### ISSUE TITLE
Research Spike: Next.js Support

### ISSUE THREAD

**Issue by rr0214** [newrelic/node-newrelic#1028]
What is the problem we are solving: Customers are not seeing transactions with the Node agent out of the box when using next.js.

What do we want to do:
Spin up a simple application with Nest.js and determine what data is not being sent up to New Relic. Transactions? Connections to external services? Document our findings. 

https://docs.google.com/document/d/1V_zNpvxRk-FvMIGBmTA1_y-ksO869bvoo_f6K5xMLZw/edit?usp=sharing

**Comment by bizob2828** [comment]
More research done here:
 * https://docs.google.com/document/d/1AWlv9JxQ5aQ5WWGfIz7r9Ds2-Ea-2njTjA4mqK_3HEA/edit?usp=sharing
 * https://docs.google.com/document/d/1B-KGS0-t69nAH2J-F6EnXbrAMD-T0Hk4FM7mGlIVLkU/edit?usp=sharing

We will be creating a new repo to house this work.  Here's a link to the [prototype branch](https://github.com/newrelic/node-newrelic/tree/next-prototype)
