### ISSUE TITLE
TypeError: Cannot read property 'agent' of undefined

### ISSUE THREAD

**Issue by minaairsupport** [newrelic/node-newrelic#1042]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
after update to node 16 I got this error 
```
TypeError: Cannot read property 'agent' of undefined
    at instrumentDatastore (/Users/minafawzy/Documents/TechModgroup/BDS-API/node_modules/newrelic/api.js:1221:23)
    at Object.<anonymous> (/Users/minafawzy/Documents/TechModgroup/BDS-API/index.ts:3:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/Users/minafawzy/Documents/TechModgroup/BDS-API/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/qy/g_lynwh536s_39w1_47zgwz40000gn/T/ts-node-dev-hook-5979901015148208.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at require.extensions.<computed> (/private/var/folders/qy/g_lynwh536s_39w1_47zgwz40000gn/T/ts-node-dev-hook-5979901015148208.js:71:20)
    at Object.nodeDevHook [as .ts] (/Users/minafawzy/Documents/TechModgroup/BDS-API/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

to be working 
[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
work in node 16 
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by garbados** [comment]
Thanks for reporting this issue. We are looking into it and will request additional information as we find need for it. Thank you for your help!

**Comment by minaairsupport** [comment]
Thanks and yea sure let me know if you need any extra info

**Comment by garbados** [comment]
Hi @minaairsupport can you share what version of the agent you are using?

**Comment by minaairsupport** [comment]
I am using the latest v8.6.0

**Comment by garbados** [comment]
Intriguing. It seems `this` must not be getting set appropriately during the invocation of the New Relic agent. Can you show me the first few lines of `BDS-API/index.ts`? Maybe the agent is being invoked incorrectly.

However, it may also be a good idea to open a ticket with New Relic tech support directly, so you can have detailed confidential conversations about your system with our support professionals. I wouldn't want you to divulge anything sensitive about your system in a public forum!

**Comment by minaairsupport** [comment]
here is the `index.ts`
```
import * as newrelic from "newrelic";

import { instrumentSlonik } from "./lib/newrelic/instrumentSlonik";
newrelic.instrumentDatastore({
  moduleName: "slonik",
  onRequire: instrumentSlonik as any,
  onError: (error) => console.log(`Got NewRelic Error ${error.message}`),
});
import { start } from "./lib";
start();
```

**Comment by darius-simplex** [comment]
This is caused by the way Typescript handles `*` imports (you can check generated JS code). It will work if you change:
```
import * as newrelic from "newrelic";
```
to
```
import newrelic from "newrelic";
```

**Comment by minaairsupport** [comment]
seems that was the issue thanks 
I am closing the issue

**Comment by josephrexme** [comment]
@darius-simplex I have this happening for the following code. Any ideas why it may be happening?
```js
let bugsnagMiddleware, newrelic

newrelic = require("newrelic")

// somewhere down the code
app.all(`/path`, async (req, res, next) => {
  newrelic.addCustomAttributes(req.query)
}
```
