### ISSUE TITLE
Increasing memory usage over time

### ISSUE THREAD

**Issue by ucarbehlul** [newrelic/node-newrelic#1068]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
Newrelic memory keeps growing. How can I avoid this situation?

## Description
I use newrelic to monitor async segments in my code. Recently I noticed a big memory usage because of shim.js code. Timers get created and callbacks get retained. I don't know how it might have happened or where it is originating from. 

Object×612820 | 2 | 22 665 9288 % | 245 711 28682 % |  
Object@5066931 | 4 | 240 % | 182 188 42461 % |  
elements::(object elements)[]@6552199 | 5 | 393 2640 % | 393 2640 % |  
[962505]::Timeout@5845729node:internal/timers:167 | 5 | 1200 % | 34 5760 % |  
_onTimeout::wrappedCallback()@3143791file:///Users/xxx/dev/xxx/xxx-client/node_modules/newrelic/lib/shim/shim.js:1172 | 6 | 640 % | 34 3840 %

You can see that this Object@5066931 retains 182 MB and it consists of timers that retain newrelic callback.

![image](https://user-images.githubusercontent.com/1509061/149635947-e9b94566-b046-412c-8717-5763f2cee6e5.png)

In my code all I do is to call:
```
newrelic.startSegment("segment", true, () => some_async_method())
```

Am I doing something wrong? What may be causing this situation? 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

Memory should not grow by newrelic usage.

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

 node --version
v16.12.0

newrelic@8.7.0

[TIP]:  # ( Include as many relevant details about your environment as possible. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by ucarbehlul** [comment]
Also lots of Transaction objects in memory. Perhaps they somehow retain each other? 

![image](https://user-images.githubusercontent.com/1509061/149636206-2e0aa41a-afb0-4e92-bbd0-ac7fdafba0a8.png)

**Comment by ucarbehlul** [comment]
> Also lots of Transaction objects in memory. Perhaps they somehow retain each other?
> 
> ![image](https://user-images.githubusercontent.com/1509061/149636206-2e0aa41a-afb0-4e92-bbd0-ac7fdafba0a8.png)

(Maybe ~1900 transactions are normal if it waits for a minute before sending them)

**Comment by michaelgoin** [comment]
Hey @ucarbehlul,

Transactions will be cleared out when they end and segments go out of context, so shouldn't need to wait a minute. Depending on the application, 1869 transactions in memory can be normal (including the many TraceSegments) and sometimes not. That TraceSegment count looks pretty high and definitely hints at a leak or delay in cleanup. If a transaction is created and never ended, that can keep everything in memory. Runaway timer chains, they get infinitely scheduled in context can also cause problems. The most common is a very small leak involving promises. If a promise gets leaked that we were maintaining context for, we'll get stuck keeping an entire transaction's segment tree in memory. Sometimes surprises come up that we have to fix.

Obviously what you shared seems to be related to timers but hard to tell what exactly could be on its own.

This is the sort of issue best routed through our support team over at support.newrelic.com. This way we can ask for more sensitive information and closer interaction. There we'll ask for some heap snapshots (which seems you are already looking at)... usually ~3: one after warm up, one after a few minutes, another after a few more minutes to help track down leaks and usually grab some logs separately as well. This way we can help diagnose if the agent is causing issues. We'll probably also want to know what frameworks are being used and maybe some code snippets of how your instrumentation is setup such as the example call you provided. Understanding how the `some_async_method` code is structured may help figure out what is going on.

**Comment by ucarbehlul** [comment]
Thanks @michaelgoin , are you saying if the promise returned by `some_async_method` never resolves, new relic agent will retain that forever? Is there an option to set a transaction timeout such as 5 minutes to tell new relic to consider that transaction dead after that point at least?

**Comment by michaelgoin** [comment]
@ucarbehlul without any special feature flags, it would be if the promise is never garbage collected. In these cases we often make a tiny memory leak in the application look much worse. There is a combination of feature flags where it would be reliant on the promise getting resolved. We don't currently have any automatic way to force a transaction to end based on timer (say for a web transaction) but also, that would not prevent a leak in the case of a leaked promise as the storage is not tied to the transaction lifecycle.

**Comment by ucarbehlul** [comment]
Thanks. I am not sure if promises actually resolve or not, but vast majority of requests have 200 status code so i would think vast majority of them resolves. Is there an easy way to see which promises it is retaining, with a stacktrace, maybe I can focus on them.

Btw, I disabled new relic setting  NEW_RELIC_ENABLED flag to false and voila, memory leak is resolved, no more SIGABRT errors because of GC collector not being able to free up memory.

**Comment by michaelgoin** [comment]
What I usually do is analyze a few memory snapshots and look for `Promise` objects that are retained across multiple GCs by toggling the "allocated between" dropdown.

**Comment by ucarbehlul** [comment]
Okay when I have some time let me run a soak test again and compare some snapshots.

**Comment by iredchuk** [comment]
Hi
Is there any reason that the issue is closed? We are experiencing the same problem, using newrelic ver. 8.17.1

**Comment by jordigh** [comment]
Hey @iredchuk 

Are you saying you're experiencing memory leaks when you call something like `newrelic.startSegment("segment", true, () => some_async_method())` yourself?

If so and the above debugging suggestions by @michaelgoin don't help, then I think the same advice applies to you: please go through our technical support so that we may gather more relevant information into the problem.

**Comment by Geczy** [comment]
i had the same issue, i decided to disable new relic for now and it fixed my memory usage

**Comment by StevenMatchett** [comment]
This also bit us and took way too much debugging to find. The issue isn't with newrelic it is with wrapping an anonymous function over a large part of code. We had segments abstracted away and when i just return a wrapper function I saw no benefits. Removing the anonymous function fixed the issue. I stripped all segments from our application
