### ISSUE TITLE
Resolved promises may cause segments to be ignored

### ISSUE THREAD

**Issue by jefersondaniel** [newrelic/node-newrelic#1076]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
When reusing a resolved promise to schedule code execution it will be ignored if the promise was created in a previous transaction.

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

Segments should be attached to current transaction.

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

The application below has a example of this behavior, moving the promise to the root will fix this but some libraries like "dataloader" have this behavior internally.

https://github.com/jefersondaniel/newrelic-promise-issue

This repo should catch the segment on first request but next requests will not track the custom segment and the following message will appear on the log:

```
{"v":0,"level":20,"name":"newrelic","hostname":"localhost","pid":16433,"time":"2022-01-20T14:58:27.819Z","msg":"startSegment(\"mysegment\") called outside of a transaction, not recording.","component":"api"}
```

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Node version: v16.13.1
Operating System and version: Linux 5.13.13-arch1-1

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment]
@jefersondaniel thanks for the repro case.  By default our promise instrumentation is using some legacy methods.  I can reproduce the issue, but the fix is to enable a feature flag to properly instrument/track promises.

When I add this to newrelic.js I do not see the issue.
```json
  feature_flag: {
    new_promise_tracking: true
  },
```

Give that a shot and let me know if it fixes your issue

**Comment by jefersondaniel** [comment]
I did some tests and it works well. Thanks!

**Comment by bizob2828** [comment]
Great. I'm going to close this issue.
