### ISSUE TITLE
Add and report test coverage

### ISSUE THREAD

**Issue by garbados** [newrelic/node-newrelic#1078]
## Is your feature request related to a problem? Please describe.

Though robust, our test suite does not report test coverage. This makes it easier to develop blindspots in testing functionality which can lead to bugs.

## Feature Description

Test coverage should be reported to a service like codecov or coveralls, and we should assert some level of coverage as part of our test suite (say, 90%).

## Describe Alternatives

🤷‍♀️ 

## Priority

Really Want

**Comment by coreyarnold** [comment]
Covered through work tracked in Jira.
