### ISSUE TITLE
There is currently no way to capture custom headers when only using ENV vars for configuration

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#1079]
Solution: we need to add the ability to set `allow_all_headers` via ENV var configuration.

The `allow_all_headers` configuration item is required for the agent to let custom headers be captured in `request.headers.*` or `response.headers.*` attributes.

This is disabled by default (even though the docs say otherwise) but set to enabled in the default config file we recommend customers start with (`newrelic.js`).

If a customer is not using a config file, they won't get this setting. Since there's no ENV var based configuration for this item, there's no way for customers to set this to true without a config file.

Temporary workarounds would include... using a config file for just setting this value with everything else overriden by ENV vars or using custom attributes.

**Comment by bizob2828** [comment]
We should also open a PR in docs-website to add the env var for this property
