### ISSUE TITLE
Proper nest.js support

### ISSUE THREAD

**Issue by Sufiane** [newrelic/node-newrelic#1106]
## Is your feature request related to a problem? Please describe.
There is currently no support of nest.js

## Feature Description
an official way to use newrelic with nest.js projects.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Really Want/Must Have

**Comment by coreyarnold** [comment]
@Sufiane Thank you so much for submitting the feature request for nest.js. We've had a few inquiries about it and are considering it along with other frameworks.

**Comment by kibertoad** [comment]
What is needed here? Isn't NestJS basically a glue over either Express.JS or fastify?

**Comment by bizob2828** [comment]
@kibertoad you're correct.  You'll get a lot of instrumentation in Nest.js from express or fastify.  You could see issues with context propagation but our solutions consultants provided a [viable workaround](https://newrelic.com/blog/how-to-relic/new-relic-nestjs)

**Comment by bizob2828** [comment]
We recommend folks use this [sample app](https://github.com/newrelic/newrelic-node-examples/tree/main/nestjs/app) as a reference.  You will get the underlying instrumentation from Express or Fastify.

**Comment by jordigh** [comment]
Of particular note is that this is a good way to start the New Relic agent, just a slight modification of the `start` command.

https://github.com/newrelic/newrelic-node-examples/blob/main/nestjs/app/package.json#L11
