### ISSUE TITLE
Add supportability metrics for common logging frameworks

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#1148]
## Is your feature request related to a problem? Please describe.
We currently only enrich logs in pino and winston.  We want to add supportability metrics when customers are requiring other popular logging frameworks so we can get an idea of any other libraries to add log enrichers.

## Feature Description
Add supportability metrics for common logging frameworks when a customer requires library.  The metric name should follow the pattern of : `Supportability/InstalledDependencies/Nodejs/<lib-name>`

- [Winston](https://www.npmjs.com/package/winston)
- [Bunyan for Node.js logging](https://www.npmjs.com/package/bunyan)
- [Pino](https://www.npmjs.com/package/pino)
- [Loglevel](https://www.npmjs.com/package/loglevel)
- [Npmlog](https://www.npmjs.com/package/npmlog)
- [fancy-log](https://www.npmjs.com/package/fancy-log)

ref: https://www.npmtrends.com/bunyan-vs-fancy-log-vs-log4js-vs-loglevel-vs-npmlog-vs-pino-vs-winston

**Comment by michaelgoin** [comment]
Turns out an internal tool may already capture what we send up on the connect request so may not need these metrics. Corey is looking into this.
