### ISSUE TITLE
Updated the config template downloaded from NR1 to enable application logging features

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#1151]
## Is your feature request related to a problem? Please describe.
We want customers using the onboarding flow to get a config with `application_logging.forwarding.enabled` set to true so they can start using log forwarding within agent with auto instrumentation.

## Additional context
We are unsure where this lives so some investigation internally will be necessary

**Comment by michaelgoin** [comment]
Add more data -> Node -> Begin Installation -> <enter app name> -> Download config.

There's may be another way to get this but that's what I just found.

**Comment by jordigh** [comment]
This is now https://source.datanerd.us/external-devbridge/setup-nerdlets/pull/73/files

I have tested locally that these changes suffice by running the "nerdlet" myself, as they call it, and downloading the file.

**Comment by jordigh** [comment]
The "upstream" PR has been merged, their team's CI will take care of moving this code onto staging and finally prod.
