### ISSUE TITLE
winston: Log warning and return when using both application logging and log enricher

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#1152]
## Is your feature request related to a problem? Please describe.
As part of log forwarding in agent, we will auto instrument and apply our current log enrichers.  However if a customer already has our log enrichers registered, this will possibly create duplicate logs.

## Feature Description
If the agent has already instrumented winston, log a warning stating you cannot use application logging and log enricher and make sure that application logging forwarding or local decorating is enabled as well. We also need a way to detect you're only using the log enricher and properly add the NR context to the log line but not add to log aggregator.

**Comment by garbados** [comment]
I experimented with this a bit in Winston, and the easiest way to do it without a shim itself was to check a wrapped thing for `__NR_unwrap`, which will be undefined *unless* we've wrapped it during instrumentation. The actual value of `__NR_unwrap` is always an unwrap function, but we don't need to ever call it. Just knowing it's there is enough.

So in Winston, we could update the log enricher with a line like...

```js
if (winston.createLogger.__NR_unwrap) {
  // winston is already instrumented. aborting...
  return
}
```

**Comment by bizob2828** [comment]
@garbados I think that'll work. I think we would not abort but log a warning and only decorate the log line with context.

**Comment by bizob2828** [comment]
Hmm, after thinking about this more I'm not sure that'll solve our issue.  In the case that `winston.createLogger` is wrapped it means `application_logging.enabled` is true and the agent did this.  However, we may just want to keep this simple and if a customer wants to continue to use the log enricher they must set `application_logging.enabled` to false

**Comment by garbados** [comment]
We could also just copy the shim's `isWrapped()` function, rather than check `__NR_unwrap`, just for consistency's sake: https://github.com/newrelic/node-newrelic/blob/main/lib/shim/shim.js#L785-L790
