### ISSUE TITLE
Logging: Infinite Tracing - adhere to data usage metrics specification

### ISSUE THREAD

**Issue by coreyarnold** [newrelic/node-newrelic#1181]
Implement the [data usage metrics specification](https://source.datanerd.us/agents/agent-specs/blob/0c52d16310bcef40cea84873408389f3d1597a98/Data-Usage-Supportability-Metrics.md)

Generate top level metrics for the following endpoints

- [ ]  InfiniteTracing

- [ ]  Update [readme](https://source.datanerd.us/agents/agent-specs/blob/main/README.md) to reflect adherence.

**Comment by bizob2828** [comment]
Based on internal conversations it appears this destination was prematurely added as the implementation details are difficult.  I'm going to close this ticket until the specification can be updated with a more clear direction on how to capture these metrics from a gRPC stream(infinite tracing)
