### ISSUE TITLE
log forwarding should not send logs when account level feature is disabled

### ISSUE THREAD

**Issue by coreyarnold** [newrelic/node-newrelic#1194]
From the point the agent receives notice from the connect service that logs should not be forwarded, no logs should be sent

## Description
If the agent is collecting logs and receives notice that logs should not be forwarded, no logs should be sent on subsequent harvest cycles.

## Expected Behavior

If the account level feature is disabled for log forwarding, new agent starts and reconnects should not send any logs.

## Steps to Reproduce

start the agent
agent sends connect request
agent collects some number of logs
connect service notifies agent that log forwarding is disabled
agent sends previously collected logs on next harvest
agent collects no more logs to 

ref: https://github.com/newrelic/newrelic-dotnet-agent/issues/1088#issuecomment-1129261734

**Comment by garbados** [comment]
Can we verify what value the server sends down to indicate that no logs should be sent?

**Comment by bizob2828** [comment]
This was addressed when #1195 was merged
