### ISSUE TITLE
Prevent this module overriding the log format for all winston transports

### ISSUE THREAD

**Issue by dpa99c** [newrelic/node-newrelic#1196]
## Description

Having just added the `newrelic` module to my node application, I now see that all the existing log transports on my winston logger instance have had their formatting overridden by your instrumentation shim:
https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentation/winston.js#L46

In particular, this breaks the rules I have configured for Cloudwatch alarms based on the application log messages being sent via the Cloudwatch transport because they are now encoded as JSON.
I understand that your agent expects the log messages in the JSON format as written to the `newrelic_agent.log`, but is there a way to prevent your formatting being applied to all other winston log transports?

## Expected Behavior

The formats defined for winston log transports by the consuming node application will not be overridden by the `newrelic` module.

## Steps to Reproduce
```
const { createLogger, format, transports } = require('winston');

const winstonLogger = createLogger({
    transports: new transports.Console({
        format: format.combine(
		    format.timestamp({
		        format:"YY-MM-DD HH:MM:SS"
		    }),
		    format.printf(
		        info => `${info.timestamp} ${info.level}: ${info.message}`
		    )
		)
    })
});

winstonLogger.log({
    level: "info",
    message: "test"
});

```

Expected log message format:
```
22-05-18 10:05:76 info: test

```

Actual log message format:

```
{"entity.guid":"MTgyMTc4MXxBUE18QVBQTElDQVRJT058MTE0MDI0MjU3Nw","entity.name":"mydomain.com","entity.type":"SERVICE","hostname":"myhost.com","level":"\u001b[info\u001b[39m","message":"\u001b[36mtest\u001b[39m","original_timestamp":"22-05-18 10:05:76","timestamp":1652867372760}

```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Module version: `newrelic@8.11.1`
* Node version: 12.14.0
* Operating System and version: Amazon Linux 2

**Comment by bizob2828** [comment]
Hi @dpa99c thanks for bringing this to our attention and sorry for the troubles. We will discuss internally and figure out how to handle this case. In the meantime you can set application_logging.enabled to false in your newrelic configuration.

**Comment by dpa99c** [comment]
Thanks for the quick response.
For now I have used this hack in my logger module:
```
const createLogger = require('winston/dist/winston/create-logger');
```

This means I create a logger using the original winston `createLogger()` function and apply my own formatting but your module still gets the shimmed version so `newrelic_agent.log` is correctly-formatted JSON.

**Comment by bizob2828** [comment]
@dpa99c so are you creating two loggers now? The config flag flip would be more appropriate so you won't have to change your code. We had some bad assumptions being made where we are forcing everything to json.

**Comment by dpa99c** [comment]
OK thanks, if `application_logging.enabled=false` has no other side effects - i.e. the NR agent will still get `newrelic_agent.log` in the correct format and my own transports will get their correct formats, I will go with that instead of my above hack.

**Comment by bizob2828** [comment]
Turning application logging off is a temporary workaround. It will disable our Winston instrumentation until we can fix this. The logging feature allows you to forward your logs to New Relic One(NR1) with no setup when application_logging.forwarding.enabled is also true. If you have no intention of seeing logs in NR1 then you can keep this disabled even after we fix this issue.

**Comment by dpa99c** [comment]
Ah, OK. I understand now. For now I have disabled it but will check with my team whether they were expecting these server application logs to be sent to NR.
