### ISSUE TITLE
move dev dependencies to devDependencies

### ISSUE THREAD

**Issue by jimmywarting** [newrelic/node-newrelic#1216]
https://github.com/newrelic/node-newrelic/blob/2ff3f568f5497ce89b2fc5f740ac677787aa4e2e/package.json#L169

trying to reduce our bundle and many dependencies comes from using [newrelic](https://npmgraph.js.org/?q=newrelic)
some things are questionable why we even have a dependency to something that is so far and unrelated to what we even use. (take emoji-regex as an example...)

anyhow one dependency that you only use in test files seems to be `concat-stream`... can you move that to dev, so that we don't have to download it as well when we run our build?

also there more newer modern ways to concat streams nowdays using simple iterators...

**Comment by bizob2828** [comment]
Hi @jimmywarting we can't move this to dev dependencies.  It is used in https://github.com/newrelic/node-newrelic/blob/main/lib/utilization/common.js but we can consider refactoring it away.  PRs are always welcome 😄
