### ISSUE TITLE
gRPC: Determine how to instrument duplex requests

### ISSUE THREAD

**Issue by garbados** [newrelic/node-newrelic#1248]
As part of our gRPC MMF, we should endeavor to instrument duplex (aka *bidirectional*) requests. In HTTP/2, it is possible for the client and server to pass information back and forth continuously in a single request, in a way that does not obviously map to a transaction. The [implementation guide](https://source.datanerd.us/agents/agent-specs/blob/main/implementation_guides/gRPC.md) does not provide a clear description of how to handle this, so we'll have to figure it out for ourselves.

For more information about duplex requests, see this relevant method in grpc-js, [makeBidiStreamRequest](https://grpc.github.io/grpc/node/grpc.Client.html#makeBidiStreamRequest), and in the [core concepts](https://grpc.io/docs/what-is-grpc/core-concepts/) documentation on [grpc.io](https://grpc.io).

This issue may be closed once we have consensus on how to instrument a duplex stream in a way that is useful to users.

**Comment by garbados** [comment]
In discussion, we floated a naive approach for handling streams:

- ignore that they're streams
- start your external when the request begins
- end it when they get a status
- and then just track all of that as a transaction

For comparison of this approach to other agents, consider these implementations:

- [Java](https://github.com/newrelic/newrelic-java-agent/tree/72bdebce3d80ec22a674e3e33be5444c12fb2d58/instrumentation/grpc-1.40.0/src/main/java/com/nr/agent/instrumentation/grpc)
- [Python](https://github.com/newrelic/newrelic-python-agent/blob/ad65494033a6aef95fa2cd10b49ae73cb4c612ed/newrelic/hooks/framework_grpc.py)
- [Go](https://github.com/newrelic/go-agent/tree/master/v3/integrations/nrgrpc)

If we can determine a higher-definition means of instrumenting streams than the above naive approach, that would be better.

**Comment by bizob2828** [comment]
I'm going to close this as we're going with the easiest path to start.  We're already instrumenting the base method for all grpc client requests and I added a test to verify bidi streaming works just fine.  It may not makes sense to run a bidi stream in a single transaction but that will be the caveat in the first MMF until we can get some feedback.
