### ISSUE TITLE
gRPC: Instrument duplex requests

### ISSUE THREAD

**Issue by garbados** [newrelic/node-newrelic#1249]
Once we have determined [how to instrument duplex requests](https://github.com/newrelic/node-newrelic/issues/1248), we should instrument them to match the [implementation guide](https://source.datanerd.us/agents/agent-specs/blob/main/implementation_guides/gRPC.md). This way, when users make duplex requests with a gRPC client, meaningful telemetry can be collected and reported to New Relic.

**Comment by bizob2828** [comment]
I'm closing this as I confirmed there is no instrumentation needed. I will be writing tests for client, server and bidi streams in https://github.com/newrelic/node-newrelic/issues/1261
