### ISSUE TITLE
Demo gRPC instrumentation internally

### ISSUE THREAD

**Issue by garbados** [newrelic/node-newrelic#1252]
We should demo our accomplishments with regards to gRPC instrumentation once we have things to show. This will include:

- [x] An example app that pushes data to New Relic via a gRPC server and client.
- [x] A presentation discussing the data that gets pushed and how users will encounter it.
- [x] If anything, highlight what is still to be done.

Our next demo day is June 16, so this should be ready by then.

**Comment by bizob2828** [comment]
We demo'd feature to @coreyarnold our interim PM and he approved the work.  We did notice we are sending the component up as `gRPC` but it is getting rendered as http for the grpc external span.  We need to talk with the collector to see why

```
{\"grpc.statusCode\":0,\"grpc.statusText\":\"OK\",\"component\":\"g       RPC\",\"http.url\":\"grpc://localhost:50051/routeguide.RouteGuide/ListFeatures\",\"http.method\":\"/rou       teguide.RouteGuide/ListFeatures\"
```
