### ISSUE TITLE
gRPC: Documentation updates

### ISSUE THREAD

**Issue by garbados** [newrelic/node-newrelic#1254]
Once the gRPC instrumentation is ready to ship, we should update our [compatibility docs](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent/) to mention that `@grpc/grpc-js` is supported. This page doesn't have a catch all for other miscellaneous libraries.  But we failed to include other things like undici.

**Comment by jordigh** [comment]
Closed by https://github.com/newrelic/node-newrelic/blob/main/lib/feature_flags.js
