### ISSUE TITLE
Add support for popular NATS.js(MQ client)

### ISSUE THREAD

**Issue by samuraitruong** [newrelic/node-newrelic#1264]
## Is your feature request related to a problem? Please describe.
Yes, we need to add instrument for some of our MQ client such as  - https://github.com/nats-io/nats.js
## Feature Description
- Allow report all request/respond as the background transaction
## Describe Alternatives
I have to wrap the 3rd library and add nr.startBackgroundTransaction  but it nice to have support out of the box
## Additional context
Add any other context here.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Nice to have

**Comment by bizob2828** [comment]
Moving request to Roadmap board for PM to prioritize

**Comment by novagen** [comment]
Mpst of our communication between micro services are done through NATS, so this would be a great addition.
