### ISSUE TITLE
Ignore server-side settings.

### ISSUE THREAD

**Issue by pburkholder** [newrelic/node-newrelic#1266]
## Is your feature request related to a problem? Please describe.

It looks like I have to turn off New Relic. A current support case indicates there’s no way for the current node-js agent to ignore “server-side” configuration. So a malicious actor within New Relic will _ALWAYS_ be able to prompt agents to start sending error logs. Even High Security would not be immune to this vector.

I'm not saying it's a likely threat, I just have to pay the sacrifice to the compliance gods.

What could work? A feature to turn off server-side configuration via a setting in newrelic.js like "REALLY_TRULY_IGNORE_SERVERSIDE: true" 

Can you consider that?

## Feature Description

An agent setting that can't be overriden to completely ignore server-side configuration.

## Describe Alternatives

Can't think of any.

## Additional context

Required for FedRAMP JAB compliance

## Priority

Blocker. Can no longer use New Relic

**Comment by bizob2828** [comment]
@pburkholder I want to clarify what you mean by 

> So a malicious actor within New Relic will ALWAYS be able to prompt agents to start sending error logs. Even High Security would not be immune to this vector.

Do you mean sending errors generated by your app or sending logs with level `error`?

**Comment by pburkholder** [comment]
I meant:
>  sending errors generated by your app

**Comment by bizob2828** [comment]
I confirmed we get the server side config payload under 1 key after connect.  this should be as simple as checking if the config value to ignore server side config is set and skip updating the local configuration

**Comment by jordigh** [comment]
@pburkholder In case you missed it, this feature is now available as of agent version 8.15.0 released last week.

https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-8-15-0/
