### ISSUE TITLE
Provide API method to enqueue log lines to agent log aggregator

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#1267]
## Is your feature request related to a problem? Please describe.
We've had several customers request adding support for various logging libraries or just the ability to add log lines to our agent log aggregator.

## Feature Description
Provide an API method for adding log lines to agent from customer app for logging libraries the agent does not support.

## Additional context
We will want to provide examples of how to decorate a log line with NR context and then how to add to the agent.

 * [Discuss request](https://discuss.newrelic.com/t/node-js-uploads-logs-of-node-js-socket-io-application-running-with-pm2-and-log4js/187721)
 * [console.log support](https://newrelic.slack.com/archives/C0511B24H/p1656035818289119?thread_ts=1656035818.289119)
 * Chat with other agent developers to create a spec

**Comment by coreyarnold** [comment]
Considering this for near term work.
