### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by gabrielalmeida** [newrelic/node-newrelic#1308]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

Application randomly crashes with the following stack trace:

```js
log | TypeError: Cannot read properties of undefined (reading 'length')
log |     at truncate (/app/node_modules/.pnpm/newrelic@8.17.0/node_modules/newrelic/lib/util/application-logging.js:19:11)
log |     at reformatError (/app/node_modules/.pnpm/newrelic@8.17.0/node_modules/newrelic/lib/instrumentation/pino/pino.js:149:28)
log |     at formatLogLine (/app/node_modules/.pnpm/newrelic@8.17.0/node_modules/newrelic/lib/instrumentation/pino/pino.js:130:7)
log |     at /app/node_modules/.pnpm/newrelic@8.17.0/node_modules/newrelic/lib/aggregators/log-aggregator.js:46:16
log |     at Array.map (<anonymous>)
log |     at LogAggregator._toPayloadSync (/app/node_modules/.pnpm/newrelic@8.17.0/node_modules/newrelic/lib/aggregators/log-aggregator.js:44:32)
log |     at LogAggregator.send (/app/node_modules/.pnpm/newrelic@8.17.0/node_modules/newrelic/lib/aggregators/base-aggregator.js:105:32)
log |     at listOnTimeout (node:internal/timers:559:17)
log |     at processTimers (node:internal/timers:502:7)

```

The stack trace suggests something is wrong with `pino` instrumentation, which is the logger library being used in the project.

## Expected Behavior

To not crash.

[NOTE]: # ( Tell us what you expected to happen. )

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

NodeJS v16 via Docker (FROM node:16-slim img)
newrelic@8.17.0

**Comment by bizob2828** [comment]
Thanks for the bug @gabrielalmeida            
I see the issue. We will get a fix landed and released. Sorry for the troubles.
