### ISSUE TITLE
NewRelic was not showing transaction tab in my project

### ISSUE THREAD

**Issue by bandipooja** [newrelic/node-newrelic#1331]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bandipooja** [comment]
here @find the screenshot of my project,am not able to see the transaction tab 
![image](https://user-images.githubusercontent.com/103558468/184810115-1eb34027-d6ca-475a-b7bf-f5aa9b7da436.png)

**Comment by bandipooja** [comment]
![image](https://user-images.githubusercontent.com/103558468/184810551-1107a1e6-931c-4fea-9800-a774c8a7e8d1.png)
Please find above image here amnot able to see the transaction tab in my project

**Comment by coreyarnold** [comment]
@bandipooja Thanks for the report. Have you opened a support case for this? Our Global Technical Support can likely help get you sorted out and if not, they can gather some much needed information to hand off to our engineering team.

**Comment by bandipooja** [comment]
ok thanks

**Comment by bizob2828** [comment]
I'm closing this issue as it was redirect to customer support
