### ISSUE TITLE
New Relic is eating up our CPU

### ISSUE THREAD

**Issue by alex-grifin** [newrelic/node-newrelic#1334]
We are doing profiling of our node.js instance. We are noticing a high CPU utilization. 

## Description

I noticed that several functions from new relic are using a lot of cycle from the cpu - where majority of our cpu is used by newrelic. I see one "anonymous" function is taking as much as 1012.1ms and total time across our whole stack is 609kms over a 5 minute window.

The trouble code seems to be in `node_modules/newrelic/lib/shim/shim.js`.

I see other methods that have high amount of time spent per function all within the same shim file:

-  storeSegment
- wrapEachPropert
- _wrap
- wrapper

## Expected Behavior

Way less CPU utilized - I'd expect no call to be more than 50ms ever.

## Steps to Reproduce

Using newrelic with a simple config file. New relic's version is 9.0.0 (we saw same issue on 8.x.x and 7.x.x)

## Your Environment

* ex: Node version: 16.14.2
* ex: Operating System and version: ECS fargate

## Additional context

I'd be happy to get on a call and share our profiler to look at what is going on.

**Comment by bizob2828** [comment]
Hi @alex-grifin depending on your application, the agent instrumentation could provide more overhead than 50ms. 

> I'd be happy to get on a call and share our profiler to look at what is going on.

For issues like this, I recommend leveraging our support team over at support.newrelic.com which can help deep-dive into solving the problem. They will also ask to collect the necessary information which may or may not be sensitive (such as logs, heap snapshots, etc).
