### ISSUE TITLE
Space after message when using Pino & `NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED`

### ISSUE THREAD

**Issue by regan-karlewicz** [newrelic/node-newrelic#1379]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

When using pino with the `NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED` environment variable to have new relic linking information added to my logs, the `message` field in the logs ingested by New Relic all have an extra space at the end.

E.g. if I call `logger.info("InformationMessage")` in my code, it shows up as `"InformationMessage "` in New Relic.
 
Note: this occurs both when using an infrastructure log forwarder, or the agent `NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED` functionality

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

The log's `message` field in New Relic should not have an extra space at the end. It should just be `"InformationMessage"`

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

Here is a minimal reproducible application

```js
const dotenv = require('dotenv');
dotenv.config();
const newrelic = require('newrelic');
const express = require('express');
const pino = require('pino');
const logger = pino({});

const app = express();
app.use('/', (req, res) => {
  logger.info('HelloWorld');
  res.status(200).send('OK');
});

app.listen(3000, () => {
  logger.info('Server started');
});
```

My environment file is as follows:

```txt
NEW_RELIC_ENABLED=true
NEW_RELIC_NO_CONFIG_FILE=true
NEW_RELIC_APP_NAME="test-app"
NEW_RELIC_LICENSE_KEY=<redacted>
NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=true
NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=true
```

The above program creates this log message in New Relic (notice the space at the end)
<img width="510" alt="Screen Shot 2022-10-11 at 9 24 02 AM" src="https://user-images.githubusercontent.com/1987265/195148655-29d14ba8-7ae8-485d-9273-ab0d864d97d8.png">

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Browser name and version: N/A
Node version: v16.13.0
Operating System and version: MacOS 12.3.1, but also occurs on Bitnami NodeJS 16 container

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jmartin4563** [comment]
hiya @regan-karlewicz, thank you for logging an issue (and the minimal repro app!)
Just dropping a note that I'll be taking a look at this :)

**Comment by jmartin4563** [comment]
@regan-karlewicz small update: we can see the issue you've reported, and we're currently having discussion on how to address, will keep you posted!

**Comment by jmartin4563** [comment]
@regan-karlewicz just circling back now to make sure this issue is fixed for you. I did a sanity check with your repro app and no longer see the trailing space, but let me know if you're still having issues.
