### ISSUE TITLE
gRPC ignore_status_codes

### ISSUE THREAD

**Issue by stellar-scottreed** [newrelic/node-newrelic#1401]
## Is your feature request related to a problem? Please describe.
There is currently a configuration flag for not throwing an error on specified HTTP codes (ignore_status_codes). There is a record_errors flag for gRPC for compeltely disabling the reporting of gRPC errors, but it is not currently possible to my knowledge to only not report specific gRPC status codes.

## Feature Description
It would be useful to have a similar feature for ignoring certain gRPC status codes for users that would not like to have all non-zero status codes reported as an error. Something like grpc.ignore_status_codes.

## Describe Alternatives
grpc.record_errors could be disabled, or newrelic.reportError could be used within server gRPC error handling.

## Additional context
@jordigh requested this issue to be created

## Priority
Nice to Have

**Comment by jordigh** [comment]
@stellar-scottreed I'm working on this feature.

I would appreciate your opinion on the following. Do you think it will suffice to have a single set of codes to ignore both in gRPC client and server instrumentation? Or do you think we should have separate codes for each?

Additionally, what are the status codes that you were seeing the most often in your case?

**Comment by jordigh** [comment]
@stellar-scottreed FYI, this feature is now shipped in Node agent version 9.7.0.

https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-9-7-0/

**Comment by stellar-scottreed** [comment]
Sorry for not responding to your earlier comment, I didn't receive a notification. Thank you for adding this! Resurfacing this because the environmental variable does not work @jordigh. Comma separated list placed in NEW_RELIC_GRPC_IGNORE_STATUS_CODES become an array of strings in the grpc.ignore_status_codes config. The statusCode variable in the shouldTrackError function in grpc.js is an integer.

https://github.com/newrelic/node-newrelic/blob/12d2fda59cac01600fe22b4ca9b1f3b68e10a80c/lib/instrumentation/grpc-js/grpc.js#L226

The array of strings would need to be parsed to an array of integers for this function to work because .includes() does a strict comparison of array elements.

Setting the variable within newrelic.js as an array of integers does work fine.

Thank you!
