### ISSUE TITLE
FATAL ERROR: v8::FromJust Maybe value is Nothing

### ISSUE THREAD

**Issue by juanjoseruiz** [newrelic/node-newrelic#1471]
After upgrading newrelic from latest 8.x to 9.7.4 we are getting unexpected application crashes when running newrelic inside a worker_thread.

I was able to track down a little bit more and it reproduces on 9.1.0 but works fine on 9.0.0

## Description

Getting unexpected crashes with the following call stack:

FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb17ec0 node::Abort() [node]
 2: 0xa341f4 node::FatalError(char const*, char const*) [node]
 3: 0xcfe46a v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xb1bb1d node::fs::FileHandle::CloseReq::Resolve() [node]
 5: 0xb1bc79  [node]
 6: 0x158ab2d  [node]
 7: 0x158f186  [node]
 8: 0x15a1f15  [node]
 9: 0x158fab8 uv_run [node]
10: 0xa59f25 node::SpinEventLoop(node::Environment*) [node]
11: 0xbdd23a node::worker::Worker::Run() [node]
12: 0xbdd9c8  [node]
13: 0x7f0b450e2b43  [/lib/x86_64-linux-gnu/libc.so.6]
14: 0x7f0b45174a00  [/lib/x86_64-linux-gnu/libc.so.6]
Aborted (core dumped)

This one is also being triggered:

FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0xb17ec0 node::Abort() [node]
 2: 0xa341f4 node::FatalError(char const*, char const*) [node]
 3: 0xcfe46a v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xb12f19 node::fs::FSReqPromise<node::AliasedBufferBase<double, v8::Float64Array, void> >::SetReturnValue(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 5: 0xb240ca  [node]
 6: 0xd655cb  [node]
 7: 0xd66a6c  [node]
 8: 0xd670e6 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 9: 0x16148d9  [node]
Aborted (core dumped)

## Expected Behavior

It should be working fine as on 8.x version

## Steps to Reproduce

I isolated the problem just by spawning a thread in loop that just calls newrelic and returns a simple result. The code crashes with latest 9.7.4 after some time whereas works fine with latest 8.x

The code uses https://github.com/andywer/threads.js/ to spawn the thread, but it's using native nodeJS workers under the hood.

main.js
```
const newrelic = require('newrelic');
const {spawn, Thread, Worker } = require('threads');

launchChildThread = async function() {
    while (true) {
        const thread = await spawn(new Worker('./worker'));
        try {
            newrelic.incrementMetric('triggers', 1);
            const result = await thread.doStuff();
            console.log(`received success: ${result.success}`)
        } finally {
            await Thread.terminate(thread);
        }    
    }
}

launchChildThread();
```

worker.js

```
const newrelic = require('newrelic');
const { expose } = require('threads');

expose({
    async doStuff() {
        console.log('worker:doStuff');
        newrelic.startBackgroundTransaction('background transaction');
        await new Promise(resolve => setTimeout(resolve, 1000));
        newrelic.incrementMetric('executions', 1);
        return {success: true};
    }
});
```
## Your Environment

* NodeJS 16 / NodeJS 18
* Ubuntu 20.04
* Alpine Linux (node:16 image)

## Additional context

I tried to call shutdown() method from newrelic in the worker thread before return statement, but it doesn't seem to have any effect.

I suspect the problem is happening when calling Thread.terminate as the last printed logs are from there, but it's crashing the main process. I suspect there may be something pending to flush from newrelic while releasing the memory.

**Comment by bizob2828** [comment]
Thanks for the reproduction case @juanjoseruiz and sorry for the troubles. We will take a look at get back to you if we have any questions.

**Comment by juanjoseruiz** [comment]
Thanks @bizob2828 for the support!

I've updated the description as I think the issue starts happening on 9.1.0 (I am not able to reproduce on 9.0.0) just in case it helps.

I've also seen this other stack trace that looks slightly different:

node[81586]: ../src/node_file-inl.h:160:node::fs::FSReqPromise<AliasedBufferT>::~FSReqPromise() [with AliasedBufferT = node::AliasedBufferBase<double, v8::Float64Array>]: Assertion `finished_' failed.
 1: 0xb17ec0 node::Abort() [node]
 2: 0xb17f3e  [node]
 3: 0xb12dba  [node]
 4: 0xb1e2f2 node::fs::FSReqAfterScope::~FSReqAfterScope() [node]
 5: 0xb1ed4e node::fs::AfterOpenFileHandle(uv_fs_s*) [node]
 6: 0x158ab2d  [node]
 7: 0x158f186  [node]
 8: 0x15a1f15  [node]
 9: 0x158fab8 uv_run [node]
10: 0xa59f25 node::SpinEventLoop(node::Environment*) [node]
11: 0xbdd23a node::worker::Worker::Run() [node]
12: 0xbdd9c8  [node]
13: 0x7febebbb2b43  [/lib/x86_64-linux-gnu/libc.so.6]
14: 0x7febebc44a00  [/lib/x86_64-linux-gnu/libc.so.6]
Aborted (core dumped)

**Comment by bizob2828** [comment]
@juanjoseruiz ok 9.0.1 was a [removal of the async library](https://github.com/newrelic/node-newrelic/pull/1325).  I'm wondering if this bug has already been fixed. We're in a code freeze but we have a pending change that was affecting something else.  Either way I'll get to the bottom of it

**Comment by juanjoseruiz** [comment]
I've just tried and I can also reproduce in 9.0.1 (still unable to repro on 9.0.0) so that makes sense.

I also reproduce it in the latest 9.7.4 as indicated in the description so at least is not fixed for me.

Thanks again for your help! Please, let me know if there is anything else I can help with.

**Comment by bizob2828** [comment]
@juanjoseruiz the fix I'm describing hasn't been released yet.  It will be out in 9.7.5 but I plan on starting there to see if a fix exists

**Comment by juanjoseruiz** [comment]
Thanks! will keep en eye on the releases and test on 9.7.5 as well!

**Comment by bizob2828** [comment]
@juanjoseruiz does this take time to crash? I'm running on my macbook and it's chugging away with no issue. I can also try on a docker container but was hoping to reproduce on my local machine first

**Comment by bizob2828** [comment]
@juanjoseruiz this doesn't seem to happen for me all the time and after applying the recommended changes below I haven't seen the crash. Regardless I don't recommend using the agent this way.  By requiring the agent in the worker thread it's spawning up a new instance of the agent.  Instead I would pass the agent from the parent process into the worker. As for how to properly do that I'm not sure as we technically don't support worker threads this is new territory.

Also, I'm not sure if this was just an oversight to show a reproduction or how you're actually using `startBackgroundTransaction` but it needs to have the code that's running in the background transaction within a callback

```js
const newrelic = require('newrelic');
const { expose } = require('threads');

expose({
    async doStuff() {
        return await newrelic.startBackgroundTransaction('background transaction', async () => {
          console.log('worker:doStuff');
          await new Promise(resolve => setTimeout(resolve, 1000));
          newrelic.incrementMetric('executions', 1);
          return {success: true};
        });
    }
});
```

Lastly, if you want to proceed with spawning a new agent in every process you will have to shutdown the agent within the worker.js like this

```js
const newrelic = require('newrelic');
const { expose } = require('threads');

expose({
    async doStuff() {
        const data =  await newrelic.startBackgroundTransaction('background transaction', async () => {
          console.log('worker:doStuff');
          await new Promise(resolve => setTimeout(resolve, 1000));
          newrelic.incrementMetric('executions', 1);
          return {success: true};
        });

      await new Promise((resolve) => newrelic.shutdown({ collectPendingData: true }, resolve))
      return data
    }
});
```

As you can see when running this the worker process gets slowed down because it has to flush the agent.

**Comment by juanjoseruiz** [comment]
I tried to shutdown but I was not awaiting for the callback to be called. I will try doing in the proposed way and will reopen if still happens.

Thanks for the rest of suggestions, I take note and apply the ones I can to our production code.

Thanks also for sorting everything out so quickly  :)

**Comment by bizob2828** [comment]
@juanjoseruiz I had this running overnight and 0 crashes. So I suspect this should fix your issue
