### ISSUE TITLE
Could not integrate new relic with nestjs application

### ISSUE THREAD

**Issue by ShubhamTiwariZee** [newrelic/node-newrelic#1477]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I am trying to integrating the new relic with my nestjs application to monitor logs but could not able to integrate it.  I am using the the nodeJS agent as guided in the documentation. Also using **winston** with new relic to emit the logs. 

Nestjs application uses Typescript as language hence I am writing new relic file with **.ts** extension. I have two questions :
1. I have to pass app_name and license_key as node env while running the application. Is the Typescript file not supported by new relic?
2. What could be best way to connect new relic with nestjs application ?

## Expected Behavior
Should be able to send the logs as done for the node js based applications . 

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* New relic npm version: 9.7.5
* Node version: v18.12.0
* Docker version: 20.10.21

**Comment by jordigh** [comment]
Hi, have you already tried these instructions?

https://newrelic.com/blog/how-to-relic/new-relic-nestjs

**Comment by jordigh** [comment]
I would like to add that our agent does not actually currently have support for NestJS. We have an open feature request about this, #1106, feel free to chime in there. In the meantime, the blog post above might give you some ideas for some workarounds.

**Comment by bizob2828** [comment]
@ShubhamTiwariZee  I know this has been a while but we determined Nest.js just works but it may be tricky to understand how to load our agent.  Take a look at this [sample app](https://github.com/newrelic/newrelic-node-examples/tree/main/nestjs/app)
