### ISSUE TITLE
Web External Transactions are almost completely gone in UI after upgrading to latest Node 18 and latest newrelic version

### ISSUE THREAD

**Issue by faresabukhiarah** [newrelic/node-newrelic#1478]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Since upgrading to Node 18 (v18.12.1) and upgrading the newrelic npm package to latest ([~9.7.5](https://npmjs.com/package/newrelic)) we are suddenly missing most of our web transactions in the newrelic UI

<img width="2031" alt="Screenshot 2023-01-12 at 15 22 42" src="https://user-images.githubusercontent.com/92319320/212099081-34a2c8c6-d04b-4dcd-8c04-baced0c90772.png">

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

Expected to still see the webtransactions

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version: v18.12.1
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jordigh** [comment]
For issues like this, I recommend leveraging our support team over at [support.newrelic.com](http://support.newrelic.com/) which can help deep-dive into solving the problem. They will also ask to collect the necessary information which may or may not be sensitive (such as logs).
