### ISSUE TITLE
Support for multi-value parameters in Amazon API Gateway and ELB to Lambda functions

### ISSUE THREAD

**Issue by Engerim** [newrelic/node-newrelic#1486]
## Is your feature request related to a problem? Please describe.

At flaconi we are using heavily nodejs lambdas which are coming through an elb, these lambdas are using multi Value parameters, `multiValueQueryStringParameters ` and `multiValueHeaders `, as this sdk is only looking for the normal headers field, no trace header is parsed and we would be forced to manually instrument these which is too much of a work. Also sind end of 2018 api gateway is supporting multi value parameters. 

## Feature Description
In the check and parsing of [the event in the sdk](https://github.com/newrelic/node-newrelic/blob/22958a0c53e8faa35eb45d32cbe82acedede486b/lib/serverless/api-gateway.js#L45) we need to enrich it to also check for multi value parameters, evtl other parts need also be touched, that is the one where I saw why it does not work for our lambdas

## Priority
Blocker

Also I'm happy to provide an pr for this feature request if you would like

**Comment by bizob2828** [comment]
@Engerim we would love a PR for this feature request.

**Comment by Engerim** [comment]
okay I will provide a pr for this
