### ISSUE TITLE
Instrument native `fetch` in Node 18+

### ISSUE THREAD

**Issue by siosphere** [newrelic/node-newrelic#1492]
## Is your feature request related to a problem? Please describe.
We recently upgraded to Node 18.x, and swapped to using the native experimental `fetch` API, and noticed that it is no longer instrumented, and no calls with the native fetch show as external segments.

## Feature Description
Have the native `fetch` api be fully instrumented

## Describe Alternatives
We have manually instrumented around our calls to have some insight, but it still isn't 100%

## Priority
Really Want

**Comment by danielbigler** [comment]
As some time has passed since this issue has been opened: are there any plans to instrument fetch natively in the forseeable future? 😄

**Comment by bizob2828** [comment]
@danielbigler yes there is. Our roadmap has this slated for the upcoming quarter.

**Comment by bizob2828** [comment]
@danielbigler this has been released in [v11.1.0](https://github.com/newrelic/node-newrelic/releases/tag/v11.1.0)
