### ISSUE TITLE
Newrelic agent throws errors when returning a response with no headers serverless project using NR layer

### ISSUE THREAD

**Issue by responsible-chris** [newrelic/node-newrelic#1503]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Recent lambdas (deployed since Feb 9th, and therefore getting the latest version of the Newrelic agent) are logging errors in the Newrelic layer code if we return a response without headers.  Our lambdas still seem to function correctly and return results, but logging lots of these errors.

I believe it is this code that throws:
https://github.com/newrelic/node-newrelic/blob/cffdce762745a1b46b1f5b2da546f6597216978a/lib/serverless/api-gateway.js#L71

Error message logged

`2023-02-10T21:02:30.910Z	9931d591-5ea1-45b1-b4d3-dfb45838c6c8	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot convert undefined or null to object","reason":{"errorType":"TypeError","errorMessage":"Cannot convert undefined or null to object","stack":["TypeError: Cannot convert undefined or null to object","    at Function.entries (<anonymous>)","    at normalizeHeaders (/opt/nodejs/node_modules/newrelic/lib/serverless/api-gateway.js:71:12)","    at new LambdaProxyWebResponse (/opt/nodejs/node_modules/newrelic/lib/serverless/api-gateway.js:35:20)","    at processApiGatewayLambdaProxyResponse (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:306:27)","    at onThen (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:207:13)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot convert undefined or null to object","    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)","    at process.emit (node:events:513:28)","    at process.wrappedEmit (/opt/nodejs/node_modules/newrelic/lib/instrumentation/core/globals.js:54:23)","    at process.wrappedEmit [as emit] (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:100:23)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}`

prettied up

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot convert undefined or null to object",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot convert undefined or null to object",
        "stack": [
            "TypeError: Cannot convert undefined or null to object",
            "    at Function.entries (<anonymous>)",
            "    at normalizeHeaders (/opt/nodejs/node_modules/newrelic/lib/serverless/api-gateway.js:71:12)",
            "    at new LambdaProxyWebResponse (/opt/nodejs/node_modules/newrelic/lib/serverless/api-gateway.js:35:20)",
            "    at processApiGatewayLambdaProxyResponse (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:306:27)",
            "    at onThen (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:207:13)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot convert undefined or null to object",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)",
        "    at process.emit (node:events:513:28)",
        "    at process.wrappedEmit (/opt/nodejs/node_modules/newrelic/lib/instrumentation/core/globals.js:54:23)",
        "    at process.wrappedEmit [as emit] (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:100:23)",
        "    at emit (node:internal/process/promises:149:20)",
        "    at processPromiseRejections (node:internal/process/promises:283:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```

## Expected Behavior

Not to generate errors.  WORK around is to make our lambdas return an empty header object.

## Steps to Reproduce

node lambda using the latest NR layer
have an HTTP endpoint
don't return headers

## Your Environment

- AWS lambda
- Node 18
- Typescript

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jmartin4563** [comment]
@responsible-chris thank you for the bug report, I'll be taking a look at this and will keep you updated

**Comment by jmartin4563** [comment]
@responsible-chris Agent version `9.10.1` and the layer were published yesterday with a fix, let me know if you're still seeing issues.

**Comment by responsible-chris** [comment]
@jmartin4563 great work, thanks for fixing it.  Confirmed it fixes it for us, I have removed my work around!
