### ISSUE TITLE
TCP Connection to Suspicious Newrelic IP 

### ISSUE THREAD

**Issue by kalsans** [newrelic/node-newrelic#1524]
There is an issue about "codestream.codestream-14.15.2/dist/agent.js" file, this extension connecting suspicious newrelic IP. And this IP is: 162.247.241.2  This connection is TCP and port is 443

162.247.241.2:443

Why we are getting alert about this IP ?

BR

**Comment by bcanzanella** [comment]
Hi @kalsans this is Brian from the CodeStream team here at New Relic. CodeStream uses the New Relic NodeJS agent to send telemetry data about how the CodeStream extensions are used.

**Comment by kalsans** [comment]
Hi,

Thank  you for answer. 

This IP is in Abuse IP List. That's why we got this alert.

BR
