### ISSUE TITLE
Report uncaught exceptions and unhandled rejections before exiting

### ISSUE THREAD

**Issue by gzurbach** [newrelic/node-newrelic#1561]
I've been trying to track down an unreported error in New Relic for the past few days. Until I realized that New Relic wasn't able to report the error because it's an unhandled rejection that kills the node process before New Relic has time to harvest the logs.

Reporting unhandled errors seems to be a key feature for a monitoring tool. When I installed NewRelic, I expected it to behave this way by default, or at least via a configuration option.

After quite a bit of digging, I ended up with the following alternative solution:

```js
// Start New Relic monitoring
const newrelic = require("newrelic");

// Initialise Winston
const logger = require("./utils/logger");

// Make sure to report uncaught exceptions and unhandled rejections to New Relic
const reportErrorAndExit = (err) => {
  logger.error("Fatal error:", err);
  if (err instanceof Error) {
    newrelic.noticeError(err);
  }
  newrelic.shutdown({ collectPendingData: true }, (err) => {
    if (err) {
      logger.error("Error shutting down Newrelic agent:", err);
    }
    process.exit(1);
  });
};
process.on("uncaughtException", reportErrorAndExit);
process.on("unhandledRejection", reportErrorAndExit);

// Start the app
const app = require("./app")();
```

Is there any reason `node-newrelic` does not support this as a core feature? 

It could be activated via the following options:
```js
exports.config = {
  app_name: ["My app"],
  logging: {
    level: "info",
    uncaughtException: true,
    unhandledRejection: true,
  },
}
```

I haven't tested it, but it seems to be the [default behaviour](https://docs.sentry.io/product/sentry-basics/integrate-backend/capturing-errors/) in Sentry:

<img width="763" alt="Screenshot 2023-03-22 at 09 45 06" src="https://user-images.githubusercontent.com/795927/226848303-fdd88803-d27c-4d6a-9f62-be82a96cd91a.png">

If there are good reasons for not adding this as a core feature, it should at least be documented somewhere (maybe it is?). Thank you for considering this!

**Comment by mrickard** [comment]
@gzurbach The NR agent's instrumentation of uncaught exceptions can be found in https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentation/core/globals.js, and it's been documented in agent release notes: https://docs.newrelic.com/?q=UncaughtException

**Comment by gzurbach** [comment]
@mrickard Thanks for pointing that out. I spoke too fast and should not have made assumptions :) 

I've ran a series of tests in my app and it seems like uncaught exceptions and unhandled rejections are _sometimes_ reported in New Relic, but not always.

To tun my tests, I added a `throw new Error("foobar")` in a route and hit the route with my browser. It seems like the error was reported about 1/3 of the time (I checked both New Relic logs and APM errors).

I don't have an explanation for why the error reporting is intermittent, maybe it's due to the node process being killed before newrelic had time send the logs?

On the other hand, the solution I shared above seem to work 100% of the time.

Side note: I am running the node app in Docker, with Kubernetes responsible to restart the pod when it crashes. The [documentation](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent-docker/) states it's possible to run the agent the following way: `node -r newrelic app.js` instead of requiring New Relic in the first line of code, does it makes any difference?

Feel free to close this issue if you think there is no need to explore this topic further 👍

**Comment by mrickard** [comment]
@gzurbach Starting your app with `node -r newrelic app.js` or including the agent explicitly in the first line of code should be equivalent. You'll still need to require the agent explicitly at the top of a file, though, if you're referencing `newrelic.*` methods in that file's code.

As for inconsistent error delivery...it's hard to say. The Node Agent collects telemetry and sends it at regular intervals. While it should also send on uncaught exception, it would depend on the timing and nature of the exception and the application environment whether or not that send would have time to begin or complete.

**Comment by TraGicCode** [comment]
I'm noticing the same issue on my end.  I have added the above code mentioned by @gzurbach to hopefully catch the real exception.  I will report back my findings when the container crashes.

@gzurbach , did you find a solution or did you just leave this code in your agent to catch what newrelic was not reporting?

**Comment by TraGicCode** [comment]
I have verified that adding the above code is indeed logging the unhandled exception that is not being logged/captured by the newrelic-node agent.
