### ISSUE TITLE
Having a url parameter called :id in the express route will cause trace spans to break and miss their parent

### ISSUE THREAD

**Issue by itai-codefresh** [newrelic/node-newrelic#1574]
## Description
When using express if you have `:id` in your url parameter it will break the transaction traceability.
it means that you will see many spans that has lost its parent.
I could not understand why this happens.
You can workaround this easily by just not using the `id` keyword and switch to something else, but this requires us to make changes in many places.

* it does not matter where in the url the `:id` will appear, as long as it appears once it will break.

* see attached screenshots to see the difference of the trace when the parameter is `:id` vs `:name`

### When using `:id` - broken
![Screen Shot 2023-03-29 at 17 51 23](https://user-images.githubusercontent.com/10414627/228581141-652117d0-b254-4172-a9e5-ff00a573ea4c.png)

### When using `:name` - working
![Screen Shot 2023-03-29 at 17 57 41](https://user-images.githubusercontent.com/10414627/228580788-3bcfd057-c768-40da-b1e3-5ec4d5bb7a8f.png)

## Expected Behavior
should be able to use `:id`

## Steps to Reproduce

1. just create a simple route with `:id` as parameter in the url.
2. add something async like a db call.
3. view the trace in newrelic and you will see spans with lost parents

## Context
- using latest node.js newrelic agent
- using express.js version 4.x

**Comment by mrickard** [comment]
@itai-codefresh Thank you for the report! We're able to reproduce, and we'll keep you posted here.

**Comment by mrickard** [comment]
@itai-codefresh Which version of express are you using?

**Comment by itai-codefresh** [comment]
We are seeing this issue in multiple versions of express 4.x.
I didnt try it with express 5.

**Comment by itai-codefresh** [comment]
@mrickard is this something that could be fixed anytime soon?

**Comment by mrickard** [comment]
@itai-codefresh We're still investigating the cause. While it's easy to reproduce, the cause is rather subtle. Initially we were suspecting the async nature of the request, but it can also be reproduced without async/await, as long as `:id` is in the route. I should have more information in a day or two.

**Comment by mrickard** [comment]
@itai-codefresh Thank you for your patience!  We've identified the cause and are working on a fix. In the very short term, I'd recommend consulting the Transaction Trace detail interface on your application's APM page--that should show the traces as unfragmented.
