### ISSUE TITLE
Memory leak /code/node_modules/newrelic/lib/instrumentation/core/async-hooks.js

### ISSUE THREAD

**Issue by hamzahamidi** [newrelic/node-newrelic#1589]
## Description

We have a nodejs worker. we noticed there was a memory leak.
I noticed we repeatedly use `/code/node_modules/newrelic/lib/instrumentation/core/async-hooks.js` check the picture below 
<img width="1246" alt="memory leak showing repeated entry /code/node_modules/newrelic/lib/instrumentation/core/async-hooks.js" src="https://user-images.githubusercontent.com/22576950/231228449-12205299-440a-49d6-89ab-76525305c223.png">

## Your Environment

* ex: Node version: v18.12.1
* ex: Operating System and version: node:18.12.1-buster-slim

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment]
Also @hamzahamidi it occurred to me i see segmentMap in the heapdump. Can you try turning on the [async context manager feature flag](https://github.com/newrelic/node-newrelic/blob/main/documentation/feature-flags.md#async_local_context) which leverages AsyncLocalStorage.  `config.feature_flag.async_local_context` = true.

**Comment by bizob2828** [comment]
@hamzahamidi I haven't heard from you, feel free to reopen if you can provide what I asked for above or go the support.newrelic.com route
