### ISSUE TITLE
Provide a programmatically way to configure the agent

### ISSUE THREAD

**Issue by GiovanniCardamone** [newrelic/node-newrelic#1636]
## Is your feature request related to a problem? Please describe.
it's annoying to have a plain file in my project just to configure the behaivour of your lib.

## Feature Description
would be nice to have a method (e.g. `newrelic.configureAgent({ ... })` to configure it in order to have the ability to configure it due to my needs

## Additional context
There is several environment in my app, and i have to configure the agent due to my needs. 
This way of configuring agent it's very annoying, because i have to configure it before i know which configuration i should use (or if i should not use it at all).

A programmatically way to confgure the Agent will resolve any issue i have

## Priority
[Blocker]

**Comment by jordigh** [comment]
Hi, @GiovanniCardamone thanks for voicing your concerns.

For a dynamic configuration as you require, you can forego the `newrelic.js` file entirely and instead use [environment variables](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#environment) such as `NEW_RELIC_APP_NAME` or `NEW_RELIC_ENABLE`. You can set these variables before you start the application instrumented by New Relic.

I am going to close this report. If you do not find environment variables sufficient for your needs, please reopen this.

**Comment by GiovanniCardamone** [comment]
Sorry i lost track of what happened on this issue :sweat_smile: 

i think most of the library in any context provide a way to setup it manually:

examples:
- (sentry) https://docs.sentry.io/platforms/node/
- (firebase) https://firebase.google.com/docs/web/setup?hl=it
- (aws sdk) https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/global-config-object.html
- and so on

your library also implement a method to stop the agent:
- https://docs.newrelic.com/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api/#shutdown

i don't undertand why it have to start it automatically witouth the capability of configure it.

**Comment by bizob2828** [comment]
@GiovanniCardamone I will let our PM evaluate the request but I just wanted to chime in regarding the libraries you linked that allow configuration.  The New Relic Node.js agent is an agent and its design patterns aren't the same as an SDK(the libraries you linked).  The agent design is intended to be somewhat invisible.  The agent does also offer an API, which you _could_ say is the New Relic SDK but you don't get the API until the agent is loaded.  

We do prefer folks to load/start via `-r` or with ESM via the `--loader flag.  In fact if you rely on the `--loader` flag to instrument ESM applications, you could not use something like `newrelic.configureAgent`.  The shutdown method on the API was built for environments where you can't control the application under instrumentation shutting down and needing to flush the agent data before shutting down the process.

We offer 3 different ways to [configure the agent](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/): configuration file, environment variables, and server side configuration.  As @jordigh mentioned above, the newrelic.js file is a module so it allows for dynamic evaluation and could serve your needs.

**Comment by GiovanniCardamone** [comment]
Hi @bizob2828 thanks for your reply!

I see your point about polyfilling / monkey patching the app and why you need to load using require at the start or using node loaders.

The part i don't get is the "client configuration" of the agent (so if it have to send reports or not to sentry).

instrumentation and capturing/monitoring can happens even without this part. If somehow i need to `await` before i can provide you `app_name` or `license_key` there is no way i can use this library.

**Comment by bizob2828** [comment]
> 

@GiovanniCardamone we've typically had customers do the following when needing to make async calls before filling out configuration...

```js
const results = await doSomeAsyncWork()
process.env.NEW_RELIC_APP_NAME = results.appName
process.env.NEW_RELIC_LICENSE_KEY = results.licenseKey
require('newrelic')
```

This is purely suggesting a workaround. But it sounded like if we had a way to dynamically evaluate your newrelic.js configuration it would also solve this correct?  I'm trying to propose alternatives because we're dealing with design decisions of a 10 year old code base and it would be a heavy lift to expose an API endpoint that is used to handle pre bootstrapping of the agent.

**Comment by GiovanniCardamone** [comment]
this do not work if my project does not support top level await

**Comment by GiovanniCardamone** [comment]
my suggestion is this one:

by default do not change the way it behave.

when there is an environment variable like `NEWRELIC_MANUAL_BOOTSTRAP = true` then the agent instead of send the reports just ignore it.

when `newrelic.configureAgent({ app_name, license_key })` is invoked then it starts work normally

**Comment by ygerass** [comment]
PM Org cannot prioritize this feature at the moment. Closing now, since a workaround is listed above.
