### ISSUE TITLE
Duplicate middleware name ‘NewRelicHeader’

### ISSUE THREAD

**Issue by jodem** [newrelic/node-newrelic#1658]
## Description
We have typescript application using aws sdk 3.338.0
When enabling newrelic agent with version 10.1.2 we have the following error when trying to use aws s3 library :

Error: Duplicate middleware name 'NewRelicHeader'
at Object.add (/app/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:130:31)
at Object.applyToStack (/app/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:45:19)
...

Looks like aws-sdk is in version 5.0.2, when I check the repo there is now a version 5.0.5 that looks to address the problem, I override the sub dependency to 5.0.5 but I still have the issue.

Eventyally, I had to disable the newrelic agent to have my application to work.

Please fix asap since it prevent us to use the service we pay for.

**Comment by jmartin4563** [comment]
Hi @jodem, sorry about the troubles you're having. I'm investigating this on my end, but any code snippets / steps to reproduce that you can provide would be very helpful in aiding my investigation.

**Comment by jodem** [comment]
Just and improvement idea :  next time you fix a breaking change in a sub dependency, it's good to bump the main newrelic package version with fixed dependency. By doing so, a npm install would fetch the new version of 2 libraries automatically (because here since newrelic lib version did not change there we no auto update).
