### ISSUE TITLE
No SocketIO Prisma database queries being captured

### ISSUE THREAD

**Issue by KevinBusch** [newrelic/node-newrelic#1666]
No SocketIO Prisma database queries being captured

[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

We are using the most update-to-date New Relic agent and it is capturing database queries now from Prisma (THANK YOU!) but only for queries executed from code within our HTTP endpoints. Any queries executed from code sourced from our persistent web socket connections do not appear to be tracked. NOTE: We are running on top of FeathersJS / Prisma.  Why?

See original request here for more information.
https://forum.newrelic.com/s/hubtopic/aAX8W0000008f99WAA/new-relic-nodejs-agent-now-instruments-prisma?t=1686310540023

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

All Prisma database queries should be captured from Prisma regardless of where they're sourced from (HTTP endpoint or web socket connection)

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

Nothing to output (since NR isn't capturing anything 😉 )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

Install FeathersJS / Prisma alongside NR agent and set up two connections (HTTPS endpoint vs Socket IO connection).  Execute a query in both.  Socket IO connection queries don't get captured.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

```
    "@feathersjs/authentication": "^4.5.14",
    "@feathersjs/authentication-client": "^4.5.14",
    "@feathersjs/authentication-local": "^4.5.14",
    "@feathersjs/configuration": "^4.5.14",
    "@feathersjs/errors": "^4.5.14",
    "@feathersjs/express": "^4.5.14",
    "@feathersjs/feathers": "^4.5.14",
    "@feathersjs/rest-client": "^4.5.14",
    "@feathersjs/socketio": "^4.5.14",
    "@feathersjs/socketio-client": "^4.5.14",
    "@feathersjs/transport-commons": "^4.5.14",
    "feathers-prisma": "^0.3.2",
    "prisma": "^4.7.1",
    "@prisma/client": "^4.7.1",
```

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

Can't think of anything

**Comment by jmartin4563** [comment]
Hi @KevinBusch, we currently don't support SocketIO instrumentation, so I'll be moving this ticket to a feature request to get prioritized.
