### ISSUE TITLE
Node 20 is logging warnings

### ISSUE THREAD

**Issue by kibertoad** [newrelic/node-newrelic#1712]
## Description

When trying to run New Relic 10.4.0 with Node.js 20.3.1, following error is displayed:

`"New Relic for Node.js 10.4.0 has not been tested on Node.js v20.3.1. Please update the agent or downgrade your version of Node.js"`

Additionally, native metrics plugin fails to install, and the following is seen:

`"Not adding native metric sampler.","component":"sampler","error":{"message":"Cannot find module '/home/node/app/node_modules/@newrelic/native-metrics/build/Release/_newrelic_native_metrics-9_0_1-native_metrics-115-linux-x64.node'`

## Expected Behavior

There are no errors or warnings, and everything works as expected.

## Steps to Reproduce

Try to use Node.js agent with Node.js 20.3.1

## Your Environment

Node.js 20.3.1
Debian bullseye-slim

**Comment by bizob2828** [comment]
@kibertoad that's correct. We don't officially support Node 20 yet. You will see official support sometime soon-ish. I'm going to close this as known issue
