### ISSUE TITLE
Prisma@5 dropped support for Node 14

### ISSUE THREAD

**Issue by jmartin4563** [newrelic/node-newrelic#1715]
## Description

prisma just released version 5 today and dropped support for Node 14. This causes our versioned tests to fail as installing prisma@5.0.0 using Node 14 fails. We need to update our versioned tests to only run versions >=5.0.0 in Node 16 and 18.

## Expected Behavior

Versioned tests pass when testing prisma@5.0.0

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
Run the versioned tests, observe that prisma@5.0.0 causes failures
https://github.com/newrelic/node-newrelic/actions/runs/5523219029/jobs/10073844277#step:6:30990

## Your Environment
N/A

## Additional context
https://github.com/prisma/prisma/releases/tag/5.0.0

**Comment by bizob2828** [comment]
We dropped support for Node 14 in v11, I'm closing this as it's out of scope now
