### ISSUE TITLE
Fix @grpc/proto-loader vulnerability

### ISSUE THREAD

**Issue by getellez** [newrelic/node-newrelic#1716]
![image](https://github.com/newrelic/node-newrelic/assets/85968117/d37d5617-fda0-4a47-9cea-345658c8a9c0)

Hey NewRelic team! Could you please make an update to use the latest version of `@grpc/proto-loader`? So that we can fix a vulnerability

**Comment by bizob2828** [comment]
@getellez this should be fixed in 10.4.1
