### ISSUE TITLE
semver this package uses has a recent disclose of vulnerabilities 

### ISSUE THREAD

**Issue by johnforte** [newrelic/node-newrelic#1728]
https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795

Multiple parts of the codebase are using this vulnerable version of Semver.

**Comment by jmartin4563** [comment]
hi @johnforte, we updated semver in https://github.com/newrelic/node-newrelic/releases/tag/v10.3.1, are you using that version or higher?

**Comment by johnforte** [comment]
Hi @jmartin4563, Yes I am using 10.4.2

A quick look into your package-lock reveals semver vulnerable version is still in it; you probably have to update other packages that are using it. 

https://github.com/newrelic/node-newrelic/blob/main/package-lock.json

**Comment by jmartin4563** [comment]
Our Snyk scanning isn't reporting anything for our `dependencies` deps, are you referring to things that are `devDependencies`? Could you provide an example of what packages you're concerned about, as many of the package-lock entries are for our dev dependencies, which do not ship with this agent.
