### ISSUE TITLE
How to publish multiple source map files?

### ISSUE THREAD

**Issue by ivetrivel** [newrelic/node-newrelic#1742]
## Description
I have a giant code baes of source files whose map files are pushed into dist/static folder, but the API usage of uploadsource maps define me to provide path of the source files

**Comment by mrickard** [comment]
@ivetrivel Is this a browser app or a server-side Node.js application? If it's Node, you don't have to upload source maps. Instead, you can start your application with the `--enable-source-maps` flag, [as seen in our docs](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/enable-source-maps/).

**Comment by ivetrivel** [comment]
@mrickard this is for the browser side javascript. I looked at a doc and recommendation and sample usage were for single file and single source map, where as, the codebase has multiple files, adding individual file path is not trivial.

Is there an option of pushing a folder?
