### ISSUE TITLE
Support for Custom Output Locations in Prisma Schemas for Monorepo Setups

### ISSUE THREAD

**Issue by gustavolzangelo** [newrelic/node-newrelic#1779]
## Is your feature request related to a problem? Please describe.
I'm encountering an issue when using NewRelic's Node agent in a monorepo setup. The agent currently supports Prisma, but only when the schema is generated to its default output location. If I specify a custom output folder for my Prisma schema, the NewRelic agent fails to integrate correctly. This becomes a bottleneck when managing multiple Prisma clients/schemas in a monorepo setup, like this one: https://github.com/nrwl/nx-recipes/tree/main/nestjs-prisma#nx--nestjs--prisma

## Feature Description
I would like NewRelic's Node agent to support custom output locations for Prisma schemas. This feature will provide flexibility for those of us using monorepos, where multiple Prisma schemas might exist, each with its own custom output location.

## Describe Alternatives
If it makes it easier, maybe support for clients inside @prisma/client/ folder, as for now it looks to support only import/require with @prisma/client

## Additional context
Found this thread with a response about the possibility of opening a feature request for this support:
https://forum.newrelic.com/s/hubtopic/aAX8W0000008f99WAA/new-relic-nodejs-agent-now-instruments-prisma

"No the Node agent by design is expecting all modules it instruments to live in "node_modules", it can't register the instrumentation in any other location. The agent is specifically looking for import/require with '@prisma/client', which maps to the node_modules install location. We could file a feature request for this if you'd like."

## Priority
Really want

**Comment by bizob2828** [comment]
@gustavolzangelo thanks for filing the feature request.  Until this can be considered, please follow the suggestion to use the [instrumentLoadedModule](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api/#instrumentLoadedModule).

**Comment by lechinoix** [comment]
Hey @bizob2828 ! Thank you to point this function in the documentation, for anyone interested by an example usage :

```
import newrelic from 'newrelic';
import * as FirstClient from '@generated/first-client';
import * as SecondClient from '@generated/second-client';

newrelic.instrumentLoadedModule('@prisma/client', FirstClient);
newrelic.instrumentLoadedModule('@prisma/client', SecondClient);
```

Works like a charm ♥️

**Comment by bizob2828** [comment]
I'm closing this feature request as our current instrumentation core cannot support located a package from a custom location.  The workaround of using `newrelic.instrumentLoadedModule` should be the recommended way to achieve this.

**Comment by antmarot** [comment]
@bizob2828 What would be the recommended way to achieve this for ESM since `instrumentLoadedModule` isn't supported?
Note that with Prisma v7, the custom output location will become the default behavior (see [here](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/generating-prisma-client))
