### ISSUE TITLE
Webview login -- Error in Navigation in IOS

### ISSUE THREAD

**Issue by somesingh95** [newrelic/node-newrelic#1781]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]:'Error in Navigation!', [Error: Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'? See
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # 'Error in Navigation!', [Error: Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'? See
[TIP]:  # ( Link a sample application that demonstrates the issue. )
    "react-native": "0.69.3",
    "newrelic-react-native-agent": "^1.2.1",

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment]
@somesingh95 this appears to be an issue with the [react native agent](https://github.com/newrelic/newrelic-react-native-agent).  I do not have permissions to that project, otherwise I'd transfer it.

**Comment by somesingh95** [comment]
@bizob2828  i had already raised  it to newrelic-react-native-agent but they said its a newrelic IOS issue.

**Comment by bizob2828** [comment]
@somesingh95 I don't see an issue on that repo from you.  Either way this repo is for the Node.js agent and unfortunately we do not maintain nor can fix your issue.  It appears the IOS agent is not accessibly publicly via GitHub just yet.  You may need to go the route of https://support.newrelic.com. I have a question out internally so I will keep you posted

**Comment by ndesai-newrelic** [comment]
@bizob2828 you can close this one.
