### ISSUE TITLE
Prisma 5 support?

### ISSUE THREAD

**Issue by rgmvisser** [newrelic/node-newrelic#1801]
## Description

I just upgraded to Prisma 5 and I don't see any DB transactions anymore

## Expected Behavior

DB transactions automatically being captured by new relice

## Steps to Reproduce

1. Upgrade to Prisma 5.4.1
2. Run DB queries
3. No results in new relice

## Your Environment

- Prisma 5.4.1
- Node 16
- New Relic 11.1.0

## Additional context

The database transactions were previously showing up fine in New Relic, also my Redis transactions are still too.

**Comment by rgmvisser** [comment]
Hmm while building a small repro repo I indeed see it is working, must be on my end then somehow. 

Will report back if I have found the issue. Thanks anyway!

**Comment by bizob2828** [comment]
I will close this for now.  If you can provide a reproduction case, please reopen.
