### ISSUE TITLE
mongodb 5.0 + support

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#1911]
## Is your feature request related to a problem? Please describe.
The release of [mongodb 5.0](https://github.com/mongodb/node-mongodb-native/blob/HEAD/etc/notes/CHANGES_5.0.0.md#changes-in-the-mongodb-nodejs-driver-v5) had significant changes that impacted our instrumentation.  

## Details
In this [PR](https://github.com/newrelic/node-newrelic/commit/bcad694838bea79aa1d4bec23a4707b4c4efaf79) we stopped testing on versions >=5.0.0.  Analysis during that time was:

 * Removal of callback support will require a whole new versioned test suite
 * Removal of callback support also affects instrumentation, which is a bigger lift that should be prioritized
 * New package `mongodb-legacy` still has the callback api support, need to determine if we should support this package

**Comment by jsumners-nr** [comment]
https://github.com/newrelic/node-newrelic/issues/1122 may also be able to be resolved at the same time as this one.

**Comment by bizob2828** [comment]
Duplicate #1491
