### ISSUE TITLE
NewRelic issue with Axios 1.6.0

### ISSUE THREAD

**Issue by mfc-ablazal** [newrelic/node-newrelic#1928]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

There is a bug with Axios 1.6.0, needs to update it with 1.6.3.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jsumners-nr** [comment]
Thank you for the report. Can you please provide some more detail? A [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) would be most helpful.

**Comment by mfc-ablazal** [comment]
> Thank you for the report. Can you please provide some more detail? A [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) would be most helpful.

https://security.snyk.io/vuln/SNYK-JS-AXIOS-6124857

pls update i have added code change with PR: https://github.com/newrelic/csec-node-agent/pull/149

need to update this package

**Comment by jsumners-nr** [comment]
According to `npm ls axios` the dependency comes from `@newrelic/security-agent`. That package has updated the dependency in https://github.com/newrelic/csec-node-agent/pull/150 and will be available when a new version of that package is published. At such time, re-installing the dependencies in any project that utilizes `newrelic` will result in acquiring the updated library.

Note: if an application does not have the security agent enabled (by following [these instructions](https://github.com/newrelic/csec-node-agent#installation)) then there is not any cause for concern. Personally, I do not think there is cause for concern regardless after a cursory examination of how the affected library is used.
