### ISSUE TITLE
node js newrelic agent: Logs missing

### ISSUE THREAD

**Issue by sahilmahajanpikup** [newrelic/node-newrelic#1934]
## Description
We are using node js relic agent to forward logs to relic server. We found case in which logs of particular api is missing.
- Request hit our server and failed due to error occur in api. 
- New relic capture that request error in error inbox but logs associate with that request is missing. 
- This is not happening for all request not sure what is happening.

## Expected Behavior
Log should be appear in Log table till error occurred
## Your Environment
* app_name : PRODUCTION
* traceId: 6a5968df67b41fb57c06d2a1511f7d89 (from error inbox)

[TIP]:  # ( Include as many relevant details about your environment as possible. )
* EXPRESS: 4.18.2
* apollo-server: 4.7.1
* graphql: 16.6.0
* Node version: 16.0.0
* version: 11.5.0

**Comment by bizob2828** [comment]
@sahilmahajanpikup for issues like this, I recommend leveraging our support team over at [support.newrelic.com](https://support.newrelic.com/s/) which can help deep-dive into solving the problem. They will also ask to collect the necessary information which may or may not be sensitive (such as logs). I'm going to close this issue. You can reopen if you can provide a minimal reproduction case though.
