### ISSUE TITLE
Bump import-in-the-middle dependency to ^1.7.3

### ISSUE THREAD

**Issue by barryhagan** [newrelic/node-newrelic#1953]
## Description

There have been several issues with `import-in-the-middle` affecting the ability to use v11 of node-newrelic in ESM projects.  Those issues are resolved as of v1.7.3.

Please bump your dependency from `^1.6.0` to `^1.7.3` [here](https://github.com/newrelic/node-newrelic/blob/main/package.json#L203).

## Expected Behavior

When a dependency is updated to fix issues affecting this package, the dependency's minimum version is changed to get those fixes automatically.

## Steps to Reproduce

- Have an ESM project that uses a package lockfile.
- Install newrelic v10.6.2 to instrument the project.
- Already have version 1.7.1 of`import-in-the-middle` in the lockfile from another existing dependency (e.g. @opentelemetry/instrumentation).
- Update to newrelic v11.9.0
- newrelic only demands ^1.6.0, so the dependency is met by the existing 1.7.1 version in the lockfile added for @opentelemetry/instrumentation.

**Comment by bizob2828** [comment]
@barryhagan we don't bundle our dependencies. You can just do a fresh install of the agent version and it'll install the latest import-in-the-middle because of our semver range.

**Comment by barryhagan** [comment]
You continue to say this, but I don't think you understand how lockfiles and semver work together. 

If I already have version 1.7.1 in my lockfile (in my case because of opentelemetry already depending on iitm), then "a fresh install of the agent version" does nothing until _newrelic_ demands something higher than 1.7.1.  You are only asking for at least 1.6.0, which I already have satisfied with the existing install of 1.7.1.

There are plenty of ways to force the installation of 1.7.3, but none of those are necessary if you properly update the semver to demand at least 1.7.3 to avoid the known bugs in versions 1.6.0 through 1.7.2 that directly affect newrelic.

I have already jumped through those hoops to get my project working with 1.7.3.  I was hoping to help others avoid this problem by having newrelic maintain their package.  I guess that is a bridge too far.

**Comment by jsumners-nr** [comment]
Please see `npm help update` and `npm update --save`.

**Comment by barryhagan** [comment]
If 1.7.3 fixed a security vulnerability, would you bump it then??

**Comment by bizob2828** [comment]
@barryhagan we will be updating our minimum of `import-in-the-middle` eventually. However we aren't confident that all the issues have been resolved.  Also we don't have any plans to backport it into the 10.x line of our agent.

**Comment by jsumners-nr** [comment]
Please recognize that we are utilizing [semver ranges](https://docs.npmjs.com/cli/v6/using-npm/semver#ranges) to indicate the minimum supported versions of the dependencies we require. Do so allows users of the library to keep transitive dependencies updated without requiring a new release of `newrelic`. If we issued a new release of `newrelic` every time one of our dependencies updated, we'd be causing maintenance churn for our users.

**Comment by barryhagan** [comment]
Thanks for that info on your maintenance/support philosophy.

I'd expect this change to be part of a 11.10.0 release, not cause it.  I just haven't seen past releases incorporate updates to this dependency when known bugs were fixed.  I can understand the risk that requiring the higher version may have its own regressions.
