### ISSUE TITLE
(langchain) Add LLM attribute to all transactions that contain LLM spans

### ISSUE THREAD

**Issue by jsumners-nr** [newrelic/node-newrelic#1971]
When recording transactions that contain LLM spans we need to add the `llm: true` attribute to the transaction, e.g.:

```js
const { DESTINATIONS } = require('lib/config/attribute-filter')
segment.transaction.trace.attributes.addAttribute(DESTINATIONS.TRANS_EVENT, 'llm', true)
```

Reference: https://github.com/newrelic/node-newrelic/pull/1946

**Comment by bizob2828** [comment]
this is being done in the various instrument x
