### ISSUE TITLE
(langchain) Store collected request and message identifiers on transaction

### ISSUE THREAD

**Issue by jsumners-nr** [newrelic/node-newrelic#1972]
To support recording response quality feedback the identifiers for requests and responses must be stored on the transaction.

Example in the OpenAI instrumentation: https://github.com/newrelic/node-newrelic/blob/52bf9f362884f481a6dcc955be4fb1267458def8/lib/instrumentation/openai.js#L138-L147

**Comment by jsumners-nr** [comment]
Hold off until @bizob2828 reports back.

**Comment by bizob2828** [comment]
We're going towards feedback at trace level so we will not have to store any ids in some context
