### ISSUE TITLE
(langchain) Instrument embeddings

### ISSUE THREAD

**Issue by jsumners-nr** [newrelic/node-newrelic#1977]
Embeddings in LangChain basically look like:

```js
'use strict'

// https://js.langchain.com/docs/modules/data_connection/text_embedding/

require('dotenv').config()
const newrelic = require('newrelic')
const { OpenAIEmbeddings } = require('@langchain/openai')

main().then(() => {}).catch(error => {
  console.error(error)
})

async function main () {
  newrelic.startBackgroundTransaction('openai-tx', async () => {
    const model = new OpenAIEmbeddings()
    const res = await model.embedQuery('hello world')

    console.log(res)

    newrelic.shutdown({ collectPendingData: true }, () => {})
  })
}

```

See the following docs for more details on embeddings:

+ https://js.langchain.com/docs/modules/data_connection/text_embedding/
+ https://js.langchain.com/docs/integrations/text_embedding

LangChain embedding clients ultimately invoke [`Embeddings.prototype.caller`](https://github.com/langchain-ai/langchainjs/blob/7e16af24dd4ee28e8536e30e9db7ffab0e26a69b/langchain-core/src/embeddings.ts#L37-L41) (e.g. [OpenAI implementation](https://github.com/langchain-ai/langchainjs/blob/7e16af24dd4ee28e8536e30e9db7ffab0e26a69b/libs/langchain-openai/src/embeddings.ts#L258-L269) and [Bedrock implementation](https://github.com/langchain-ai/langchainjs/blob/7e16af24dd4ee28e8536e30e9db7ffab0e26a69b/libs/langchain-community/src/embeddings/bedrock.ts#L125-L131)). Therefore, we should instrument the base class's `caller` method to instrument embeddings as we do for baseline OpenAI:

https://github.com/newrelic/node-newrelic/blob/52bf9f362884f481a6dcc955be4fb1267458def8/lib/instrumentation/openai.js#L178-L185

**Comment by bizob2828** [comment]
I confirmed that there isn't anything in langchain we need to instrument. We will get embeddings through openai and bedrock(if we instrument the langchain implementation of it)
