### ISSUE TITLE
Get a specific custom attribute value on transaction

### ISSUE THREAD

**Issue by hame25** [newrelic/node-newrelic#2010]
## Is your feature request related to a problem? Please describe.
I need to be able to access or increment an existing custom attribute on the current transaction

## Feature Description
I would like to increment the value on an existing custom attribute. Either through a direct api method or by getting the current value and re-setting the attribute myself

E.g. I've previously set attribute x to 'abc' and next I would like to add ',xyz' to the attribute rather than replace it.

Something like either 
```javascript
newrelic.incrementAttribute('myAttribute', 'abc') // abc
newrelic.incrementAttribute('myAttribute', ',xyz') // abc,xyz
```
or
```javascript
newrelic.addCustomAttribute('myAttribute', 'abc');
const currentValue = newrelic.getAttribute('myAttribute') // abc
```
or something similar to the browser SPA API's getContext

https://docs.newrelic.com/docs/browser/new-relic-browser/browser-apis/getcontext/

## Describe Alternatives
Previously looked at accessing the current transaction through `newrelic.getTransaction()` but as there are no working api's available the only way i can access the custom attribute value is via object property access - which seems a little fragile.

## Additional context
Add any other context here.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have, Really Want, Must Have, Blocker] 
Must Have

**Comment by jsumners-nr** [comment]
Does [`newrelic.incrementMetric('name')`](https://newrelic.github.io/node-newrelic/API.html#incrementMetric) solve this issue?

**Comment by bizob2828** [comment]
@hame25 custom attributres are not immutable.  So you can just call `newrelic.addCustomAttribute(<key>,<value>)` as many times as you want throughout a transaction and it will update it accordingly.  You mention increment which is why @jsumners-nr also proposed using metrics to track you information.

**Comment by bizob2828** [comment]
@hame25 updating custom attributes can be done but you'd have to keep track of their previous values.  

So instead of 

```js
newrelic.incrementAttribute('myAttribute', 'abc') // abc
newrelic.incrementAttribute('myAttribute', ',xyz') // abc,xyz
```

it'd be

```js
newrelic.addCustomAttribute('myAttribute', 'abc') // abc
newrelic.addCustomAttribute('myAttribute', 'abc,xyz') // abc,xyz
```

The idea of incrementing exists in our agent but it is meant for metrics as @jsumners-nr suggested in the comment above.

**Comment by bizob2828** [comment]
@hame25 I see.  I will keep this feature request open an allow our PM to decide its priority amongst other work.  You can definitely get the data but reaching deep into the trace may not be recommended as it may change in the future.

**Comment by bizob2828** [comment]
@hame25 we spoke about this internally and are struggling to understand the exact use case you're trying to support.  We came to the conclusion that incrementing an attribute would not be reliable. The reason for this is custom attributes are attached to transactions and we harvest them on a cycle. There could be a chance if you try to increment it won't be there.  The one thought is that you could just defer creating the attribute when you know your done with all your logic.  That would just require your application to keep the context of the value and then when you're ready to finalize, just use our API to `addCustomAttribute`
