### ISSUE TITLE
Restore ability to instrument the same module but in different folder locations

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#2033]
## Is your feature request related to a problem? Please describe.
In #1563 we added the ability to instrument the same module more than once.  However there were some issues with that. We shifted where we flagged if a module was already instrumented from the export to the instrumentation hooks.  This surfaced a different issue where you could not instrument multiple version of the same module(#1799).  However, that still had an issue where you could have the same module and version installed in different locations.  The modern npm resolution typically flattens directories to where this is not possible but you could have a module installed in different roots. One could argue this is an anti-pattern but it still works.  We need to [restore this ability](https://github.com/newrelic/node-newrelic/pull/1563/files#diff-3d0c4388e915f657046d7040af798b9376a45f953db048c457fe98a148d22b10L559), which essentially should be storing the instrumentation flag back on the exported module. But instead of having a boolean flag we need to keep track of which instrumentation hooks were registered.

## Feature Description
Support instrumenting the same module and version in different folder locations.

**Comment by jsumners-nr** [comment]
@bizob2828 do I have this correct?

-----

For a given module, e.g. `pino`, that could be installed multiple times through direct and transitive dependencies, e.g.:

```
- node_modules
 |
  - pino@8.19.0
 |
  - foo
   |
    - node_modules
     |
      - pino@8.19.0
```

We want:

```js
// where module === pino
module[symbols.instrumented] = ['log', 'transport', 'destination']
```
