### ISSUE TITLE
[spike] mongodb v5/v6 support

### ISSUE THREAD

**Issue by kmudduluru** [newrelic/node-newrelic#2048]
## Description
This spike is to identify the scope of [mongodb v5 support](https://github.com/newrelic/node-newrelic/issues/1491). Original triage was done [here](https://new-relic.atlassian.net/browse/NR-135382) but since it is in jira and not visible to community this was the analysis:

Get the usage from Angler for MongoDB

## Findings

 * Removal of callback support will require a whole new versioned test suite

 * Removal of callback support also affects instrumentation, which is a bigger lift that should be prioritized

  * New package `mongodb-legacy` still has the callback api support, need to determine if we should support this package

## Open Questions
1. Do we need to support this mongodb-legacy (https://www.npmjs.com/package/mongodb-legacy?activeTab=versions) ?

**Comment by bizob2828** [comment]
> Do we need to support this mongodb-legacy (https://www.npmjs.com/package/mongodb-legacy?activeTab=versions) ?

We will not support `mongodb-legacy`.  We will be actively try to drop older versions of mongodb in our next major release

**Comment by bizob2828** [comment]
Research spike was not needed.  This effort was purely a test update which is captured in #2085
