### ISSUE TITLE
Provide ability to disable the capturing of content in Llm events

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#2054]
### Description
Due to compliance and other reasons, customers need the ability to disable capturing of content in Llm events.  We will be introducing a new configuration `ai_monitoring.record_content.enabled` defaulting to true but when false its hould not capture the content in any Llm message

### Acceptance Criteria
When `ai_monitoring.content.enabled` is false the following attributes should be omitted from events in openai, langchain:

| Event name               | Attribute name  |
| ------------------------ | --------------- |
| LlmChatCompletionMessage | content         |
| LlmEmbedding             | input           |
| LlmTool                  | input           |
| LlmTool                  | output          |
| LlmVectorSearch          | request.query   |
| LlmVectorSearchResult    | page_content   |

**Comment by jsumners-nr** [comment]
Resolved by #2058
