### ISSUE TITLE
Agent header collecting, high CPU utilization

### ISSUE THREAD

**Issue by halfmatthalfcat** [newrelic/node-newrelic#2066]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

During an incident we profiled our application pretty in-depth and while not the source of our issue, found that the NR node agent was taking quite a bit of time collecting headers:

```
30766  7.6%      /usr/local/bin/node
7052   22.9%        LazyCompile: *_headerToCamelCase /[redacted]/node_modules/newrelic/lib/header-attributes.js:86:28
7019   99.5%          LazyCompile: *_collectHeaders /[redacted]/node_modules/newrelic/lib/header-attributes.js:103:25
3780   53.9%            LazyCompile: *wrappedHandler /[redacted]/node_modules/newrelic/lib/instrumentation/core/http.js:36:57
1906   27.2%            LazyCompile: *instrumentedFinish /[redacted]/node_modules/newrelic/lib/instrumentation/core/http.js:156:28
1167   16.6%            LazyCompile: *collectRequestHeaders /[redacted]/node_modules/newrelic/lib/header-attributes.js:147:31
111    1.6%             Function: ^collectRequestHeaders /[redacted]/node_modules/newrelic/lib/header-attributes.js:147:31
```

~1.7% total CPU time for the above profile. Looking at the code paths above, things don't look too bad but just wanted to bring it to your attention. If there were any optimizations that could be made, that would be excellent.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

It's just somewhat of a smell that this is so high on the utilization profile. I would expect this type of functionality to not be super intensive but I may be wrong.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Agent version: 11.10.2
* ex: Node version: 18.19.0
* ex: Operating System and version: Debian GNU/Linux 11 (bullseye)

**Comment by jsumners-nr** [comment]
Thank you for bringing this to our attention. I'd like to do some further diagnosis. Can you provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)? Doing so will help us diagnose the issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.

You may use a GitHub repository to host the code if it is too much to fit into a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).
