### ISSUE TITLE
Duplicate middleware 'NewRelicHeader' when using DynamoDBClient and DynamoDBDocumentClient in the same project

### ISSUE THREAD

**Issue by KevinWiegand-Genesys** [newrelic/node-newrelic#2071]
## Description

When using both the DynamoDBClient and the DynamoDBDocumentClient in the same project, NewRelic throws an exception stating that there is a duplicate 'NewRelicHeader' middleware.

## Expected Behavior

Both clients should be able to be used in the same project.

## Steps to Reproduce
The following repository shows the issue and has instructions on reproducing: https://github.com/KevinWiegand-Genesys/duplicate-middleware

## Your Environment

NodeJs 18.16.0
AWS SDK Client Modules 3.525.0
NewRelic 11.12.0

**Comment by svetlanabrennan** [comment]
@KevinWiegand-Genesys Thanks for reporting this. We found what was causing this issue and are working on a fix for it now.

**Comment by svetlanabrennan** [comment]
Fixed in this pr: https://github.com/newrelic/node-newrelic-aws-sdk/pull/273

**Comment by svetlanabrennan** [comment]
Fixed in this pr: https://github.com/newrelic/node-newrelic-aws-sdk/pull/273
