### ISSUE TITLE
protobuf@7.2.6 causing install failure of newrelic

### ISSUE THREAD

**Issue by flpms** [newrelic/node-newrelic#2077]
Remote `npm install` executions from CI (github actions) with newrelic in the dependencies breaks the pipeline.

## Description

My infrastructure executes a remote `npm install` through ssh command from github actions with the following result
![image](https://github.com/newrelic/node-newrelic/assets/4911643/9e3b4556-55a7-4dd7-9450-a66d84786cc8)

run `npm install` direct from the server works as expected also after remove newrelic the pipeline executes without any issue.

The problem looks like to be a dependency from the `newrelic` package. **More details In the additional context**

## Expected Behavior

Run `npm install` without break pipeline as a regular `npm install` from the server

## Steps to Reproduce

1. using a project with newrelic as dependencies
2. run `ssh root@example.server 'export PATH=[path to your npm] && cd /path/to/node/project; npm install'`

## Your Environment

**New Relic Package Version**:  11.13.0
**NPM version**: 10.5.0
**Node version**: 20.11.1
**Operating System and version**: Ubuntu 22

## Additional context

The problem looks like be caused by protobujs post script install, [that affecting others projects. ](https://github.com/protobufjs/protobuf.js/issues/1975).

`Protobufjs@7.2.6` is a dependency from `proto-loader@0.7.10` as I see after runing `npm ls --all`
![image](https://github.com/newrelic/node-newrelic/assets/4911643/9afb87dd-6448-4116-bcfa-89ea5545c129)

Follow the log from `npm install` error in the error step
![image](https://github.com/newrelic/node-newrelic/assets/4911643/62ac7acc-a1d8-4d2f-9df9-6b9a6d2e1001)

As workaround I'm remove new relic from my project and looking for another monitoring service

**Comment by bizob2828** [comment]
@flpms I'm sorry to hear you're having an issue with the agent.  As you called out this is an issue with one of our dependencies.  You can apply a force to install `protobuf@7.2.5` until they fix it by doing this in your package.json:

```
  "overrides": {
    "@grpc/proto-loader": {
      "protobufjs": "7.2.5"
    }
  }
```

**Comment by bizob2828** [comment]
I'm going to close this issue as there isn't anything we can do unless we pin to a lower version which we will not be doing.  The workaround provided should suffice until protobufjs releases a fix

**Comment by flpms** [comment]
Thanks @bizob2828 for the suggestion, I tried overriding without a solutions, I'll try some else in the future as news versions was released.
