### ISSUE TITLE
require.cache changes in 9.6.0 causing error in loopback app

### ISSUE THREAD

**Issue by mrickard** [newrelic/node-newrelic#2111]
[This commit](https://github.com/newrelic/node-newrelic/pull/1389) changed how we handle require.cache. Previously we'd used non-enumerable properties with an *__NR* prefix, and this commit converted those to symbols. 

A customer [reported an issue](https://new-relic.atlassian.net/browse/NR-235132) upgrading from a much older agent to a recent one, and experienced consistent crashes above version 9.5.0. There's a repro case attached to the ticket, which needs to be run under Node 14. Changing the New Relic agent from 9.5.0 to 9.6.0--or even toggling over the above commit--will show that to be the change affecting the application.

**Comment by bizob2828** [comment]
This is related to loopback 3 which is out of support.  They had [logic in their code](https://github.com/strongloop/loopback/blob/v3.28.0/lib/server-app.js#L228) that checked if the New Relic agent had wrapped an express function.  When we moved from dunder props to symbols this broke.  I'm closing this as won't fix. If other cutomers report this, the solution is to either stay on 9.5.0 of agent or upgrade loopback to v4
