### ISSUE TITLE
Migrate `@newrelic/next` into repo

### ISSUE THREAD

**Issue by jsumners-nr** [newrelic/node-newrelic#2127]
See https://github.com/newrelic/node-newrelic/issues/2123.

Note: we should mark it as experimental in the release notes and as an on-going basis.

Tasks:
 * deprecate the `@newrelic/next` package
 * Update `lib/instrumentations.js` to register a relative folder
 * Remove the external versioned tests configuration.
 * update tests to use `test/lib/agent_helper` instead of `@newrelic/test-utilities`
 * Convert git history with the previous repo.
 * Archive old repo when done.

**Comment by bizob2828** [comment]
This is fine but I think we should wait to do this until we've deemed our instrumentation stable

**Comment by bizob2828** [comment]
If we do this, it's more than just migrating the next.js instrumentation into the repo.  We had a bunch of FAQs around Next.js nuance and would have to port those and the standalone to [externalize libraries](https://github.com/newrelic/newrelic-node-nextjs/blob/ea20b76a13c84f4f3c48e9544e18e568b8e41c33/load-externals.js)
