### ISSUE TITLE
spike: Add the agent_language v2 metadata header to serverless payload

### ISSUE THREAD

**Issue by mrickard** [newrelic/node-newrelic#2130]
### Description
Lambda functions instrumented with the Node agent emit instrumentation payloads defined with the v1 spec. Our internal metrics track usage patterns that depend on a v2-spec metadata header which the Node agent doesn't report. We want to see if adding the `agent_language` metadata header to a v1 payload is sufficient to show Node usage.
 
### Acceptance Criteria
This spike would add the `agent_language` metadata header to the serverless payload, and check if that's sufficient to show usage for Node independent of other v1 agents.

This test requires a change to the agent's serverless collector. This change can be local to the developer's machine, or submitted to a branch. We can then test with a custom layer incorporating that change, and apply that to a test Lambda function in AWS.

The test function can be invoked, and we check tdp.usage metrics for Node.

Additionally, the test function can add some custom metrics to check the pipeline handling of those.

**Comment by kmudduluru** [comment]
Also need to verify if custom metrics are working fine and displayed in NRDB.

**Comment by mrickard** [comment]
Confirmed that the addition of an `agent_language` metadata header is reflected in TDP usage. 

Custom metrics recorded with the agent are not appearing in the staging metric explorer.

**Comment by mrickard** [comment]
Reopening to track the addition of the header in the agent

**Comment by bizob2828** [comment]
[Spike](https://docs.google.com/document/d/1gMxdzF5WWIdENCi2bZ3LY3w64sEhSvTXNwRbDsGYifg/edit?usp=sharing)
