### ISSUE TITLE
New Relic doesn't include any trace level beyond a handler in a breakdown when using fastify

### ISSUE THREAD

**Issue by kibertoad** [newrelic/node-newrelic#2137]
## Description

There is no breakdown of any calls beyond the handler level. See screenshot for how it looks like for pretty much any request:

![image](https://github.com/newrelic/node-newrelic/assets/1847934/c9956f73-5cbe-4b51-b3dc-59faa1727566)

fastify lifecycle hooks? included
fastify prehandlers? included
fastify routes? included

but if you call a service from the route, and then a repository from the service, all of that gets reported under route umbrella, so it's very difficult to understand where the time was spent, exactly.

## Expected Behavior

It is possible to trace which specific domain service and/or repository calls took how much time within a trace.

## Steps to Reproduce

You can use https://github.com/lokalise/node-service-template, which includes the New Relic instrumentation, in order to reproduce the problem. Note that you should either remove `jwtTokenPlugin` from `app.ts` or add the endpoint that you would be testing with in its skiplist.

You can call any of the user routes for the reproduction: https://github.com/lokalise/node-service-template/blob/main/src/modules/users/routes/userRoutes.ts

## Your Environment

Debian Bookworm, Node 20.11.1

**Comment by kibertoad** [comment]
More like this:
```ts
class MyService() {

constructor(repository) {
  this.repository = repository
}

createUser() {
  this.repository.createUser()
}
}

async function handler(req, res) {
  await someStaticMethod1() // takes 1 second
  const myData = await myService.createUser() // takes 10 seconds
  await someStaticMethod2() // takes 1 second
  return res.send(myData)
}
```

In this scenario NewRelic will show up as `/Fastify/Route` took 12 seconds, which is not very helpful. What we really need to know is that `someStaticMethod1` took 1 second, and `myService.createUser()` took 10 seconds, which is currently obscured, as data is only aggregated on a route level.

I can try preparing a simple repo over the next week if that helps.

**Comment by bizob2828** [comment]
@kibertoad that service code is custom and not fastify related. You will have to use our API to record segments.

**Comment by kibertoad** [comment]
@bizob2828 That's odd. Instrumentation for other languages, such as Java or PHP is showing a deep drilldown across all the layers for custom code without any extra effort. What makes Node.js different in this case?

I don't think it's realistic to manually record segments for every single non-trivial call within the system, that kinda defeats the purpose of having the auto-instrumenting agent.

**Comment by jsumners-nr** [comment]
@kibertoad are your "service" and "repository" entities backed by one of our instrumented libraries, e.g. `pg`?

**Comment by bizob2828** [comment]
@kibertoad I'm not familiar with our other agents but looking at those span names they are prefixed with Custom. I would read that as your company has custom code to instrument those functions.  Our agent and our competitors instrument a finite set of [3rd party libraries](https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentations.js).   

> New Relic Node.js agent is incapable of instrumenting just plain JavaScript code, comparably to other languages?

I don't think you'd want an agent to instrument plain javascript, it would be a performance bottleneck and provide a very noisy trace.  What we do instead is provide our customers with an API to do instrumentation and recording of spans and metrics.  

Either way, I'm sorry you're not getting at much insight for free from the Node.js agent as PHP but I don't see any action from us at this time.  I'm going to close this bug.  If you can provide reproduction cases, we could probably recommend ways to instrument that is maintainable for your service(s), feel free to comment on it and we can take a look.

**Comment by kibertoad** [comment]
@bizob2828 Thank you for the clarification! I guess we'll try to investigate using custom segments then.

**Comment by jsumners-nr** [comment]
@kibertoad for what it's worth, here's a recent example of using our exported API to instrument a custom module https://github.com/newrelic/node-newrelic/blob/8013b25ef24575946d46c163d6b876dce9a02665/test/integration/shimmer/reinstrument.tap.js

**Comment by kibertoad** [comment]
@jsumners-nr thank you, that helps!

**Comment by bizob2828** [comment]
@kibertoad we also have an [examples repo](https://github.com/newrelic/newrelic-node-examples). The ones of interest may be [messaging app](https://github.com/newrelic/newrelic-node-examples/tree/main/messaging-app) or [webframework app](https://github.com/newrelic/newrelic-node-examples/tree/main/custom-instrument-apps/instrument-webframework)
