### ISSUE TITLE
Routes set up with `express-promise-router` are missing the base path.

### ISSUE THREAD

**Issue by eelco** [newrelic/node-newrelic#2138]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

We’re using `express-promise-router` to set up routes with a nested router like this…
```
import Router from "express-promise-router"
import { userRoutes } from "./userRoutes
// etc…

export const routes = Router()

routes.use("/users", userRoutes)
// etc…
```
And then in `userRoutes.ts` the code looks similar:

```
import Router from "express-promise-router"

export const userRoutes = Router()

userRoutes.get("/:userId", /* handlers */)
// etc…
```

This works well, but confuses New Relic. The path as specified in the outer router (`/users`) is dropped when transactions are logged, so it will only show `/:userId`. We use a lot of sub-routers, with overlapping paths.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

Transactions use the full path: `/users/:userId`.

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

This looks like it’s a long standing issue: https://github.com/newrelic/node-newrelic/issues/163

If this is fixable by writing custom instrumentation, I’d love to learn how exactly as it’s not clear to me from the documentation.

**Comment by bizob2828** [comment]
This is because our instrumentation does not instrument `express-promise-router`.  It looks like this is small wrapper around express Router but I think this [line](https://github.com/express-promise-router/express-promise-router/blob/trunk/lib/express-promise-router.js#L62) is why you don't see the `/users` substring in the transaction name.  I'm trying to provide you sample instrumentation but its turning out to be very difficult.

**Comment by eelco** [comment]
It’s never actually “simple”, right?

I was responding to your earlier comment, and you posted the answer in the meantime, thank you so much for this!

(Aside: it seems that 2024 might be the year of Express 5.0 (after 10 years 🤞) with router 2.0 that supports promises. Is Express 5.0 beta / RC support in the cards?)

**Comment by bizob2828** [comment]
Yea when you get into complex use cases, unfortunately our instrumentation APIs are a steep learning curve.  Here's a good [example app](https://github.com/newrelic/newrelic-node-examples/tree/main/custom-instrument-apps/instrument-webframework) that uses our webframework shim to instrument a custom webframework

**Comment by bizob2828** [comment]
I imagine express 5 will be on our roadmap when that time comes. I'm not holding my breath though as you alluded to this is a long time coming
