### ISSUE TITLE
Provide an API to ignore calculating apdex on the active transaction

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#2142]
### Description
A few language agents: java, .net, and ruby have the ability to omit collecting apdex metrics for an active transaction.

### Acceptance Criteria
As a user I want the ability to ignore collecting apdex metrics for the active transaction.

### Design Consideration/Limitations
add a ignoreApex property to transaction and when [_setApdex](https://github.com/newrelic/node-newrelic/blob/main/lib/transaction/index.js#L722) is called and `ignoreApex` is true, it should log warning and exit early.

`api.ignoreApdex` - it will create a supportability metric when created, it will try to get the active transaction and if there is one it'll set the ignoreApdex property on transaction

### Additional context
 * [Ruby agent implementation](https://rubydoc.info/github/newrelic/newrelic-ruby-agent/NewRelic%2FAgent%2FInstrumentation%2FControllerInstrumentation%2FClassMethods:newrelic_ignore_apdex)
 * [Java agent](https://github.com/newrelic/newrelic-java-agent/blob/8e37e4450e7abef17ae6bdec1f09253029b861b4/newrelic-agent/src/main/java/com/newrelic/agent/dispatchers/DefaultDispatcher.java#L29-L31)
 * [.Net agent](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs#L478)

**Comment by slider** [comment]
I'd like to +1 on this, we have a use case with long running calls that are polling an external API and as a result out Appdex value gets skewed by this.
