### ISSUE TITLE
Newrelic + Fastify: Function.prototype.apply was called on #<Object>, which is an object and not a function

### ISSUE THREAD

**Issue by gevalo1** [newrelic/node-newrelic#2155]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

We're converting our project from CJS to ESM, and are encountering some issues with Newrelic & its Fastify instrumentation.
Not sure if relevant, but we also integrate @apollo/server with fastify using https://www.npmjs.com/package/@as-integrations/fastify.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

```
{
  "error.message": "Function.prototype.apply was called on #<Object>, which is an object and not a function",
  "error.stack": "TypeError: Function.prototype.apply was called on #<Object>, which is an object and not a function\n    at wrappedFastifyModule (/.../node_modules/.pnpm/newrelic@11.15.0/node_modules/newrelic/lib/instrumentation/fastify.js:99:37)\n    at createFastifyInstance (file:///.../dist/src/utils/fastify/fastify.js:27:17)\n    at start (file:///.../dist/src/server.js:45:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
}
```

The above error is the main error message, but we're also seeing the following message since we migrated to ESM.

```
{
  "message": "New Relic for Node.js in worker_threads is not officially supported. Not starting! To bypass this, set `config.worker_threads.enabled` to true in configuration.",
}
```
How can it be that we didn't get this message before?

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

We encountered this when migrating our project from CJS to ESM. Everything worked fine before.

```
node --experimental-loader newrelic/esm-loader.mjs -r newrelic ./index.js
```

If/when I'm able to create a reproduction I can share, I will link it here.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Node version: `20.11.1`
Docker Image: `node:20.11.1-alpine`
Newrelic `11.15.0` (same error on `11.14.0`)
Fastify: `4.26.2`
@fastify/cors: `9.0.1`
@fastify/helmet: `11.1.1`
@fastify/type-provider-typebox: `4.0.0`
@apollo/server: `4.10.2`
@as-integrations/fastify: `2.1.1`
@newrelic/apollo-server-plugin: `5.1.0`

**newrelic.cjs**
```
module.exports.config = {
  agent_enabled: process.env.NEW_RELIC_LICENSE_KEY !== undefined,
  app_name: process.env.NEW_RELIC_APP_NAME,
  application_logging: {
    forwarding: {
      enabled: false,
    },
    local_decorating: {
      enabled: true
    },
  },
  distributed_tracing: {
    enabled: true,
  },
  ignore_server_configuration: true,
  labels: process.env.NEW_RELIC_LABELS,
  license_key: process.env.NEW_RELIC_LICENSE_KEY,
  logging: {
    level: 'warning',
    filepath: 'stdout',
  },
  slow_sql: {
    enabled: true,
  },
  transaction_tracer: {
    enabled: true,
    record_sql: 'obfuscated',
  },
};
```

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by mrickard** [comment]
We're sorry to hear you're having trouble. A reproduction case would help us pin down what you're seeing, since there are a few moving parts (CJS-to-ESM, Fastify, Apollo).

**Comment by gevalo1** [comment]
Hi @mrickard,

Here is a reproduction case for both error messages: https://github.com/gevalo1/node-newrelic-issue-2155.

Using fastify at all seems to cause the main error: `TypeError: Function.prototype.apply was called on #<Object>, which is an object and not a function`.

While the logging configuration in `newrelic.cjs` seems to cause the `New Relic for Node.js in worker_threads is not officially supported. Not starting! To bypass this, set `config.worker_threads.enabled` to true in configuration.` error.

**Comment by gevalo1** [comment]
I also added a GitHub Action in that repository to show both errors: https://github.com/gevalo1/node-newrelic-issue-2155/actions.

**Comment by jsumners-nr** [comment]
You stated that you are seeing this problem with ESM. The provided example seems to be TypeScript. Where is the ESM reproduction?

**Comment by gevalo1** [comment]
I'm not sure if it's an ESM specific problem or not, but we started seeing it when we migrated to ESM.

The example I provided is indeed TypeScript, but it's also ESM. Either way I simplified the example even more by removing TypeScript entirely: https://github.com/gevalo1/node-newrelic-issue-2155.

I've kept the TypeScript code under the `typescript` branch as well.

**Comment by gevalo1** [comment]
Hi @jsumners-nr & @bizob2828,

I just want to follow-up quickly regarding the reproduction, was the message
```
New Relic for Node.js in worker_threads is not officially supported. Not starting! To bypass this, set `config.worker_threads.enabled` to true in configuration.
```
expected there?

**Comment by bizob2828** [comment]
This application must spawn worker threads. We do not properly function in worker threads because we do not propagate asynchronous context. In fact we don't want to make the decision of propagating context as executing in worker threads is heavily dependent on your application logic. You can opt in to loading the agent in worker threads but keep in mind that mileage may vary.

**Comment by gevalo1** [comment]
The replication doesn't do anything with worker threads though? Unless either New Relic or Fastify does something with them by default?

**Comment by gevalo1** [comment]
Hi,

I've tried the latest version (11.16.0), and we are still getting the following warning:
```
New Relic for Node.js in worker_threads is not officially supported. Not starting! To bypass this, set `config.worker_threads.enabled` to true in configuration.
```

The replication above also throws this warning but doesn't use any worker threads. Can I safely ignore this warning and will the agent still work as expected?

**Comment by mrickard** [comment]
@gevalo1 If you take a look at the [code path that logs this message](https://github.com/newrelic/node-newrelic/blob/main/index.js#L95-L103), you'll see that it's logged when the agent isn't running on the main thread. As New Relic doesn't support instrumentation for applications not running on the main thread, the agent won't start. 

If you ignore the message, the agent won't provide instrumentation. If you override, there's no guarantee of the agent working in the same way that it works with main-thread instrumentation.

**Comment by gevalo1** [comment]
Hi @mrickard, I understand that the agent doesn't support worker threads.

However my question is: What is causing there to be any worker threads at all?
To demonstrate what I mean I simplified the above replication to only show this warning: https://github.com/gevalo1/node-newrelic-issue-2155/tree/worker-threads.
And you can see the output and resulting warning of running this code here: https://github.com/gevalo1/node-newrelic-issue-2155/actions/runs/9001197998/job/24726926905#step:5:18

What in my reproduction is causing this warning to be thrown? There is practically no code there and still the agent doesn't want to start?
(Ignoring the fact that I didn't push a license key in that repository of course)
What should I change in that replication to make the agent able to start?

**Comment by jsumners-nr** [comment]
Given the code provided below (the referenced replication), I can run the application like so:

```sh
$ node -r newrelic index.js
```

And get 0 lines referencing threads:

```sh
$ cat newrelic_agent.log | jq -rc 'pick(.component,.module,.msg)' | rg thread
# no results
```

Do you have the `NEW_RELIC_WORKER_THREADS` environment variable set? How are you starting your application?

-----

<details>
<summary>index.js</summary>

```js
const timeout = 5000;

const start = async () => {
  console.log(`Starting, running for ${timeout/1000} seconds`);

  await new Promise(function (resolve, _reject) {
    setTimeout(function () {
      console.log('Stopping, timeout expired');

      resolve();
    }, timeout);
 });
};

start().catch((error) => {
  console.log('Error', { error });

  process.exit(1);
});
```

</details>

<details>
<summary>package.json</summary>

```json
{
  "dependencies": {
    "newrelic": "^11.16.0"
  }
}
```

</details>

<details>
<summary>newrelic.js</summary>

```js
'use strict'
exports.config = {
  app_name: ['jsumners-playground'],
  license_key: 'redacted',
  logging: {
    level: 'trace'
  },
  
  /**
   * When true, all request headers except for those listed in attributes.exclude
   * will be captured for all traces, unless otherwise specified in a destination's
   * attributes include/exclude lists.
   */
  allow_all_headers: true,
  attributes: {
    /**
     * Prefix of attributes to exclude from all destinations. Allows * as wildcard
     * at end.
     *
     * NOTE: If excluding headers, they must be in camelCase form to be filtered.
     *
     * @name NEW_RELIC_ATTRIBUTES_EXCLUDE
     */
    exclude: [
      'request.headers.cookie',
      'request.headers.authorization',
      'request.headers.proxyAuthorization',
      'request.headers.setCookie*',
      'request.headers.x*',
      'response.headers.cookie',
      'response.headers.authorization',
      'response.headers.proxyAuthorization',
      'response.headers.setCookie*',
      'response.headers.x*'
    ]
  }
}

```

</details>

**Comment by jsumners-nr** [comment]
Node.js's loader API spawns threads to handle module loading. The `-r newrelic` gets passed to every thread started by the process. So this warning can be safely ignored.

**Comment by gevalo1** [comment]
Just to clarify still, with ignoring the warning do you mean I need to set `config.worker_threads.enabled`?
