### ISSUE TITLE
Application crash not reporting stack/error to newrelic logs

### ISSUE THREAD

**Issue by TraGicCode** [newrelic/node-newrelic#2156]
## Description

We believe our GraphQL node application using express is crashing but no log/error is reported in newrelic. Any help is greatly appreciated as we would love to prevent this from happening. 

## Expected Behavior

When the application throws an unhandled and terminating exception newrelic would show the error in newrelic logs for my apm app.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]

1. kubectl describe pod showing crash/termination

![image](https://github.com/newrelic/node-newrelic/assets/6224270/09f29776-e6fd-4a4f-9234-4dc924b96808)

2. newrelic apm logs not showing the error

![image](https://github.com/newrelic/node-newrelic/assets/6224270/45cab198-5f26-40a3-b34e-361e8cfb432d)

3. NewRelic Kubernetes deployment showing container crash

![image](https://github.com/newrelic/node-newrelic/assets/6224270/b41bfd01-1b9f-4fc4-ad32-afd375b87511)

![image](https://github.com/newrelic/node-newrelic/assets/6224270/3d78aea0-4d0e-4e8a-ac91-31de2d9f7ae9)

## Steps to Reproduce

Unable to reproduce this

## Your Environment

Node Version:
16.20.2

```
    "@babel/runtime": "^7.4.2",
    "@google-cloud/storage": "^2.4.3",
    "@graphql-tools/schema": "^8.3.10",
    "@newrelic/apollo-server-plugin": "^4.0.0",
    "apollo-server-core": "^3.13.0",
    "apollo-server-errors": "^3.3.1",
    "apollo-server-express": "^3.13.0",
    "await-to-js": "^2.1.1",
    "axios": "^0.18.0",
    "base64-stream": "^1.0.0",
    "body-parser": "^1.18.3",
    "date-fns": "^2.16.1",
    "express": "^4.19.2",
    "firebase-admin": "^8.13.0",
    "flat": "^5.0.2",
    "graphql": "^16.8.1",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.11",
    "moment": "^2.29.1",
    "newrelic": "^11.14.0",
    "passport": "^0.4.0",
    "passport-http": "^0.3.0",
    "qs": "^6.7.0",
    "sort-keys": "^2.0.0",
    "uuid": "^8.3.1",
    "winston": "^3.13.0",
    "yargs": "^13.2.2"
```

## Additional context

We are running graphql with expressjs. We also have the @newrelic/apollo-server-plugin installed.

New Relic Case Number:
00199124

**Comment by mrickard** [comment]
Sorry to hear you're having trouble, @TraGicCode . You have an active ticket with Support, so they'll be able to lead you through information gathering and debugging steps.

**Comment by TraGicCode** [comment]
hey @mrickard ,

I think i'm experiencing a similiar issue to #1561 .  I added the logging was recommended in #1561 and i noticed that the error is showing up in my winston logs but the code that does the `newrelic.noteError` and the code that shutsdown the agent along with collecting any pending data is not reporting that same error to newrelic to be shown in the APM logs.

```
// Make sure to report uncaught exceptions and unhandled rejections to New Relic
const reportErrorAndExit = (err) => {
  logger.error("Fatal error:", err); // <-- showing up in newrelic apm logs
  if (err instanceof Error) {
    newrelic.noticeError(err); // <-- not showing up in newrelic apm
  }
  newrelic.shutdown({ collectPendingData: true }, (err) => {
    if (err) {
      logger.error("Error shutting down Newrelic agent:", err); <-- not showing up in newrelic apm
    }
    process.exit(1);
  });
};
process.on("uncaughtException", reportErrorAndExit);
process.on("unhandledRejection", reportErrorAndExit);
```

**Comment by jsumners-nr** [comment]
The uncaught/unhandled callbacks should implement synchronous operations:

https://nodejs.org/docs/latest-v20.x/api/process.html#warning-using-uncaughtexception-correctly
> The correct use of 'uncaughtException' is to perform synchronous cleanup of allocated resources

`agent.noticeError` _enqueues_ an error to be sent at the next harvest cycle:

https://github.com/newrelic/node-newrelic/blob/9a14cb02dce5bfbe7830aaa25d71edb38447250b/api.js#L427-L464

https://github.com/newrelic/node-newrelic/blob/9a14cb02dce5bfbe7830aaa25d71edb38447250b/lib/errors/error-collector.js#L256-L291

https://github.com/newrelic/node-newrelic/blob/9a14cb02dce5bfbe7830aaa25d71edb38447250b/lib/transaction/index.js#L847-L855

The `shutdown` function is an _asynchronous_ function:

https://github.com/newrelic/node-newrelic/blob/9a14cb02dce5bfbe7830aaa25d71edb38447250b/api.js#L1611-L1626

https://github.com/newrelic/node-newrelic/blob/9a14cb02dce5bfbe7830aaa25d71edb38447250b/api.js#L1660-L1673
