### ISSUE TITLE
Node 22 testing

### ISSUE THREAD

**Issue by kibertoad** [newrelic/node-newrelic#2171]
## Is your feature request related to a problem? Please describe.

Node 22 is not currently officially supported by Node-Newrelic, and is not included in CI matrix.

## Feature Description

Fix whatever compatibilities with Node 22 there might be, make CI pass, include Node 22 in the CI matrix.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Really Want]

**Comment by jsumners-nr** [comment]
Please see https://github.com/newrelic/node-newrelic/pull/2164

For what it's worth, Node 22 will not be labeled as LTS by upstream until October of 2024. Until then, it is not recommended to use Node 22 for production systems.

**Comment by bizob2828** [comment]
@kibertoad based on our initial CI runs this will be a rather clean upgrade for our agent.  However, it is not on our roadmap for at least a quarter.  As @jsumners-nr said, we only support LTS versions and we have a few months until 22 is in LTS.

**Comment by bizob2828** [comment]
Linking internal [doc](https://docs.google.com/document/d/1OA7Hl2V8arMPibDarXa3EcAnQDGiEzVeUavkXdPB_90/edit?usp=sharing) that's tracking CI runs

**Comment by kibertoad** [comment]
@bizob2828 What are the implications for that if we decide to run 22 in production, other than "Don't complain about things being broken if you use it"? I remember older New Relic versions warning about "Not adding native metric sampler", which I assume had negative perf impact. Will same thing happen for Node 20 now?

**Comment by bizob2828** [comment]
@kibertoad we do not support running the agent in production with Node 22 until it is LTS.

**Comment by kibertoad** [comment]
@bizob2828 Yes, but what does "we do not support" mean? Does that mean that it might work, but if it doesn't then New Relic won't address the issues (which is fair), or is it already known up-front that there will be certain issues?

**Comment by bizob2828** [comment]
@kibertoad we don't know yet. Preliminary CI runs show this will be a very low effort.  But we will not go into the analysis until our team actually works on adding support for Node 22.  Frankly, you shouldn't be using a Node.js version that isn't LTS so any other conversations are moot.

**Comment by kibertoad** [comment]
Gotcha. Thank you for the explanation.
