### ISSUE TITLE
Next.js Frontend Browser Monitor not working

### ISSUE THREAD

**Issue by gmreburn** [newrelic/node-newrelic#2192]
The user is encountering issues with the Next.js frontend browser monitor not working as expected. They followed instructions from a blog post, but those instructions were for the Next.js pages router, while they are using the newer app router. They adjusted the instructions accordingly but are still facing errors after configuring frontend observability. The server-side monitoring metrics are working fine.

## Description

I followed the instructions from this [blog post](https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data) and updated it for use in next.js's new app router. The SSR APM monitoring works but browser does not. The issue arises when I include the "newrelic" npm package.

![image](https://github.com/newrelic/node-newrelic/assets/5257753/a02588d4-c648-44f3-b957-dc1070f5cde9)

## Expected Behavior

The user expected the frontend browser monitor to work correctly after configuring it following the adjustments made for the newer Next.js app router.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

Follow the instructions from the blog and adapt it for app router. Here are the highlights of the adaptation. I can create a clone/example if necessary but hoping this is sufficient.

```tsx
// /app/layout.tsx
export default function RootLayout({
  children,
  params: { locale }
}: RootLayoutProps) {
  const messages = useMessages()
  return (
    <html>
      <NewRelic />
<body>{children}
...
```

```tsx
// /app/newrelic.tsx
import newrelic from 'newrelic'

export default function NewRelic() {
  const browserTimingHeader = newrelic.getBrowserTimingHeader({
    hasToRemoveScriptWrapper: true
    // allowTransactionlessInjection: true
  })
  return (
    <script
      type="text/javascript"
      dangerouslySetInnerHTML={{ __html: browserTimingHeader }}
    />
  )
}

```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version: Firefox 125.0.3
* ex: Node version: v20.13.1
* ex: Operating System and version: Windows 10

## Additional context

The user received guidance from New Relic support to check if the browser app was set up correctly and connected to an existing APM app. They were directed to resources for browser monitoring with Node.js, compatibility and requirements for browser monitoring, and advised to visit the node-newrelic GitHub page for further assistance. NewRelic Case #00200702 for reference (closed).

**Comment by jsumners-nr** [comment]
Please review this example application https://github.com/newrelic/newrelic-node-examples/tree/58f760e828c45d90391bda3f66764d4420ba4990/nextjs-app-router

**Comment by bizob2828** [comment]
follow up was logged [here](https://github.com/newrelic/newrelic-node-examples/issues/230) and we determined an issue with a package we do not maintain `@newrelic/types`
