### ISSUE TITLE
Instrument node-rdkafka

### ISSUE THREAD

**Issue by kmudduluru** [newrelic/node-newrelic#2213]
### Description
Instrument `node-rdkafka` based on the published [spec](https://source.datanerd.us/agents/agent-specs/blob/main/Kafka.md)

### Acceptance Criteria
As a New Relic Node.js customer using `node-rdkafka`, I want the Node.js agent to instrument the calls to send and receive data to kafka topics

### Additional context
This may take a little longer as we have to understand how to instrument. We could handle that as research but I find researching adding instrumentation produces the instrumentation.  We could also defer the versioned tests but I'm open

**Comment by bizob2828** [comment]
Closing this in lieu of issues #2217-#2222
