### ISSUE TITLE
Cannot read properties of undefined (reading 'setCustomAttribute')

### ISSUE THREAD

**Issue by DrewML** [newrelic/node-newrelic#2238]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I'm using the `newrelic@11.12.0` package in a node.js @ `20.11.0` web app. This project uses [`newrelic.getBrowserTimingHeader()`](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/extend-your-instrumentation/browser-monitoring-nodejs-agent/#procedures) to load [the browser SDK](https://github.com/newrelic/newrelic-browser-agent) for clients. According to the inlined code, I think the version of the browser agent loaded is `1.260.1`

Although it's not recommended, this app uses another 3rd party client-side error monitoring tool in addition to New Relic. Through this 3rd party tool, I've noticed the New Relic browser SDK occasionally throwing the exception `Cannot read properties of undefined (reading 'setCustomAttribute')`.

The stack trace reported by the 3rd party tool starts at my app's helper function, `setNewRelicAttribute`. The body of that function is a tiny wrapper around `window.newrelic.setCustomAttribute(key, val)` with some safety checks to make sure `newrelic` is present on `window`.

<img width="584" alt="image" src="https://github.com/newrelic/node-newrelic/assets/5233399/21610d78-f365-408a-836a-fd8e25f945ef">

To try and narrow down a culprit for the exception, I set a breakpoint in my `setNewRelicAttribute` function in the browser, and walked through the calls into the browser agent, trying to match stack frames from the browser and from the 3rd party tool to their source on Github. Here's the trail I found into the browser agent:

1. First call into the browser agent [hits the inline function in `src/loaders/api/api.js` used to expose public API methods from the agent](https://github.com/newrelic/newrelic-browser-agent/blob/v1.260.1/src/loaders/api/api.js#L23)
2. Second call hits the [`caller` function](https://github.com/newrelic/newrelic-browser-agent/blob/v1.260.1/src/loaders/api/api.js#L27)
3. 3rd call is [inside of the `forEach` loop iterating over each initialized agent](https://github.com/newrelic/newrelic-browser-agent/blob/v1.260.1/src/loaders/api/api.js#L29)

Based on this trail, I suspect that the check for `val.exposed && val.api[fnName]` is throwing an exception due to `val.api` being `undefined` at that point in execution for _some_ reason, for _some_ clients.

## Expected Behavior

Calls to `window.newrelic.setCustomAttribute` should not throw an exception

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

I've not yet been able to replicate the exception myself. Based on events in the 3rd party tool, this seems to predominantly impact clients using Chrome on Windows.

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Additional Info

This isn't a critical issue since I can just wrap the body of the `setNewRelicAttribute` wrapper function in a `try/catch` for the time being. 

We'll also try updating to the latest version of the agent in the near future to rule out a fix already being `main`.

**Comment by bizob2828** [comment]
@DrewML you're referencing issue with the [browser agent](https://github.com/newrelic/newrelic-browser-agent). Can you log an issue with that project please?

**Comment by DrewML** [comment]
Moved to https://github.com/newrelic/newrelic-browser-agent/issues/1057
