### ISSUE TITLE
Drop support for mysql 5.7

### ISSUE THREAD

**Issue by jsumners-nr** [newrelic/node-newrelic#2269]
Our current versioned tests for the `mysql` library only work on MySQL 5.7 (see https://github.com/newrelic/node-newrelic/actions/runs/9483195320). We should update our minimum supported version of the database to 8.0 and update our versioned tests accordingly.

1. MySQL marked 5.7 as EOL on October 21, 2023 (https://dba.stackexchange.com/questions/234261/mysql-5-7-community-server-end-of-life-support has the best breakdown. Oracle's site is opaque https://www.mysql.com/support/eol-notice.html https://www.oracle.com/support/lifetime-support/software.html).
2. AWS is dropping 5.7 on October 31, 2024 (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.MySQL57.EOL.html)

It does not make sense to continue supporting 5.7.

**Comment by bizob2828** [comment]
I don't think this is a semver major. We don't state we support version x of the database server. we just support versions 2.2.0+ of the npm library.  This is probably a case of that was the version of mysql when the container was added and we've never updated
