### ISSUE TITLE
url_obfuscation is ignored when added via addCustomAttributes

### ISSUE THREAD

**Issue by garciasdos** [newrelic/node-newrelic#2302]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When using `addCustomAttributes` to add the `request.uri` attribute, `obfuscatePath` function is not being called 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

Even if I set `request.uri` as a custom attribute, I expect it to be obfuscated.

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

- Define a `url_obfuscation` configuration.
- Start a WebTransaction (`apmInstance.startWebTransaction`)
- Add a custom attribute (`apmInstance.addCustomAttributes`)
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
Node v20.13.1
newrelic@v10.4.1
## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jsumners-nr** [comment]
This is working as intended. Custom attributes are added by users, and we cannot know ahead of time if they should be manipulated in anyway. We suggest performing redaction prior to adding the custom attribute.
