### ISSUE TITLE
[spike] Research replacing `examples/shim` with workable example applications

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#2311]
### Description
There is a lot of good information in `examples/shim`.  These get published to API docs as [tutorials](https://newrelic.github.io/node-newrelic/tutorial-Context-Preservation.html).  The goal of this spike is to determine what's missing in our current example applications and cut tickets to address the gaps.  The intent of those stories will be to replace code snippets with links to example applications that can be run and see in action.

**Comment by amychisholm03** [comment]
Created 3 GH issues that details how we will do this
