### ISSUE TITLE
update grpc-js@1.10.9

### ISSUE THREAD

**Issue by mmmelroy** [newrelic/node-newrelic#2320]
security concern for grpc-js@1.10.1

suggested to upgrade to grpc-js@1.10.9

## Description

Affected versions of this package are vulnerable to Uncontrolled Resource Consumption via the grpc.max_receive_message_length channel option. An attacker can cause a denial of service by sending messages that exceed the configured limits, which are then buffered or decompressed into memory.

## Additional context
(https://security.snyk.io/vuln/SNYK-JS-GRPCGRPCJS-7242922)

**Comment by querry43** [comment]
this would be helpful to me as well!

**Comment by jsumners-nr** [comment]
Duplicate of https://github.com/newrelic/node-newrelic/issues/2260
