### ISSUE TITLE
Convert native errors to strings in NR Winston transport

### ISSUE THREAD

**Issue by daniel-smyth** [newrelic/node-newrelic#2330]
## Problem
There is a discrepancy between identical logs in our cloud provider and New Relic. Specifically, native JS errors appear in our cloud provider but not in New Relic. They appear in our cloud provider because we format them to be serialisable before dispatching. The NR Winston transport tries to do this but is very particular about where it expects errors in `reformatError` in `lib/instrumentation/nr-winston-transport.js`. 

The error in the cloud provider:
```ts
{
  "module": "i-am-the-module/where-the-code-is",
  "error": {
    "message": "I failed! I am sorry!",
    "stack": "Error: I failed! I am sorry!.
      at BrokenClass.doSomething (/app/dist/logic/foo/bar/index.js: 94: 19)
      at async #onSomeEvent (/app/dist/logic/bar/foo.js: 195: 31)"
  }
}
```
The error in New Relic:
```ts
{
  "module": "i-am-the-module/where-the-code-is",
  // Empty!
}
```

We utilise our own Winston formatter before dispatching to our cloud provider via [logform's](https://github.com/winstonjs/logform) `json` formatter. It is nothing special, just looks like this:

```ts
import util from 'util';
import { createLogger, format } from 'winston';

export const logger = createLogger({
  // ...
  format: format.combine(
    // ...
    format.json({
      replacer: (_key, value: unknown) => (value instanceof Error ? util.format(value) : value),
    })
  ),
});
```

Ideally, the NR Winston transport would use our formatters first before sending them to New Relic but from what I have looked at (and I admit I am not an expert in this domain) this seems difficult. What I suggest below is a more straightforward alternative. 

## Feature Description
The NR Winston transport should try to make all errors serialisable before log forwarding. 

```js
/**
 * Reformats a log line by reformatting errors, timestamp and adding
 * new relic linking metadata(context). When uncaught exceptions exist
 * an exception property will exist on the log line.  This will tell us
 * that we need to reformat the error
 *
 * @param {object} logLine log line
 * @param {object} metadata linking metadata
 * @returns {object} copy of log line with NR linking metadata
 */
function reformatLogLine(logLine, metadata) {
  // Add the metadata to a copy of the logLine
  const formattedLine = Object.assign({}, logLine, metadata)

  if (formattedLine.exception === true) {
    reformatError(formattedLine)
  }

  // Add this step.
  reformatErrorsToStrings(formattedLine)

  reformatTimestamp(formattedLine)

  return formattedLine
}

/**
 * Converts all errors in an object to strings
 * @param {object} logLine log line
 * @returns {object} a copy of the object with all errors converted to strings
 */
function reformatErrorsToStrings(logLine) {
  if (logLine instanceof Error) {
    return util.format(logLine)
  }

  if (Array.isArray(logLine)) {
    return logLine.map(reformatErrorsToStrings)
  }

  if (typeof logLine === 'object' && logLine !== null) {
    const result = {}
    for (const key in logLine) {
      if (logLine.hasOwnProperty(key)) {
        result[key] = reformatErrorsToStrings(logLine[key])
      }
    }
    return result
  }

  return logLine
}
```

## Describe Alternatives
Alternatively, the NR transport could utilise Winston formatters the consumer have themselves listed before trying to format errors themselves. 

## Priority
Nice to have. We are considering [forwarding logs from the log file](https://docs.newrelic.com/docs/logs/forward-logs/enable-log-management-new-relic/#log-forwarding), rather than using automatic forwarding with the APM agent.

**Comment by jsumners-nr** [comment]
Thank you for the detailed write up, but I'm still rather unclear what the ask is. Can you provide a minimal example that shows the problem?

**Comment by daniel-smyth** [comment]
Sure. 

```ts
const logger = createLogger({
  level: LOGGER_LEVEL,
});

logger.error(`Message for the error log`, {
  errors: [new Error(`Error message`), new Error(`Another error message`)],
});

// The above will appear in New Relic as:
// {
//   "message": "Message for the error log",
//   "errors": [],
// }
```

Since native JS errors are not JSON serialisable, they appear empty when serialised before sending to New Relic. 

New Relic _tries_ to handle this in the `reformatError` in `lib/instrumentation/nr-winston-transport.js`, however, it is _very_ particular about where it expects errors to appear. 

We do not have this same issue when sending logs to our cloud provider because we serialise all native JS errors before transporting via a Winston formatter. We check if any errors are present in the log metadata before dispatching. I think New Relic APM agent should do the same. 

```ts
import util from 'util';
import { createLogger, format } from 'winston';

export const logger = createLogger({
  // ...
  format: format.combine(
    // ...
    format.json({
      replacer: (_key, value: unknown) => (value instanceof Error ? util.format(value) : value),
    })
  ),
});
```

**Comment by jsumners-nr** [comment]
Okay, as I am understanding the issue:

1. `winston.error()` (or any log method) accepts an object as the log message, such that if `msg` or `msg.message` exists it will use that as the log message (https://github.com/winstonjs/winston/blob/7f5f014d56f646bd96b989922d69e60c91f6f664/lib/winston/create-logger.js#L77-L78). But any other properties get serialized in some way or other depending on various factors (I really can't follow that code base to figure out the details).
2. You have some sort of transport registered that recognizes an `errors` property on logged objects and serializes them.
3. Your transport is not getting evaluated when the `newrelic` agent is in place.

If that is true, I am unable to replicate the issue:

```js
'use strict'

const newrelic = require('newrelic')

const util = require('util')
const Transport = require('winston-transport')
const tsport = class ExampleTransport extends Transport {
  log(info, callback) {
    if (info.errors) {
      info.errors = info.errors.map(error => util.format(error))
    }
    callback()
  }
}

const winston = require('winston')
const logger = winston.createLogger({
  level: 'info',
  transports: [new tsport()]
})

newrelic.startBackgroundTransaction('winston-errors', () => {
  logger.error('Some errors', {
    errors: [
      Error('boom'),
      Error('boom boom')
    ]
  })

  newrelic.shutdown({ collectPendingData: true }, () => {
    console.log('finished')
  })
})
```

The transport gets evaluated correctly. In my dashboard, I see the reformatted errors that have been manipulated by the transport:

![image](https://github.com/newrelic/node-newrelic/assets/150050532/4386a5e9-bba1-47ba-86cc-75a6b2fb08e4)

**Comment by jsumners-nr** [comment]
I'm going to close this as not reproducible. Please provide a reproduction if you think this is inaccurate.
