### ISSUE TITLE
isBuiltin is not a function in node-newrelic 11.19.0 on Linux NodeJS 18.2.0

### ISSUE THREAD

**Issue by DeeptiGuptaP** [newrelic/node-newrelic#2364]
Newrelic agent throws error isBuiltin is not a function

## Description

Newrelic agent throws error isBuiltin is not a function, Agent version: 11.19.0; Node version: v18.2.0.

## Expected Behavior

It should work correctly

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
{"v":0,"level":30,"name":"newrelic","hostname":"8504c59e9ec6","pid":18,"time":"2024-07-16T09:01:35.614Z","msg":"Using New Relic for Node.js. Agent version: 11.19.0; Node version: v18.2.0."}
{"v":0,"level":30,"name":"newrelic","hostname":"8504c59e9ec6","pid":18,"time":"2024-07-16T09:01:35.762Z","msg":"Using AsyncLocalContextManager"}
{"v":0,"level":50,"name":"newrelic","hostname":"8504c59e9ec6","pid":18,"time":"2024-07-16T09:01:35.764Z","msg":"New Relic for Node.js was unable to bootstrap itself due to an error:","stack":"TypeError: isBuiltin is not a function\n    at new Shim (/app/node_modules/newrelic/lib/shim/shim.js:51:22)\n    at Object.registerCoreInstrumentation (/app/node_modules/newrelic/lib/shimmer.js:328:24)\n    at Object.bootstrapInstrumentation (/app/node_modules/newrelic/lib/shimmer.js:391:13)\n    at createAgent (/app/node_modules/newrelic/index.js:164:11)\n    at initialize (/app/node_modules/newrelic/index.js:105:15)\n    at Object.<anonymous> (/app/node_modules/newrelic/index.js:39:3)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\nat Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Module._load (node:internal/modules/cjs/loader:827:12)","message":"isBuiltin is not a function"}

## Steps to Reproduce

Include v11.19.0 in package.json

## Your Environment

Node version: 18.2.0

**Comment by jsumners-nr** [comment]
`module.isBuiltin` was added in Node 18.6.0. Please upgrade from Node 18.2.0 to resolve the issue.

https://nodejs.org/api/module.html#moduleisbuiltinmodulename
