### ISSUE TITLE
Add new config `explain_threshold` to something more accurate

### ISSUE THREAD

**Issue by kmudduluru** [newrelic/node-newrelic#2384]
currently node agent uses explain_threshold config for slow query threshold transaction traces. this config name is confusing to customers as it can be related to explain plan feature that Node.js agent does not support yet.  
Since the Node agent does not collect SQL explain plans the explain_threshold , config option in Node [is just an threshold for slow queries and transaction traces](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#explain_threshold):

Minimum query duration (in milliseconds) for a transaction to be eligible for [slow queries](https://docs.newrelic.com/docs/apm/applications-menu/monitoring/viewing-slow-query-details/) in [transaction traces](https://docs.newrelic.com/docs/apm/transactions/transaction-traces/transaction-traces/).  

Since this is confusing, need to add new config for slow query threshold (DatastoreTracer.SlowQuery.Threshold) and also update the description of the old config so the purpose of that config is clear.  This way we dont create a breaking change for other customers. 
suggest renaming it to something like slow_query_threshold. This would align with what the [Go agent ](https://docs.newrelic.com/docs/apm/agents/go-agent/configuration/go-agent-configuration/#slow-query-threshold)uses (DatastoreTracer.SlowQuery.Threshold) 

[spec](https://source.datanerd.us/agents/agent-specs/blob/main/Slow-SQLs-LEGACY.md)

**Comment by jsumners-nr** [comment]
See the summary at https://github.com/newrelic/node-newrelic/pull/2390#discussion_r1687147846
