### ISSUE TITLE
Fastify v4 Support

### ISSUE THREAD

**Issue by JesKingDev** [newrelic/node-newrelic#2408]
## Is your feature request related to a problem? Please describe.
Web Framework instrumentation is available for Fastify, but the semver matching is restricted to 3.x. When running the Node agent on a Fastify v4 app, all transactions are grouped under `*`.

## Feature Description
Add support for Fastify v4 along with (or instead of?) v3.

## Describe Alternatives
N/A

## Additional context
[Fastify's migration guide for v3 -> v4](https://fastify.dev/docs/latest/Guides/Migration-Guide-V4/)

## Priority
Really Want

**Comment by mrickard** [comment]
@JesKingDev We don't restrict our instrumentation to Fastify 3.x. We have tests that run across several versions of Fastify, with two branches: > 2 and < 3, and >= 3. On running the versioned tests for Fastify just now, I see these versions passing: 2.0.1, 2.1.0, 2.3.0, 2.5.0, 2.7.1, 2.8.0, 2.10.0, 2.12.1, 2.14.1, 2.15.3, 3.0.3, 3.6.0, 3.13.0, 3.19.2, 3.26.0, 4.2.1, 4.9.2, 4.15.0, 4.22.2, 4.28.1. These tests do check transaction names, so transaction naming would be consistent across these versions. 

If you're having trouble with Fastify v4 instrumentation, I'd recommend opening a ticket with [Support](https://support.newrelic.com/s/), who can help you resolve this.
