### ISSUE TITLE
Missing error details when module initialization throws during SSR

### ISSUE THREAD

**Issue by DrewML** [newrelic/node-newrelic#2420]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I'm investigating an issue in my employer's app where we see an increase in 500 errors in New Relic, but these errors do not have any context or stack traces. Looking through our application logs, we see Next.js logging the actual error objects directly to `console.error`, but the NR agent doesn't seem to capture this info.

As a test, we added some code locally to purposely throw, during a request to the `/` route, during the top-level execution of one of our modules. That code is:

```js
if (process.env.NEXT_PHASE !== 'phase-production-build') {
  // emulate an error thrown as a side-effect of module initialization.
  // process.env check is to make sure the build passes, to make sure this is a runtime error
  // and not a build error
  throw new Error('this error is not captured by New Relic');
}
```

We then traced the execution path through Next.js code to determine where these errors were being passed to `console.error`, and determined the error is caught (and logged) inside of [`renderToResponseImpl`](https://github.com/vercel/next.js/blob/5d2d7c07d935895911cdd5424de3435464f9542c/packages/next/src/server/base-server.ts#L3460). The error is then passed to the [`renderErrorToResponse`](https://github.com/vercel/next.js/blob/5d2d7c07d935895911cdd5424de3435464f9542c/packages/next/src/server/base-server.ts#L3560) method.

My suspicion is that this package, `newrelic-node-nextjs`, is missing instrumentation of the `renderErrorToResponse` method, which would unlock the ability to capture the Error object associated with the failed request and 500 error.

## Expected Behavior

If an exception is thrown as a side-effect of module initialization in the dependency graph for a Next.js app, that error is reported to New Relic.

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

1. Get a Next.js app setup with the "Pages Router" (as opposed to "App Router") and `newrelic-node-nextjs`
2. In the top-level of `pages/index.tsx`, throw an error using the sample code provided in this ticket
3. Run a build
4. Run the app in Production mode, and navigate to the `/` route in your browser
5. Confirm a generic 500 was reported to New Relic

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
* `next` version: 14.2.2
* `@newrelic/next` version: 0.9.0
* `node` version: 20.11.0

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment]
Moving this issue to `node-newrelic` as the Next.js instrumentation has been merged into agent

**Comment by bizob2828** [comment]
I'm closing this based on my comment from 3 weeks ago.  If this doesn't meet your needs, please reopen with more details
