### ISSUE TITLE
E2E Elasticache redis service setup

### ISSUE THREAD

**Issue by kmudduluru** [newrelic/node-newrelic#2426]
This ticket is to track the end2end testing of AWS Elasticache redis service.

**Note**: We instrument both `redis` and `ioredis`, there should be two different test scenarios to validate

Will also need to edit this Confluence page when we are done: https://newrelic.atlassian.net/wiki/spaces/INST/pages/3354723296/AWS_ELASTICACHE_REDIS_CLUSTER

**Comment by bizob2828** [comment]
https://github.com/newrelic/node-aws-e2e/pull/9 and https://github.com/newrelic/node-aws-e2e/pull/7
