### ISSUE TITLE
Determine resolution to superagent@10 breaking versioned tests

### ISSUE THREAD

**Issue by jsumners-nr** [newrelic/node-newrelic#2451]
Version 10 of `superagent` is causing our versioned tests to fail. We need to determine the cause and a fix. See https://github.com/newrelic/node-newrelic/pull/2439

**Comment by bizob2828** [comment]
I think this is a case of waiting on superagent. they have 2 prs to fix the issue: https://github.com/ladjs/superagent/pull/1813, and https://github.com/ladjs/superagent/pull/1814
