### ISSUE TITLE
`custom-instrumentation` API docs cleanup

### ISSUE THREAD

**Issue by amychisholm03** [newrelic/node-newrelic#2468]
### Description
After [removing examples/shim](https://github.com/newrelic/node-newrelic/issues/2467), we need to go through docs.newrelic.com to replace any links that pointed to `node-newrelic/examples`. We should also cleanup any redundant documentation regarding custom instrumentation.

**Comment by bizob2828** [comment]
We should reach out to the docs team to give them a heads up as this will be a drastic change
