### ISSUE TITLE
Remix Vite ESM loader fails to start

### ISSUE THREAD

**Issue by kenn** [newrelic/node-newrelic#2482]
## Description

I have installed NewRelic with [Remix Vite](https://remix.run/docs/en/main/guides/vite) and ESM, but it fails to start the server in production build.

```ts
> node --experimental-loader newrelic/esm-loader.mjs -r newrelic ./server.js
==> Exited with status 1
==> Common ways to troubleshoot your deploy: https://docs.render.com/troubleshooting-deploys
(node:102) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("newrelic/esm-loader.mjs", pathToFileURL("./"));'
debug
(Use `node --trace-warnings ...` to show where the warning was created)
file:///opt/render/project/src/frontend/build/server/index.js:36
import { relations, desc, isNull, isNotNull, gte, lte, eq, and, count, inArray, asc, sql } from "drizzle-orm";
                                                           ^^^
SyntaxError: The requested module 'drizzle-orm' does not provide an export named 'and'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async file:///opt/render/project/src/frontend/server.js:21:7
Node.js v20.16.0
 ELIFECYCLE  Command failed with exit code 1.
```

I don't have issues with starting the server without `--experimental-loader` for NewRelic.

```ts
> node ./server.js
🔌 setting up drizzle client
✅ app ready at http://localhost:10000
HEAD / 200 - - 153.861 ms
==> Your service is live 🎉
```

## Expected Behavior

Start without issue

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

N/A

## Steps to Reproduce

Compare these two start modes:

Success:

```ts
node ./server.js
```

Failure:

```ts
node --experimental-loader newrelic/esm-loader.mjs -r newrelic ./server.js
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Node version: v20.16.0
* Hosting provider: [Render.com](https://render.com/)
* [node-newrelic](https://github.com/newrelic/node-newrelic) version: v12.1.1

## Additional context

We were using NewRelic before upgrading Remix to Vite / ESM.

When we completed upgrade, we gave up on NewRelic. This is our second trial thinking updated node-newrelic v12 might fix the issue, but still fails.

**Comment by bizob2828** [comment]
@kenn the ESM loader is experimental and it's just proxy to [import-in-the-middle](https://github.com/nodejs/import-in-the-middle).  This would be a bug with that package but if you look at issues it's like this [one](https://github.com/nodejs/import-in-the-middle/issues/141).
