### ISSUE TITLE
docs: Update documentation for Node Site Extension for Azure

### ISSUE THREAD

**Issue by mrickard** [newrelic/node-newrelic#2597]
### Description
Now that customers using Windows webapps in Azure can install the agent via an Azure Site Extension, we should make sure our docs are aligned with the Site Extension recommendations and behavior.

We should note that site extensions are only available for code-only webapps (not containerized webapps), and only for Windows. 

### Additional context
See the [Azure Site Extension readme](https://github.com/newrelic/node-newrelic/blob/main/cloud-tooling/azure-site-extension/Content/README.md).

**Comment by kmudduluru** [comment]
closing this issue as duplicate
