### ISSUE TITLE
amqplib is not instrumented in ESM (unless using createRequire)

### ISSUE THREAD

**Issue by antmarot** [newrelic/node-newrelic#2663]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I'm using esm loader, as described in the documentation.

As I noticed that amqplib was not being instrumented in my ESM app, I tried all styles of import I could think of as an attempt to see whether or not that fixed the issue
```typescript
// original import
import { connect } from 'amqplib';
connect(...);

// star import
import * as amqplib from 'amqplib';
amqplib.connect(...)

// default import
import { default as amqplib } from 'amqplib';
amqplib.connect(...)

// classic default import
import amqplib from 'amqplib';
amqplib.connect(...)
```
None of these resulted in amqplib being instrumented.

Only falling back to `require` worked:
```typescript
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const amqplib = require('amqplib');

amqplib.connect(...)
```

As shown in this log, use `createRequire` finally worked:
```
{"v":0,"level":10,"name":"newrelic","hostname":"...","pid":1,"time":"2024-10-16T14:14:24.212Z","msg":"Instrumenting amqplib/channel_api with onRequire (module loaded) hook.","component":"shimmer"}
{"v":0,"level":10,"name":"newrelic","hostname":"...","pid":1,"time":"2024-10-16T14:14:24.213Z","msg":"Instrumenting basic Channel class.","component":"MessageShim","module":"amqplib/channel_api","library":"RabbitMQ"}
```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
`amqplib` to be properly instrumented when using the ESM loader and import statements.

## Your Environment

* Node version: 20.10
* amqplib version: 0.10.4
* newrelic version: 12.5.1

**Comment by jsumners-nr** [comment]
I'm looking in to this.
