### ISSUE TITLE
Cannot use with esbuild based application (AWS CDK)

### ISSUE THREAD

**Issue by Kilowhisky** [newrelic/node-newrelic#2664]
## Description

I'm trying to instrument custom events for nodejs based AWS ECS Tasks and Lambdas. I currently have successful lambda layer implementation but i am not able to send custom events using this method. 

In order to do so i need to install `newrelic` into the main `package.json`.  My AWS functions and tasks are created and managed using  AWS CDK which uses esbuild in order to bundle and prepare my applications. The problem is when i attempt to import the function to record a custom event i get tons of build errors i can't seem to resolve. 

I've tried all the following

```
import { recordCustomEvent } from "newrelic";
import newrelic from 'newrelic';
import * as NR from 'newrelic';
const NR = require('newrelic');
```
and they all result in these errors.
```
X [ERROR] No loader is configured for ".md" files: node_modules/newrelic/README.md

    node_modules/newrelic/index.js:42:22:
      42 │   const API = require(`./${apiPath}`)
         ╵                       ~~~~~~~~~~~~~~

X [ERROR] No loader is configured for ".md" files: node_modules/newrelic/THIRD_PARTY_NOTICES.md

    node_modules/newrelic/index.js:42:22:
      42 │   const API = require(`./${apiPath}`)
         ╵                       ~~~~~~~~~~~~~~

X [ERROR] Expected ";" but found "License"

    node_modules/newrelic/LICENSE:1:40:
      1 │                                  Apache License
        │                                         ~~~~~~~
        ╵                                         ;

X [ERROR] Could not resolve "split"

    node_modules/newrelic/bin/tracetractor:23:21:
      23 │   , split  = require('split')
```

If i use this to import
```
import * as NR from 'newrelic/esm-loader.mjs';
```
I get build warnings but it still builds. Unfortunately it won't run as it throws the following errors. 

```
2024-10-16T16:53:55.766Z	undefined	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Invalid URL",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Invalid URL",
        "code": "ERR_INVALID_URL",
        "input": "lib/register.js",
        "stack": [
            "TypeError: Invalid URL",
            "    at new URL (node:internal/url:797:36)",
            "    at createHook2 (/var/task/index.js:12042:23)",
            "    at Object.<anonymous> (/var/task/index.js:12572:86)",
            "    at Module._compile (node:internal/modules/cjs/loader:1469:14)",
            "    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)",
            "    at Module.load (node:internal/modules/cjs/loader:1288:32)",
            "    at Module._load (node:internal/modules/cjs/loader:1104:12)",
            "    at cjsLoader (node:internal/modules/esm/translators:346:17)",
            "    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)",
            "    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Invalid URL",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)",
        "    at process.emit (node:events:519:28)",
        "    at process.wrappedEmit [as emit] (/opt/nodejs/node_modules/newrelic/lib/instrumentation/core/globals.js:53:23)",
        "    at emitUnhandledRejection (node:internal/process/promises:250:13)",
        "    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)",
        "    at processPromiseRejections (node:internal/process/promises:470:17)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version: AWS Lambda / ECS (Docker)
* ex: Node version: LTS

**Comment by chaudharysaket** [comment]
Hi @Kilowhisky 
Please have a look at our example [here](https://github.com/newrelic/newrelic-lambda-extension/blob/main/examples/sam/node/newrelic-example-node/app.js). Although the example uses SAM, similar implementation using AWS CDK tool should work.

**Comment by Kilowhisky** [comment]
Hi @chaudharysaket ,

There are a few differences between your code and mine. I took your repo and applied the changes and got it into the broken build state. You can try it out yourself using `npx cdk synth`. 

https://github.com/Kilowhisky/lambda-instrumentation-cdk-nodejs

The chief differences are: 
* Utilize TypeScript instead of JavaScript
* Utilize ESBuild 
* Utilize `new NodeJsFunction()` instead of `new lambda.Function()`. See [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.NodejsFunction.html) as to why. 

All the changes listed above come out of the box when you utilize cdk with the `TypeScript` template parameter, so it is a standard configuration.

**Comment by chaudharysaket** [comment]
Hi @Kilowhisky 
I have updated the reference [code](https://github.com/chaudharysaket/lambda-instrumentation-cdk-nodejs) to incorporate the changes requested above such as use of TypeScript , `esbuild` & `new NodeJsFunction()` .
We need to add `newrelic` to the CDK NodejsFunction construct as externalModules to the bundling parameter. 
```
bundling: {
        sourceMap: true,
        externalModules: [
            'newrelic',
        ]               
    },
```
You can refer one public blog [here](https://shawntorsitano.com/blog/cdk-lambda-layers/) that discusses about using Lambda Layers with TypeScript and CDK.
Please let us know if this resolves your issue. 
Thank you!

**Comment by Kilowhisky** [comment]
This fixes it! thanks.
