### ISSUE TITLE
Enhance Proxy Request Handling to Display Actual External URLs in Node.js APM Client

### ISSUE THREAD

**Issue by mstarzec386** [newrelic/node-newrelic#2688]
## Is your feature request related to a problem? Please describe.
In Node.js applications, when using the New Relic Node.js APM client with a proxy (Axios with HTTP_PROXY, HTTPS_PROXY, NO_PROXY environments set), we are unable to distinguish external domains in the “External Services” section. Currently, all requests routed through a proxy display as PROXY:PROXY_PORT (e.g., "proxy.company.network:8080") without showing the actual destination URL, making it difficult to track and analyze specific external services.

## Feature Description
We would like the New Relic Node.js APM client to better handle proxy requests by capturing the actual external destination rather than displaying only the proxy server's details. Specifically, we suggest enhancing the client to recognize and differentiate the ultimate external URLs accessed via the proxy.

## Describe Alternatives
As a workaround, we’ve forked the New Relic Node.js package and applied a patch in the lib/instrumentation/core/http-outbound.js file.
The change: https://github.com/mstarzec386/node-newrelic/commit/85cfde5aca85cc9f95272d4bf32e52ee96208ba7

Another alternative we considered was using startWebTransaction. However, this approach is limited because it doesn’t fully support external calls made from external packages and is also more challenging to implement in the apps.

## Additional context
This enhancement would improve observability for applications using proxies, enabling us to monitor actual external service calls more accurately.

## Priority
Really Want

**Comment by bizob2828** [comment]
Hi @mstarzec386 can you please open a PR for your suggested change?

**Comment by mstarzec386** [comment]
> Hi @mstarzec386 can you please open a PR for your suggested change?

https://github.com/newrelic/node-newrelic/pull/2698
