### ISSUE TITLE
Get newrelic working in edge middleware

### ISSUE THREAD

**Issue by JohnMarsden24** [newrelic/node-newrelic#2690]
I want to run `newrelic` in [Next's middleware](https://nextjs.org/docs/app/building-your-application/routing/middleware) which runs on the edge.

[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
I've followed the [Next instrumentation and ECMAScript modules guides](https://nextjs.org/docs/app/building-your-application/routing/middleware) and copied the [example](https://github.com/newrelic/newrelic-node-examples/blob/58f760e828c45d90391bda3f66764d4420ba4990/nextjs-app-router/next.config.js) and while that all works fine in server components it does not work for me in my `middleware.ts`.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
I expect `newrelic` to be be a ES6 module which can run in the middleware in an edge runtime

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

- Follow the steps and example above but add a middleware file which uses `newrelic`

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* `"newrelic": "^12.3.0"`, `"next": "14.2.11"`

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment]
Next.js middleware runs in a worker thread. Our agent does not propagate between the main and worker threads so there's nothing useful that would happen here
