### ISSUE TITLE
Regex is blocking thread

### ISSUE THREAD

**Issue by modestaspruckus** [newrelic/node-newrelic#2703]
[NOTE]: # sql query parser is blocking main thread

## Description

We're using latest newrelic package ^12.6.0 and noticed performance issues with enabled apm agent. Node profiling shows that issue relies on sql parser regex. Issue occurs only with enabled newrelic package.

## Expected Behavior

Try to avoid using heavy regex

## node profiling results
```js
   ticks parent  name
  115723   50.4%  RegExp: \/\\*.*?\\*\/
  115719  100.0%    JS: *parseSql /app/node_modules/newrelic/lib/db/query-parsers/sql.js:29:35
  115719  100.0%      JS: *queryRecorder /app/node_modules/newrelic/lib/shim/datastore-shim.js:552:64
  115719  100.0%        JS: *wrapper /app/node_modules/newrelic/lib/shim/shim.js:668:26
  58027   50.1%          JS: *runInContextCb /app/node_modules/newrelic/lib/shim/shim.js:1178:26
  58027  100.0%            JS: *run node:async_hooks:332:6
  57692   49.9%          JS: ^<anonymous> /app/node_modules/mysql2/lib/pool.js:144:24
  57692  100.0%            JS: *runInContextCb /app/node_modules/newrelic/lib/shim/shim.js:1178:26
```

## Steps to Reproduce

Issue occurs only when specific json is saved to database e.g. having many `\\\\` characters inside (attaching payload example)
[scratch_86.json](https://github.com/user-attachments/files/17648501/scratch_86.json)

## Your Environment

node@20
mysql2 package
newrelic@12.6.0

**Comment by jsumners-nr** [comment]
@modestaspruckus thank you for the report. I am looking into this issue. Unfortunately, it doesn't look like we have a way to disable query parsing individually. In the meantime, can you provide me with an SQL statement that would fail? Basically, what does a basic statement look like that would include the provided JSON as part of it?

**Comment by jsumners-nr** [comment]
@modestaspruckus are you able to provide the additional context I have requested?

**Comment by jsumners-nr** [comment]
I am closing this as not reproducible due to lack of response. If you are able to provide the requested information, please do and we can re-open the issue. If you try the changes in #2714 and find that the solve the issue, please report that as well.
