### ISSUE TITLE
Enable Trivy Github Action in node.js agent teams repos

### ISSUE THREAD

**Issue by kmudduluru** [newrelic/node-newrelic#2704]
### Description
Enable Trivy security scans for GHA workflows
Acceptance Criteria

### Acceptance Criteria

Follow standardized instructions, validate and close per standards
Design Consideration/Limitations and follow similar changes done by Ruby agent team - https://new-relic.atlassian.net/browse/NR-303890

**Comment by bizob2828** [comment]
@kmudduluru  I don't understand the point of this story. We have containers but they are for our tests only.  We have some older containers because we support older versions of certain technologies. We don't ship our containers so trivvy will just be unncessary noise

**Comment by bizob2828** [comment]
Confirmed with [security](https://newrelic.slack.com/archives/C056KB65U06/p1732032564534229) that this is not needed for our team because we don't ship the containers we use to test
