### ISSUE TITLE
PinoHttp automatic http logs with default successful log message not being forwarded to NewRelic

### ISSUE THREAD

**Issue by danimagb-moonfare** [newrelic/node-newrelic#2718]
## Description

I'm using nestjs-pino which uses pino-http  and allows me to log http requests automatically.
The pino-http package automatically logs http requests with a default message based on the result of the request (e.g: 'request completed', 'request errored', 'request aborted', etc...)

I noticed that when the log message is 'request completed', I see the log in my console locally but it seems that for some reason the log never reaches newrelic. If I customize the log message to something else like 'http request completed', then I'm able to see it in my console and it is automatically forward to newrelic by the agent.

I was able to find a similar bug related to pino-http [here](https://github.com/newrelic/node-newrelic/issues/2595)
I tried to update my newrelic node agent to the version where the bug was fixed but it didn't help, so I guess this may be something else.
https://github.com/newrelic/node-newrelic/releases/tag/v12.5.1

## Expected Behavior

The log should reach newrelic regardless of the message being logged.  The log should be forwarded to newrelic when the log message is 'request completed'.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

When configuring the module without customizing the default success message defined in pino-http for successful http requests I can see the logs in my console, but the automatic http log never reaches newrelic. 

```typescript
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { LoggerModule } from 'nestjs-pino';

@Module({
  imports: [LoggerModule.forRoot({
    pinoHttp:{
      autoLogging: true,
      level: 'debug',
      useLevel: 'debug',
    }
  })],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```
Console Logs
![default_logs](https://github.com/user-attachments/assets/5abae57b-583c-4187-b730-ee2a946349d3)

**Default PinoHttp success log message  `request completed` isn't forwarded  to NewRelic**

NewRelic logs 
![default_nr_logs](https://github.com/user-attachments/assets/62e42b28-0100-4707-9bab-a71116139fb5)

**When I change the log message to a custom one like `Http Request Completed`,  it starts working**
```typescript
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { LoggerModule } from 'nestjs-pino';

@Module({
  imports: [LoggerModule.forRoot({
    pinoHttp:{
      autoLogging: true,
      level: 'debug',
      useLevel: 'debug',
      customSuccessMessage: (req, res) : string => (!req.readableAborted && res.writableEnded ?
        'Http Request Completed' :
        'Http Request Aborted'),
      customErrorMessage: () : string => 'Http Request Errored',
    }
  })],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```
Console Logs
![custom_logs](https://github.com/user-attachments/assets/ec7fd023-8246-44cd-b39e-813b3f945a1f)

NewRelic logs 
![custom_nr_logs](https://github.com/user-attachments/assets/4ee9fe48-2e1b-4456-8a34-11972051a76b)

[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

Link to the repo [here](https://github.com/danimagb-moonfare/newrelic-nestjs-pino)

## Your Environment

* NestJs version: 10.0.0
* Node version: 20.16.0
* nestjs-pino version: 4.1.0
* pino-http version: 10.3.0
* newrelic node agent version: 12.6.1

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jsumners-nr** [comment]
Are you able to provide a minimal reproduction with plain JavaScript?

**Comment by danimagb-moonfare** [comment]
> Are you able to provide a minimal reproduction with plain JavaScript?

Hi @jsumners-nr ,
You can find it [here](https://github.com/danimagb-moonfare/newrelic-pino-js)

**Comment by jsumners-nr** [comment]
> > Are you able to provide a minimal reproduction with plain JavaScript?
> 
> Hi @jsumners-nr , You can find it [here](https://github.com/danimagb-moonfare/newrelic-pino-js)

I am getting a 404 when I visit that link. Can you make it public?

**Comment by danimagb-moonfare** [comment]
> > > Are you able to provide a minimal reproduction with plain JavaScript?
> > 
> > 
> > Hi @jsumners-nr , You can find it [here](https://github.com/danimagb-moonfare/newrelic-pino-js)
> 
> I am getting a 404 when I visit that link. Can you make it public?

My bad! it should be public now.

**Comment by bizob2828** [comment]
@danimagb-moonfare I ran your repro and I see the `request completed` log messages. When I uncomment out the code I see the `Http Request Completed` messages as well

<img width="830" alt="screenshot 2024-11-12 at 12 47 29 PM" src="https://github.com/user-attachments/assets/bcb7b462-29a6-4dce-9806-7de43277b3a1">

**Comment by danimagb-moonfare** [comment]
> @danimagb-moonfare I ran your repro and I see the `request completed` log messages. When I uncomment out the code I see the `Http Request Completed` messages as well
> 
> <img alt="screenshot 2024-11-12 at 12 47 29 PM" width="830" src="https://private-user-images.githubusercontent.com/1874937/385399469-bcb7b462-29a6-4dce-9806-7de43277b3a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQwMTUsIm5iZiI6MTczMTQ5MzcxNSwicGF0aCI6Ii8xODc0OTM3LzM4NTM5OTQ2OS1iY2I3YjQ2Mi0yOWE2LTRkY2UtOTgwNi03ZGU0MzI3N2IzYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMTAyODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNkNzZiYTM4Yzc0Njc0MGI3YWU1MzI5NzYxZGVkYTVjMzFiYjllMzU1NzMyZTMzM2E5ODE5ZjY4ZWEyYzJjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.s4gObq69L6DHZm2iubJUCWL-hEZpVrDViIEYqLTBel8">

Hey @bizob2828, 

Thanks for your response.
I will try to understand if we are dropping some logs intentionally, it will probably be that. I will give feedback

**Comment by bizob2828** [comment]
@danimagb-moonfare I'm going to close this bug for now. If you can figure out a way to reproduce, please update your github repo and reopen this issue.
