### ISSUE TITLE
Convert Jade template to HTML

### ISSUE THREAD

**Issue by szaranger** [newrelic/node-newrelic#280]
Not everybody uses Jade. Please convert this to HTML

**Comment by astormnewrelic** [comment]
Nice to meet you you szaranger, and thanks for your feedback/attention!

That said -- we're not 100% sure what use of jade you're referring to.  The New Relic agent itself doesn't use jade for any functionality.  

If you're referring to our docs ([this](https://github.com/newrelic/node-newrelic#example)?  somewhere else?) -- the intent of that passage isn't to advocate or recommend jade -- jade just happens to be the library we chose to show _the general concept_.  Per those same docs.

> Although the specifics are different for other frameworks, the general approach described below should work in most cases.

In our experience a majority of **our** users are usually using some sort of templating engine, and it's important for our docs to reflect that.  

Do you have a suggestion for a better templating engine we could use as an example?  Or have you spotted other uses of jade in our docs?  Or have I completely misunderstood what your issue posting was about? :)

**Comment by szaranger** [comment]
I'm using NextJS and never used Jade/Pug so had to learn Jade to convert your example to HTML. So if the documentation had it in HTML, it will be useful for the users

**Comment by astormnewrelic** [comment]
@szaranger I see, thanks for sharing.  Do you have any suggestions for how we could write the docs in such a way that we cover, conceptually, both the HTML use case and the template engine use case?

**Comment by astormnewrelic** [comment]
@szaranger We're still open to hearing about solutions that cover the use cases we described.  If you're interested in coming back to this either open a PR, or reopen the issue to revive the discussion. Thanks! :)

**Comment by szaranger** [comment]
@astormnewrelic I guess it’s good to have both HTML and Jade examples. Handlebars templates for example use HTML
