### ISSUE TITLE
No longer works with NextJS 15

### ISSUE THREAD

**Issue by edwinveldhuizen** [newrelic/node-newrelic#2816]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

When updating to nextjs v15.0.3 we're getting the following error:
```
/usr/local/bin/node: --r= is not allowed in NODE_OPTIONS
```

Meaning
```
NODE_OPTIONS='-r newrelic' next start
```
no longer works

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Node version: 20.12.7

**Comment by jsumners-nr** [comment]
The quoted error message is showing two dashes preceding the `r`. Please use only a single dash: `-r`.

**Comment by edwinveldhuizen** [comment]
@jsumners-nr we’re using single -r, not sure why the error message acts like there is a double dash.

**Comment by jsumners-nr** [comment]
I'd recommend filing an issue with Next.js.

**Comment by bizob2828** [comment]
I'm closing this because it works just fine on 15.0.3 when providing 

```sh
NODE_OPTIONS='-r newrelic'
```

```sh
❯ npm start

> start
> NODE_OPTIONS='-r dotenv/config --loader newrelic/esm-loader.mjs -r newrelic' next start

(node:59710) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("newrelic/esm-loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
   ▲ Next.js 15.0.3
   - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 252ms

**Comment by giladrom** [comment]
You can use `NODE_OPTIONS='--require=newrelic'` and it'll work fine.

**Comment by MinSomai** [comment]
```
    "start": "cross-env NODE_OPTIONS=\"--require=dotenv/config --require=newrelic --no-deprecation --max-old-space-size=1536\" next start",
```

and `newrelic.cjs`

This is working for me in nextjs 15.
