### ISSUE TITLE
Node agent doesn't work with directus cms setup

### ISSUE THREAD

**Issue by coignite-user** [newrelic/node-newrelic#2832]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
We want to use the newrelic to get insight into our directus setup.
The current app is running in the docker.

Newrelic node agent setup was done by the book:
`npx directus bootstrap && node --experimental-loader newrelic/esm-loader.mjs -r newrelic scripts/start.js`

It seemed the agent was doing great
```
{
"v":0,
"level":30,
"name":"newrelic",
"hostname":"<our-hostname>",
"pid":41,
"time":"2024-12-11T10:32:22.919Z",
"msg":"Agent state changed from connected to started."
}
```

But then it crashed
```
file:///workspace/node_modules/node-machine-id/dist/index.js?iitm=true:23
       let $electron-machine-id = _.electron-machine-id
                    ^
 
SyntaxError: Unexpected token '-'
     at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:168:18)
     at callTranslator (node:internal/modules/esm/loader:279:14)
     at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:285:30)
```

I believe the error might be related to `import-in-the-middle` lib being unable to parse the `node-machine-id` correctly.

## Expected Behavior
Not to crash and start the app

## Steps to Reproduce
Setup directus and run `npx directus bootstrap && node --experimental-loader newrelic/esm-loader.mjs -r newrelic scripts/start.js`

Where start.js is 
```
import {config} from 'dotenv';
import {startServer} from '@directus/api/server';
config();
startServer();
```
## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Node: v21.7.3
* OS: 4.4.0 x86_64 GNU/Linux
* Directus: 11.3.2
* newrelic: 12.8.2
* import-in-the-middle: 1.11.3

**Comment by bizob2828** [comment]
I'm going to close this issue
