### ISSUE TITLE
Webpack cannot load newrelic npm package

### ISSUE THREAD

**Issue by artgoce** [newrelic/node-newrelic#285]

**Comment by michaelgoin** [comment]
Hi @artgoce ,

We have some known issues with Webpack, for sure. Some are currently unavoidable. Particularly, Webpack changes how dependencies are loaded which can break our instrumentation. We have some newer means of mitigating that, if it ends up being the issue. For example, to deal with module loading issues where a dependency is loaded prior to `newrelic` and doesn't get instrumented, we now have `instrumentLoadedModule()` on the API to allow us to inject our hooks after the fact. You can see more in [the docs](https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/nodejs-agent-api#custom-instrumentation-api). 

I haven't heard of any issues directly with New Relic failing to load at all. I do know some customers need to load us as an external and then manually set our dependency on the global.

This seems like the sort of thing that probably belongs as a support ticket, so our awesome support folks can help troubleshoot and extract information to narrow down the problem in collaboration with the dev team. Here's the best starting point: https://support.newrelic.com/

Thanks!

Michael
