### ISSUE TITLE
lib/config/default.js has bad defaults for proxy

### ISSUE THREAD

**Issue by jwineman** [newrelic/node-newrelic#294]
When installing the `newrelic` npm package we followed the instructions about setting up a `newrelic.js` file. 

In the comments of `newrelic.js` we saw:
```
/**
 * New Relic agent configuration.
 *
 * See lib/config/default.js in the agent distribution for a more complete
 * description of configuration variables and their potential values.
 */
```
which led us to use `lib/config/default.js` as our starting point for `newrelic.js` rather than the one at the root of the repository.  This led to the following issue when running `nrdiag`:
```
Failure - Base/Collector/ConnectUS
There was an error connecting to collector.newrelic.com (US Region)
Please check network and proxy settings and try again or see -help for more options.
Error = Get https://collector.newrelic.com/status/mongrel: proxyconnect tcp: dial tcp: lookup http on 192.168.1.1:53: no such host
See https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/networks for more information.
```

The root cause of this issue was `lib/config/default.js` setting `proxy`,`proxy_host`, `proxy_port`, `proxy_user`, and `proxy_pass` to `''` (empty string).
https://github.com/newrelic/node-newrelic/blob/master/lib/config/default.js#L66-L90

I assume the default value for these fields should be `null` instead of empty string?  I'm happy to PR this change if so.

**Comment by michaelgoin** [comment]
Hi @jwineman!

`default.js` is not meant to be copied / used outside of the agent itself. It is where we seed some standard defaults as well as account for all of the supported user-configurable settings.

The language pointing there was meant to indicate the items in there can be a reference for your own use inside of `newrelic.js` in the root of your directory.

I would start with the `newrelic.js` at the roof of the repository and then add/tweak whatever configuration you need from there. `default.js` can be a helpful reference for everything available and of course there's always the docs: https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration

As is, the `default.js` file is setup fine for its intended internal usage.

I'm going to close this out but we are happy to help if you have further issues.

Thanks!

Michael
