### ISSUE TITLE
Create a next.js example

### ISSUE THREAD

**Issue by lifeiscontent** [newrelic/node-newrelic#295]
I'd like to see a next.js example, since it's an SSR React app, there's not a clear way to inject the timing header.

**Comment by astormnewrelic** [comment]
Hey there @lifeiscontent, great to meet you!

Officially -- the agent doesn't formally support NextJS -- the best way to get official support would be via [support.newrelic.com](https://support.newrelic.com/) or [the Explorer's Hub forums](https://discuss.newrelic.com/). 

Unofficially though lets see what we can come up with :)

Looking over at [the NextJS docs](https://nextjs.org/), it looks like this is a framework that renders reacts components on the server, and then sends users HTML pages (like you said, an SSR (Server Side Rendered) framework).   

Given that, if you want to get [the _browser_ agent](https://docs.newrelic.com/docs/browser/new-relic-browser/installation/install-new-relic-browser-agent) added to these HTML pages your best bet is probably to _skip_ the node agent's [`getBrowserTimingHeader()`]((https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/nodejs-agent-api#other-api) method, and instead use [the browser's agent's Copy/Paste](https://docs.newrelic.com/docs/browser/new-relic-browser/installation/install-new-relic-browser-agent#copy-paste-app) method to add the right script tags to your document's `<head/>` section.  We're not super familiar with Next.js around here, but it looks like they have docs [on how to add stuff to the head section](https://nextjs.org/docs#populating-head) of your pages.  

If you want to use the Node Agent to instrument what your node process is doing while serving/building/etc NextJS pages, that's a little tricker.  Normally to [install the NodeJS agent](https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent) you need to add `require('newrelic')` to the top of your main entry point, or use the `node` executable's `-r` options to load the `newrelic` module before any other modules (i.e. `node -r newrelic`).

When I tried out NextJS's [getting started](https://nextjs.org/docs#quick-start) guide they put a lot of boilerplate between you and node.  

Starting NextJS means invoking a custom `next` command, not `node` itself.

    "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start"
    },
    
It looks like, **at this time** `next` is just a javascript CLI program

    cat node_modules/.bin/next
    #!/usr/bin/env node
    "use strict";var _index=_interopRequireDefault(...        
        
So you should be able to start your next JS program with the following         

    node -r newrelic node_modules/.bin/next dev
    node -r newrelic node_modules/.bin/next build
    node -r newrelic node_modules/.bin/next start

and have basic instrumentation. The [NextJS maintainers](https://github.com/zeit/next.js/) may also have some thoughts about the best way to slide `node` arguments into their system or customize the entry point.

Hope that gets you pointed in the right direction.  I'm going to close this issue out, but if you need further assistance, feels free to keep the conversation going here, or start up an [the Explorer's Hub thread](https://discuss.newrelic.com/).

**Comment by lifeiscontent** [comment]
@astormnewrelic thanks for the quick response, the issue is that React doesn't allow you to render just plain/text HTML tags, and thats exactly what `newrelic.getBrowserTimingHeader()` returns. In fact, you also can't render HTML Comments either in React, so thats kinda where I got stuck, any suggestions?

**Comment by astormnewrelic** [comment]
> any suggestions?

@lifeiscontent (hides jQuery and vue quickly behind back)  Huh, I did not know that about React.

Given that restriction, then no, it it not possible to use the `getBrowserTimingHeader` agent API method with React.  While we're getting a little far afield of the Node Agent and more into pure [browser agent](https://docs.newrelic.com/docs/browser/new-relic-browser/installation/install-new-relic-browser-agent) territory, here's two paths to persue

1. Does Next.js Allow you to modify the HTML template of the pages it renders?  If so, just insert the script tag there in the `<head>` section.

2. It looks like one common work around folks are using to get the browser agent into React is to [create a React component](https://github.com/jesse-weaver/new-relic-agent-react/blob/master/src/index.js#L13) for the brower agent's script tag.  I'd try something like that in your own project.

**Comment by lifeiscontent** [comment]
@astormnewrelic it does, but only as react components. 🤷‍♂

**Comment by lifeiscontent** [comment]
considering the amount of developers using react, I would assume this would be a surface area that New Relic should want to support though right?

**Comment by petvas** [comment]
This is how we integrated into our next js project:
**Server Side:**
1st step we created a server.js to add newrelic:
based on this: https://github.com/zeit/next.js/blob/canary/examples/custom-server-express/server.js#L24
```js
 server.get('*', (req, res) => handle(req, res));
```
We need to add newrelic here:
```js
    server.get('*', (req, res) => {
        const parsedUrl = parse(req.url, true)
        const { pathname, query } = parsedUrl
        // Transaction Name: (w/o this new relic shows "/*" for all transaction)
        // https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/guide-using-nodejs-agent-api
        console.log(`path ${pathname}`)
        newrelic.setTransactionName(pathname);

        return handle(req, res)
    });
```

**Client Side:**
create a new Browser project:
select "Pro + SPA" and Copy/Pase code, save the code into a text file
remove the script tags from the file and replace chars "/" with "//". (escape the escape characters)
create a new react Component `NewRelicSnippet .tsx`: and add the escaped script string into it.
```ts
// Copy-Paste code use Pro + SPA  on newrelic
const snippet = `
window.NREUM||...
`;

export const NewRelicSnippet = () => {
    return <script type="text/javascript" dangerouslySetInnerHTML={{ __html: snippet}} />
};
```
Add this component into: `_app.tsx` (or jsx)
``` js
        return (
            <>
                <Head>
                    <NewRelicSnippet />
                </Head>
                {/* ... */}
            </>
        )
```

**Comment by astormnewrelic** [comment]
neat!  thanks for sharing @petvas!

**Comment by QuantumTalent** [comment]
> This is how we integrated into our next js project:
> **Server Side:**
> 1st step we created a server.js to add newrelic:
> based on this: https://github.com/zeit/next.js/blob/canary/examples/custom-server-express/server.js#L24
> 
> ```js
>  server.get('*', (req, res) => handle(req, res));
> ```
> 
> We need to add newrelic here:
> 
> ```js
>     server.get('*', (req, res) => {
>         const parsedUrl = parse(req.url, true)
>         const { pathname, query } = parsedUrl
>         // Transaction Name: (w/o this new relic shows "/*" for all transaction)
>         // https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/guide-using-nodejs-agent-api
>         console.log(`path ${pathname}`)
>         newrelic.setTransactionName(pathname);
> 
>         return handle(req, res)
>     });
> ```
> 
> **Client Side:**
> create a new Browser project:
> select "Pro + SPA" and Copy/Pase code, save the code into a text file
> remove the script tags from the file and replace chars "/" with "//". (escape the escape characters)
> create a new react Component `NewRelicSnippet .tsx`: and add the escaped script string into it.
> 
> ```ts
> // Copy-Paste code use Pro + SPA  on newrelic
> const snippet = `
> window.NREUM||...
> `;
> 
> export const NewRelicSnippet = () => {
>     return <script type="text/javascript" dangerouslySetInnerHTML={{ __html: snippet}} />
> };
> ```
> 
> Add this component into: `_app.tsx` (or jsx)
> 
> ```js
>         return (
>             <>
>                 <Head>
>                     <NewRelicSnippet />
>                 </Head>
>                 {/* ... */}
>             </>
>         )
> ```

Hello @petvas, thanks you a lot for your response, but I think the replacing should be: "\" with "\\".

Nice work!!

**Comment by insivika** [comment]
Do you still add the `newrelic.js` to the root of your project as described in the set up process? 
![Screen Shot 2020-12-04 at 8 16 19 PM](https://user-images.githubusercontent.com/33808429/101233403-98556300-366d-11eb-947c-33231eda7448.png)

**Comment by insivika** [comment]
Super helpful, thank you @petvas

**Comment by kfaria** [comment]
Has anyone been able to setup the server side reporting without going the custom express server route?

**Comment by adri** [comment]
Great example @petvas!  I get an error in production. This error was also reported here  https://discuss.newrelic.com/t/cut-and-paste-js-error/138610
```js
Uncaught SyntaxError: Unexpected token ')'
```

When compiling this to production with webpack it seems like the code gets modified. Did anyone have this too and maybe found a fix for it?

**Comment by mehmetpekcan** [comment]
> Has anyone been able to setup the server side reporting without going the custom express server route?

Create a file called `newrelic.js` with below context

```
exports.config = {
  app_name: [process.env.NEW_RELIC_APP_NAME],
  license_key: process.env.NEW_RELIC_APP_KEY,
  logging: {
    level: "info",
  },
};
```

Then in your **next.config.js** (please create if you don't have see more [here](https://nextjs.org/docs/api-reference/next.config.js/introduction)) then inside your **next.config.js** write below code

```
if (process.env.NODE_ENV === "production") {
    require("newrelic");
}
```

When you do this two steps your all server configuration has been done. Also note that if you want to push your local env. data please remove process if above code.

**Comment by ka8725** [comment]
Hey @mehmetpekcan , thanks for sharing this!

I followed your steps and my SSR next.js app was successfully registered at Newrelic. But after some clicks around I see no data at the Newrelic board:

![Image 2021-12-13 at 23 47 17](https://user-images.githubusercontent.com/243846/145901357-4ab2cd1b-0e5f-482e-bb40-1e53933518d2.jpg)

Does your solution really have no additional configuration steps? Did you have the same experience? How to make it  showing data on the dashboard? Thanks!

**Comment by Sharan-rupeek** [comment]
> Set up APM tracing pylonboard/nextjs-pylonboard#3
<img width="119" alt="Screenshot 2022-05-18 at 11 01 53 PM" src="https://user-images.githubusercontent.com/71309686/169105960-f6da896e-4118-4761-b6b1-4e977bbcf03e.png">

@mehmetpekcan Without custom server, the transactions are grouped generally like this. How do we get actual pathnames in the transaction?

**Comment by Sharan-rupeek** [comment]
> > Has anyone been able to setup the server side reporting without going the custom express server route?
> 
> Create a file called `newrelic.js` with below context
> 
> ```
> exports.config = {
>   app_name: [process.env.NEW_RELIC_APP_NAME],
>   license_key: process.env.NEW_RELIC_APP_KEY,
>   logging: {
>     level: "info",
>   },
> };
> ```
> 
> Then in your **next.config.js** (please create if you don't have see more [here](https://nextjs.org/docs/api-reference/next.config.js/introduction)) then inside your **next.config.js** write below code
> 
> ```
> if (process.env.NODE_ENV === "production") {
>     require("newrelic");
> }
> ```
> 
> When you do this two steps your all server configuration has been done. Also note that if you want to push your local env. data please remove process if above code.

@mehmetpekcan Without custom server, the transactions are grouped generally like this. How do we get actual pathnames in the transaction?

<img width="119" alt="Screenshot 2022-05-18 at 11 01 53 PM" src="https://user-images.githubusercontent.com/71309686/169108863-361d0c59-2a2e-4bcd-b435-30b10b93c617.png">

**Comment by w3bdesign** [comment]
Check out https://github.com/newrelic/newrelic-node-nextjs

@lifeiscontent
