### ISSUE TITLE
Invalid type passed to the parameter customAttribute for newrelic.noticeError(...)

### ISSUE THREAD

**Issue by Jeffrey-Chang** [newrelic/node-newrelic#297]
Reading the documentation for the optional parameter, it says we should be passing an object with key/value pairs but when I do pass it an object, it omit's it saying `Omitting attribute data from noticeError call, type must be boolean, number, or string`. 

Looking through the source code (https://github.com/newrelic/node-newrelic/blob/master/lib/util/attribute-types.js), it would seem that you do not allow object's to be a valid type. I'm not sure if the documentation is wrong or if it is a bug.

**Comment by astormnewrelic** [comment]
@Jeffrey-Chang Nice to meet you!  Could you 

1. Point us towards which docs say _Reading the documentation for the optional parameter_?  We've got documentation all over the place and it's easy to loose track of these things

2. Send along a simple example of the `noticeError` call you're making that's causing this problem?

With that information we'll be better able to advise. Thanks!

**Comment by Jeffrey-Chang** [comment]
https://docs.newrelic.com/docs/browser/new-relic-browser/browser-agent-spa-api/notice-error
https://newrelic.github.io/node-newrelic/docs/API.html#noticeError

My code looks a little something like this
```
axios.post('http://the-url.com')
  .then(response => response.json())
  .catch(error => newrelic.noticeError('API_IS_BROKEN', error.response.data)
```

**Comment by astormnewrelic** [comment]
@Jeffrey-Chang OK, I think I see the disconnect. The `noticeError` method _will_ let you pass an object of key/value pairs in

    newrelic.noticeError(foo,{'foo':1})
    newrelic.noticeError(foo,{'foo':'bar'})
    newrelic.noticeError(foo,{'foo':true})

However, the attribute values of the object must be a number, string, or boolean.  I'm guessing your response object has nested objects and arrays off the top level, and that's why the agent information you it's not allowing those values.  

Does that sound right?  Or does that go against your understanding of the problem?

**Comment by Jeffrey-Chang** [comment]
@astormnewrelic Ahh. I see! I must have been confused by the wording a bit. You are right and changing it to that syntax has worked! Thanks!
