### ISSUE TITLE
TC-39 function implementation hiding proposal

### ISSUE THREAD

**Issue by ghermeto** [newrelic/node-newrelic#301]
Hi there! 👋

I would like to ask you to take a look at the [Function implementation hiding proposal on TC-39](https://github.com/tc39/proposal-function-implementation-hiding) which is currently on stage 2.

Your library seems to be relying on the `stack` property from the Error object in a few places ([1](https://github.com/newrelic/node-newrelic/blob/d17518834b0a51278d52eff93674d0b08ef6aa5f/test/helpers/unwritable-log/unwritable.js#L14), [2](https://github.com/newrelic/node-newrelic/blob/8bc36123871d7ea2ab30bf4093be25ba926a187f/lib/errors/index.js#L67), [3](https://github.com/newrelic/node-newrelic/blob/533ba20079e903205c397932cc08dec4fc8553a1/lib/sampler.js#L168), [4](https://github.com/newrelic/node-newrelic/blob/8bc36123871d7ea2ab30bf4093be25ba926a187f/lib/transaction/index.js#L144)) and I would like to understand better how this proposal might affect your product.

I have an [open ticket on the proposal](https://github.com/tc39/proposal-function-implementation-hiding/issues/25) and your insights would be appreciated.

**Comment by michaelgoin** [comment]
Hi @ghermeto,

Wanted to reach-out and acknowledge we've seen your request here. I can't guarantee timing of when we'll get to it, at this time. We appreciate you thinking of us.

Thanks,

Michael

**Comment by misterdjules** [comment]
@michaelgoin That proposal is scheduled to be presented for advancement to stage 3 the week of December 2nd 2019. If you have some concerns about its impact on observability of stack traces, now would be a good time to express them in those issues.

**Comment by michaelgoin** [comment]
Hi @ghermeto,

We don't believe this proposal would break anything for us.

Impacts will mostly be related to what end users see collected for errors occurring in their applications and logging in some circumstances. Since they would control this, it is not a major concern with regards to the agent.

I'll keep an eye on the proposal to ensure I am fully understanding the details correctly.

Thank you for reaching out!

Michael
