### ISSUE TITLE
Receiving TypeError for fatal exception handling

### ISSUE THREAD

**Issue by DullReferenceException** [newrelic/node-newrelic#302]
We started getting crashes of this nature with `newrelic@5.11.0`:

```
/src/node_modules/newrelic/lib/errors/helper.js:68
      !config.strip_exception_messages.enabled
                                       ^
TypeError: Cannot read property 'enabled' of undefined
    at Object.extractErrorInformation (/src/node_modules/newrelic/lib/errors/helper.js:68:40)
    at Object.shouldIgnoreError (/src/node_modules/newrelic/lib/errors/helper.js:100:26)
    at ErrorAggregator.collect (/src/node_modules/newrelic/lib/errors/aggregator.js:234:21)
    at ErrorAggregator.add (/src/node_modules/newrelic/lib/errors/aggregator.js:136:12)
    at process.wrappedFatalException [as _fatalException] (/src/node_modules/newrelic/lib/instrumentation/core/globals.js:20:22)
```

Is this a known issue?

**Comment by michaelgoin** [comment]
This is not a known issue.

When we've seen this sort of issue occur for other parts of our code, it is often when an application library will enumerate and delete properties off of objects. I'm not sure how one would grab a hold of our config but perhaps this is the case.

In `v5.13` we made a segment we add to the outbound request non-enumerable to try to avoid such issues. You might try this version and also confirm you don't have any libraries that will arbitrarily strip properties off of objects it encounters. I believe where we've seen this the most is grabbing information off of requests and serializing them into logs.

Beyond that, we'll prob have to do a bunch more information gathering.

If that becomes the case, this seems like the sort of thing that probably belongs as a support ticket, so our awesome support folks can help troubleshoot and extract information to narrow down the problem in collaboration with the dev team. Here's the best starting point: https://support.newrelic.com/

**Comment by michaelgoin** [comment]
Hi @DullReferenceException,

Thought I would check in and see if this is still an issue.

Thanks,

Michael

**Comment by DullReferenceException** [comment]
Can close this. It likely was caused by something that was using property stripping. We've had problems with this in the past (when serializing error objects that we want to limit output size for, and the stripping process touches newrelic-injections).

**Comment by michaelgoin** [comment]
OK. Thanks for the update!
