### ISSUE TITLE
Express + Apollo Server + Knex.js + MySQL =  not recording db trace

### ISSUE THREAD

**Issue by sponomarev** [newrelic/node-newrelic#303]
For some reason, MySQL instrumentation is not working when db query is invoked using async knex.js inside an Express + Apollo Server request. 

What I see in the trace log:

```
{"v":0,"level":10,"name":"newrelic","hostname":"ec72183679aa","pid":51,"time":"2019-09-30T00:25:09.060Z","msg":"Found and parsed query MySQL -> unknown/select","component":"DatastoreShim","module":"mysql","datastore":"MySQL"}
{"v":0,"level":20,"name":"newrelic","hostname":"ec72183679aa","pid":51,"time":"2019-09-30T00:25:09.060Z","msg":"Not recording function query, not in a transaction.","component":"DatastoreShim","module":"mysql","datastore":"MySQL"}
```

I guess that loosing transaction context is not a fault of Express + Apollo Server stack. If I start a new segment nearby, it's recorder properly. The same is with using mysql.js directly.

**Comment by sponomarev** [comment]
I guess it's relevant to https://discuss.newrelic.com/t/feature-idea-knex-support-in-nodejs-client/67212

**Comment by michaelgoin** [comment]
Hi @sponomarev! 

We've found both `knex` and `apollo` can cause transaction state loss. Unfortunately, this will only be resolvable by adding some instrumentation for each.

As always, we are open to feature requests (typically handled through support). I'm going to add a feature-request label to this, as well, so we can keep it open for others who may run into similar issues.

**Comment by rr0214** [comment]
You can now use this plugin for Apollo support: https://github.com/newrelic/newrelic-node-apollo-server-plugin. Give this a try with your environment.
