### ISSUE TITLE
Security vulnerability caused by https-proxy-agent

### ISSUE THREAD

**Issue by mastermatt** [newrelic/node-newrelic#304]
Last week a MitM vulnerability was publicly disclosed for one of the prod dependencies `https-proxy-agent`. 
https://hackerone.com/reports/541502

There is no published fix at this time, although there is a PR open. https://github.com/TooTallNate/node-https-proxy-agent/pull/76.

Short of removing the dep, there isn't much this lib is able to do. However, I'm opening this issue as a notice. 
The vulnerability is registered with [Snyk](https://snyk.io/vuln/SNYK-JS-HTTPSPROXYAGENT-469131) as a medium threat and my builds are now failing because we use the NR agent.

**Comment by astormnewrelic** [comment]
@mastermatt Thanks for the heads up -- we dropped into the PR thread to see if we can get Nate to let everyone know if he plans on fixing this or not: https://github.com/TooTallNate/node-https-proxy-agent/pull/76

In the meanwhile -- if you're not using the proxy features of the New Relic agent (which require explicit configuration) you should be unaffected by particular vulnerability (other than, of course, your build system and Snyk).  I'd also encourage you to [chime into the PR thread](https://github.com/TooTallNate/node-https-proxy-agent/pull/76) -- sometimes it takes a few folks being affected to get the attention of an open source maintainer. 

We intend to monitor the situation and, depending on Nate's response, take appropriate action. If there's anything else we can do in the meanwhile please let us know.

**Comment by kadler15** [comment]
@astormnewrelic Version 3.0.0 is out with a fix! [TooTallNate/node-https-proxy-agent#77](https://github.com/TooTallNate/node-https-proxy-agent/pull/77)

**Comment by astormnewrelic** [comment]
@kadler15 We know!  The system works!  We're still stuck with a "release internally, push to public GitHub workflow", but the new `http-proxy-agent` is coming ASAP.   Once we have the release out we'll update this ticket with the details.

**Comment by astormnewrelic** [comment]
@kadler15 @mastermatt Agent version 5.13.1 has hit the wires, and includes [the latest `http-proxy-agent`](https://github.com/newrelic/node-newrelic/blob/v5.13.1/package.json#L138), so we should be all good here. We're going to close this issue out, but don't hesitate to reopen/comment if there's more to say or do, and thanks again for bringing this to our attention!
