### ISSUE TITLE
How do I disable the automatic aws-sdk instrumentation?

### ISSUE THREAD

**Issue by simonrussell** [newrelic/node-newrelic#311]
The automatic inclusion of the `@newrelic/aws-sdk` package is causing problems:

```
TypeError: Cannot read property 'scan' of undefined
    at DocumentClient.wrapOperation (/opt/app/node_modules/@newrelic/aws-sdk/lib/dynamodb.js:59:62)
    at DocumentClient.opRecorder (/opt/app/node_modules/newrelic/lib/shim/datastore-shim.js:411:24)
    at DocumentClient.wrapper [as scan] (/opt/app/node_modules/newrelic/lib/shim/shim.js:927:33)
    at module.exports.Table.sendRequest (/opt/app/node_modules/vogels/lib/table.js:64:18)
    at module.exports.Table.runScan (/opt/app/node_modules/vogels/lib/table.js:451:8)\n    at runScan (/opt/app/node_modules/vogels/lib/scan.js:159:16)
    at doFunc (/opt/app/node_modules/vogels/lib/utils.js:79:5)
   .... etc
```

The library calling it is old, but without NewRelic inserting itself it works just fine.  I don't want this instrumentation anyway, how do I disable this?

This probably shouldn't have been put in a .1 release.

I think my fundamental request would be just remove the package as a dependency (also the koa one) and just recommend people install it if they want it.

**Comment by astormnewrelic** [comment]
@simonrussell Nice to meet you, even if it's not under the best of circumstances.  

First -- the quickest way to get support for the New Relic agent is through our formal support channels.  https://support.newrelic.com/  Using the formal support pipeline will get your ticket in front of the folks who are best equipped to deal with the fastest.  That said we're always happy to backchannel things informally via Github -- we just can't guarantee when our time/attention will be on the issue. 

For what it's worth, the decision to fold this instrumentation into the agent wasn't made lightly -- like a lot of folks in the javascript ecosystem we're always trying to find the right balance when moving the platform forward.  I also know that doesn't help when you're caught by a bug. 

Re:

> how do I disable this?

At this time there's no official way to disable an instrumentation that's built-in to the agent. 

If this is critical we'd recommend temporarily rolling back to the previous agent version.

Out of curiosity, what's the old version of the AWS SDK that you're using?  If we have the version and can reproduce the issue locally we may be help to help you with a work around.

**Comment by simonrussell** [comment]
Thanks for the quick reply.  I think the dependency is on `aws-sdk` 2.2.x, so pretty old.  That said, it's not broken and we don't have time to rewrite the app to not use the library with the old dependency.

I think definitely there needs to be a way to disable major features that could cause issues like this; I've already rolled back to the previous version, but this definitely should have been in a major version bump.  I'm now basically stuck on a previous version because of a feature I'm not using.

It would seem pretty easy to add a feature to disable these things.  You should also potentially add a peerDependency on `aws-sdk` with a version restriction; but even better would be to make the aws-sdk instrumentation an optionalDepdendency.

(incidentally GitHub is probably the best place to be tracking bugs like this in your open source tools, so other people can see the issue, etc.)

**Comment by astormnewrelic** [comment]
@simonrussel We've taken a look at this using the 2015/2016 era 2.2.x version of the Amazon SDK and were able to reproduce the problem.  We have a potential fix in flight 

> https://github.com/newrelic/node-newrelic-aws-sdk/pull/24/

If you want to give that branch/PR a try and let us know if it fixes your issues we'd love the feedback.

Re: your feature request to be able to remove instrumentations you're not using, I've passed that on to the product teams.  I'm not in a position to promise anything, but I do know you're not the only one to ask for that. 

Re: tracking issues here in GitHub -- I hear you on that one.  As New Relic moves from our current "Source Available" projects that we publish on GitHub to more fully open source projects we'll probably be doing more issue management on GitHub -- that said our support team is still the best way to guarantee your issue gets in front of the right eyes in a timely manner  https://support.newrelic.com/

Sorry again that you got caught up in this bug -- if you can let us know whether the PR fixes your issue or not that'd be a big help in getting it landed and getting you back on the regular update train.

**Comment by simonrussell** [comment]
Hi there, yes that branch seems to fix the issue.  Thanks for looking into it.  I'll look out for a 6.1.1 or 6.2.0 release :)

It's definitely an ancient version of the SDK, but unfortunately it keeps working for us and the production system it's used in doesn't have any other reason to spend the time to rewrite that chunk. :)

**Comment by simonrussell** [comment]
This is fixed in the most recent releases.
