### ISSUE TITLE
Support http/https APIs for node >= 10

### ISSUE THREAD

**Issue by kennethaasan** [newrelic/node-newrelic#316]
Related issue: https://github.com/sindresorhus/got/issues/876

Seems like https://github.com/newrelic/node-newrelic/blob/master/lib/instrumentation/core/http.js#L447-L451 breaks requests. 

Also seems like the dependency _node-agent-base_ that you have through _https-proxy-agent_ doesn't support http/https APIs for node >= 10: https://github.com/TooTallNate/node-agent-base/issues/29

**Comment by astormnewrelic** [comment]
@kennethaasan Nice to meet you, thanks for the bug report.  

First, some official business: The best way to get support for the Node Agent is via our official support channels: https://support.newrelic.com/ -- reporting things via the official channels will ensure your issue gets in front the folks best situated to give you immediate help _and_ make sure the issues routed properly through our org. 

With that out of the way -- do you have some sample code/agent-configuration that shows how things break?  I took a look at the links you provided and there's enough extra parties involved that I'm not 100% clear what the problem you're describing is.  If you could provide a small program that demonstrates how things breaks we'll be in a much better position to help out.

**Comment by kennethaasan** [comment]
@astormnewrelic Thanks, I made a support ticket now.

I made a PR to fix this in https://github.com/newrelic/node-newrelic/pull/317

**Comment by astormnewrelic** [comment]
@kennethaasan 

> do you have some sample code/agent-configuration that shows how things break? 

Would you be able to provide the above so we can better understanding the issue you're facing?

**Comment by kennethaasan** [comment]
@astormnewrelic, 

The error message I get is _TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object_.

The NR agent config I use is:
```js
process.env.NEW_RELIC_NO_CONFIG_FILE = 'true';
process.env.NEW_RELIC_DISTRIBUTED_TRACING_ENABLED = 'true';
process.env.NEW_RELIC_LOG_ENABLED = 'false';
process.env.NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERROR_CODES = '400';
import 'newrelic';
```

The error happens when I use got v10 (https://github.com/sindresorhus/got) to request JSON feeds:
```ts
const agent = new https.Agent({
  keepAlive: true,
  maxSockets: 50,
  maxFreeSockets: 50,
})

export async function gotGet<V extends object>(
  url: string
): Promise<Response<V>> {
  const newrelicHeader = newrelic
    .getTransaction()
    .createDistributedTracePayload()
    .httpSafe();

  return got.get<V>(url, {
    agent,
    headers: {
      'user-agent': 'Sportradar Graph',
      newrelic: newrelicHeader,
    },
    timeout: 10000,
    followRedirect: true,
    retry: 3,
    responseType: 'json',
  });
}
```

**Comment by kennethaasan** [comment]
I made a sample app to show the problem: https://github.com/kennethaasan/node-newrelic-bug
It happens using both _got_ and _https.request_.

**Comment by michaelgoin** [comment]
Hi @kennethaasan,

Thank you for all of your hard work making the issue clear. 

We definitely have an issue with the `http.request(url, options, callback)` signature. I also think we may introduce some issues in the older signature when `options` is a proper `URL` object, but I haven't manually confirmed that.

I've created an internal bug to track this on our end more-closely. For our reference: NODE-2242.

Looking through things, it seems there are several permutations we want to ensure we get right with both signatures. The public PR is definitely on the right track. If you want to keep iterating on your PR, we are happy to help provide guidance and review. If not, totally understandable. It may be involved. Either way, you've set us up for success.

I can't guarantee timing of when we'll get a fix out. Given it crashes, it will be higher priority bug.

Thank you,

Michael

**Comment by kennethaasan** [comment]
Hi @michaelgoin ,

Thanks for the follow-up!

I'd love to finish my PR, but I'll have to dig into the whole codebase to understand why some of the tests break. Feel free to take over from where I left. When I have time to finish it, I'll give you an update here.

**Comment by kennethaasan** [comment]
I have some time to look at it today.

Looks like nock needs an update to v11 make tests pass: https://github.com/nock/nock/releases/tag/v11.3.2
> Add support for the http.request signatures added in Node 10.9

**Comment by kennethaasan** [comment]
@michaelgoin, this turns out to be a complex issue. Nock, a lib you use for testing is also breaking the Node API: https://github.com/nock/nock/pull/1588
_http.get_ calls _http.request_, which is causing the tests to fail because _wrapRequest_ is then called twice on 1 request. They claim they have fixed it, but their fix is not working for this library because of that reason. A temporary solution might be to not add the shim on _http.get_ when running tests until Nock has fixed this.

Also looks like _https-proxy-agent_ has released a new version that doesn't overwrite the Node API anymore, which is good!

Can the NR team take over this and prioritize it? This is blocking upgrades of open source software that are using this Node API.

**Comment by kennethaasan** [comment]
https://github.com/nock/nock/pull/1837 will fix the integration tests.

**Comment by pcwiek** [comment]
I'm just chiming in for 'visibility' - we're also waiting for a new release of the agent with this fix in place.

**Comment by kennethaasan** [comment]
@pcwiek, https://github.com/newrelic/node-newrelic/pull/318 is "ready" to be merged IMO, but the unit tests are breaking because of the nock issue above.

**Comment by nrcmkoh** [comment]
Any update on this?

**Comment by michaelgoin** [comment]
Hi @nrcmkoh,

We are hoping to put dedicated focus on getting this resolved/wrapped-up right after we finish our current effort. That probably puts it a few releases out but likely not very far out time-wise. We might get to put some focus on it prior to then, but that is what I can more confidently communicate. We'll update the issue and PR as that progresses.

Thank you,

Michael

**Comment by kennethaasan** [comment]
https://github.com/nock/nock/pull/1837 is ready to be revied and merged. Hopefully, that happens soon so that I can continue with #318

**Comment by jrnelson90** [comment]
I am currently also seeing an issue using `got` 10.3.0 with `newrelic` 6.3.0 due to the dependency on ` https-proxy-agent@3.0.1', which causes a dependency on 'agent-base@4.0.3`. All `got` versions 10+ need `agent-base` 5+.

I have to choose between having metrics or being able to just make HTTP requests at the moment.

**Comment by jrnelson90** [comment]
I have also been able to locally change the `package.json` of `newrelic` within `node-modules` to depend on `https-proxy-agent@4.0.0`, and I was able to run my `mocha` tests that depend on `got` 10.3.0 and `newrelic` 6.3.0. However, I am not certain how stable a solution this is without further inspecting this codebase.

**Comment by mike-dazn** [comment]
We're also seeing issues with `got` 10.3.0 and the newrelic agent (both directly, and via the newrelic lambda layer).  I've raised a support ticket on our side with newrelic referencing this issue to hopefully help get it moving.

**Comment by carlonewrelic** [comment]
Thank you for putting the support ticket @mike-dazn.  We are still in the middle of our current effort in updating the agent.  Hopefully we can get to this soon.

**Comment by paulmelnikow** [comment]
@kennethaasan, @michaelgoin, or others, the ecosystem impact has just come to my attention. I'd like to get this patched in Nock in the next day or so.

I need a bit of help to understand clearly what is the undesirable behavior in Nock w.r.t. New Relic's overriding of `http.request`. See my question at https://github.com/nock/nock/issues/1836#issuecomment-582096922. Thanks!

**Comment by kennethaasan** [comment]
@michaelgoin,

My PR is ready for review: https://github.com/newrelic/node-newrelic/pull/318

The nock issue is fixed. All the tests except the versioned tests pass. But they seem to break on master as well, so not sure if I should care?

**Comment by michaelgoin** [comment]
Thanks @kennethaasan, we plan to take a look at this soon. Not sure what is up with the public versioned tests. With our current setup, we have to pull things down to our private repo before shipping so we'll ensure the tests are in a good spot.

**Comment by maximilian-krauss** [comment]
Hi, 
how is the progress on new relic side regarding this issue? We are blocked since the very beginning of this issue here and can't use the node integration in most of our services unfortunately 😐

Do you have an estimation when we can see this fix going into the official release?

Thanks in advance, cheers,
Max

**Comment by astormnewrelic** [comment]
Thanks for checking in @maximilian-krauss -- Last week [we released version 6.4.2 of the node agent](https://www.npmjs.com/package/newrelic).  This release incorporates this PR, as well as expanding it to cover most (hopefully all?) possible combinations of arguments for the http functions.  (to preempt the obvious question -- we don't have a good public github/internal release pipeline setup yet so this PR remains unmerged -- we're _are_ working on it)

Could you give this latest release a try and let us know if it solves your problems?  If not, could you share an isolated example of an HTTP request (or other code) that breaks things?  We've added [significant test coverage](https://github.com/newrelic/node-newrelic/blob/master/test/unit/instrumentation/http/outbound.test.js) to ensure we test every message signature, but it's possible we've missed one.   An isolated reproduction case is the most actionable piece of feedback we can get.

**Comment by kennethaasan** [comment]
Thanks! I just deployed the new version of NR together with upgrading got. So far I don't see any issues, so for me we can close this ticket.

**Comment by nijotz** [comment]
Excellent! Sounds great, thank you so much for your help with this issue
