### ISSUE TITLE
Newrelic for nuxtjs

### ISSUE THREAD

**Issue by akagamina** [newrelic/node-newrelic#319]
Hello,

I want to use newrelic with nuxtjs, but i didnt see any helpfull source. Some people said you can do with express but i dont want use express.

there is a npm package for nextjs but nuxt sourceless :(

How can i use newrelic with nuxtjs?

**Comment by michaelgoin** [comment]
Hi @akagamina,

We haven't officially invested in supporting `nuxtjs`. While often our base instrumentation will work well, at least to see something, there is a high chance we may not notice/capture anything yet for `nuxtjs`. As far as usage in general, requiring `newrelic` as the very first module in your app will result in the agent instrumenting anything it does support.

While the framework may not be tracked by the agent, you should still be able to leverage it to take advantage of the browser agent, if that is desired. `newrelic.getBrowserTimingHeader()` can be used to get the necessary JS to insert into your headers.

> Returns the HTML snippet to be inserted into the header of HTML pages to enable New Relic Browser. The HTML will instruct the browser to fetch a small JavaScript file and start the page timer.

```
const newrelic = require('newrelic')

const browserHeader = newrelic.getBrowserTimingHeader()
```

Let us know if you'd like us to add `nuxtjs` as a feature request.

Thank you,

Michael

**Comment by aayushgoyal** [comment]
Hi @michaelgoin 

I would be great if there is at least some documentation regarding adding newrelic to nuxtjs application

**Comment by akagamina** [comment]
@aayushgoyal i agree with you. 

@michaelgoin we need a documentation as a nuxt developers. 

My company using newrelic other projects. Nuxt is a new project but we cant see server side. It would be great for us :) 

Thank you

**Comment by astormnewrelic** [comment]
@aayushgoyal  @akagamina Thanks both for the feature request.  We've got a note logged internally. That said if you both had a spare moment would you mind submitting a feature request via our forums? https://discuss.newrelic.com/c/feature-ideas.  Submitting a feature request via that channel will make sure the right people see it.

Also -- Re: using NuxtJS and the Node Agent -- if you're using [Express, Koa, or Hapi](https://nuxtjs.org/guide/installation#using-code-create-nuxt-app-code-) as your server side framework that _should_ get you server side metrics.  If you're using one of those frameworks and you're not seeing information that sounds like a bug we'd like to fix.  If you're using a _different_ framework we'd love to hear about in your feature request (and _why_ you're using a framework, if applicable)

**Comment by aayushgoyal** [comment]
@astormnewrelic Thanks for reply. 

I have added a [feature request](https://discuss.newrelic.com/t/documentation-support-for-adding-new-relic-on-nuxtjs-application/92234?u=aayush.goyal) on forum. 

New Relic is working partially for server side metrics in Nuxt.js (throwing "**Some modules were uninstrumented during the current time window: connect. Make sure require('newrelic'); is the first line of the application's main module.**" error) but it is unable to provided browser metrics.

 As a workaround, I separately added browser script on html page to get the browser metrice.

**Comment by astormnewrelic** [comment]
Thanks!  We're glad that adding the browser script directly got you the metrics you need here.  The workarounds posted in this issue seem to have folks covered for now and a feature request had been opened.  We're going to close this issue out for now.

**Comment by asaloff** [comment]
For anyone else running into this that wants New Relic running on the server and the client, you can do the following:

1. Add `require('newrelic')` at the very top of `nuxt.config.js`
2. Add a `new-relic.js` plugin to the plugins directory. It should look something like this:

```
const fs = require('fs');
const newrelic = require('newrelic');
const browserHeader = newrelic.getBrowserTimingHeader();

const isProd = process.env.NODE_ENV === 'production';
const appDir = process.cwd();
const staticJsDir = `${appDir}${isProd ? '/.nuxt' : '/static'}/js`;

const cleanedHeader = browserHeader.replace(/<\/?script?[^>]+>/gm, ''); // Removes script tags

export default () => {
  if (!fs.existsSync(staticJsDir)) {
    fs.mkdirSync(staticJsDir);
  }
  fs.writeFileSync(`${staticJsDir}/new-relic.js`, cleanedHeader, 'utf-8');
};
```

3. Use this plugin as a server only plugin in `nuxt.config.js` like this (Make sure it's the first one if you have other plugins too):

```
  plugins: [
    { src: '~/plugins/new-relic', mode: 'server' }
  ]
```

4. Lastly, add the script tag to the HTML docs header in `nuxt.config.js`:

```
  head: {
    script: [
      { src: '/js/new-relic.js' }
    ]
  },
```

**Comment by rkbodenner** [comment]
FYI there's an example of how to instrument the front-end/browser side of a Nuxt.js app here: https://github.com/nuxt/nuxt.js/issues/7960
