### ISSUE TITLE
OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by adityasabnis** [newrelic/node-newrelic#322]
Getting,
`OutgoingMessage.prototype._headers is deprecated` warning

Node_Doc:
https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames

![image](https://user-images.githubusercontent.com/3688957/72112013-85b8a800-3390-11ea-8ebc-3ac27c037ff7.png)

We are using:
  **Node: 12.14.0
  NewRelic: 6.1.0**

After a quick lookup, I guess it might be related to following blocks:

https://github.com/newrelic/node-newrelic/blob/0113eb5f0e707dc662a17d262a841503bab88841/lib/instrumentation/core/http.js#L375

or

https://github.com/newrelic/node-newrelic/blob/0113eb5f0e707dc662a17d262a841503bab88841/lib/instrumentation/core/http.js#L214

**Comment by michaelgoin** [comment]
Hi @adityasabnis,

Thank you for letting us know. We'll definitely want to make sure we don't break when this is fully gone. That being said, we may or may not need to keep using for backwards compatibility. We will take a look. Our deprecation schedule is a bit more aggressive these days, so hopefully we can get this annoyance out of the way sooner than later.

Thanks,

Michael

**Comment by fukayatsu** [comment]
> https://github.com/newrelic/node-newrelic/releases/tag/v6.0.0
> The minimum supported version is now Node v8. 
> 
> * **BREAKING** Removed support for Node 6, 7, and 9.
> 
>  The minimum supported version is now Node v8. For further information on our
  support policy, see:
  https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.

It seems `response._headers` fallback is not needed now.

**Comment by michaelgoin** [comment]
Hi adityasabnis and @fukayatsu ,

This should be resolved with the most recent release.
