### ISSUE TITLE
Frequent logging from base_aggregator component

### ISSUE THREAD

**Issue by louh** [newrelic/node-newrelic#324]
Hi, I'm running an app on Heroku, and every five seconds we're getting this in our logs:

```
Jan 10 10:18:46 streetmix-staging app/web.1: {"v":0,"level":30,"name":"newrelic","hostname":"574a985e-0269-419b-b6fd-8421dde485a4","pid":18,"time":"2020-01-10T18:18:46.314Z","msg":"error_event_data Aggregator data send.","component":"base_aggregator"}
Jan 10 10:18:46 streetmix-staging app/web.1: {"v":0,"level":30,"name":"newrelic","hostname":"574a985e-0269-419b-b6fd-8421dde485a4","pid":18,"time":"2020-01-10T18:18:46.316Z","msg":"analytic_event_data Aggregator data send.","component":"base_aggregator"}
Jan 10 10:18:46 streetmix-staging app/web.1: {"v":0,"level":30,"name":"newrelic","hostname":"574a985e-0269-419b-b6fd-8421dde485a4","pid":18,"time":"2020-01-10T18:18:46.316Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"
```

I'm posting this here because "newrelic" is being identified (and we do use this package). But I'm not sure what this `base_aggregator` component is, what it's trying to do, and why it's generating these messages. While our application seems to be running just fine, this is really disruptive to our logs. Any thoughts? Thanks!

**Comment by michaelgoin** [comment]
Hi @louh,

This is our agent new relic logging indicating when certain types of data have been sent to our server, logging at "info" level. While this was previously helpful diagnosing potential issues when they occurred, we realize this is getting a bit too verbose and have been considering reducing log level.

That being said, I'm not sure why it is showing up in your Heroku logs. One possibility is your agent logging has been configured to write to `stdout` and that is what Heroku watches? 

Thanks,

Michael

**Comment by louh** [comment]
Yes, the logging is configured to write to `stdout`, and to be specific, Heroku itself is not watching this, but rather its Papertrail addon.

So this is good that this isn't an issue with newrelic itself but it's just being very verbose. I think we have two options on our end:

1. We can configure Papertrail to drop/filter anything that matches this output from the logs
2. We can try setting NEW_RELIC_LOG_LEVEL to "warn" (but I suppose this will drop all other "info" messages).

What would you recommend?

**Comment by michaelgoin** [comment]
@louh, "warn" level is probably the easiest for you. We unfortunately don't log a lot of valuable info at "info" level, so chance of negative impact is super low. Most things we need for researching issues are at the "trace" level.

That being said, that *could* change in the future. So the other approach might be more future proof so you don't have to remember to set back with a future release.

**Comment by louh** [comment]
@michaelgoin We'll set our log level to "warn" for now. Thanks for the advice!

**Comment by michaelgoin** [comment]
@louh just a heads up this logging has been reduced to "debug" level in the most recent agent version, so "info" level in your logs should work fine now.

**Comment by gask** [comment]
@michaelgoin just a review here, I'm at new relic@5.13.1 using heroku and setting our log level to "info" didn't work, the base_aggregator spam was still going on... I had to set the log level to "warn" for the spamming to stop.

**Comment by michaelgoin** [comment]
@gask That checks out. The most recent version as of Feb 20, 2020 was 6.4.1: https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-641. The current most recent version is 7.1.0.
