### ISSUE TITLE
Significant increase in logging

### ISSUE THREAD

**Issue by daveisfera** [newrelic/node-newrelic#325]
Related to #324, we updated from 5.11 to 6.2 and there's a lot of the following logs (and then 4 other message that are happening a lot but about 1/10 as much):
```
analytic_event_data Aggregator data send.
custom_event_data Aggregator data send.
error_event_data Aggregator data send.
```

Can it be reduced, because the recommended solution of changing log level to warn disables a lot of other useful logs (like the startup messages)?

**Comment by yigaldviri** [comment]
Any news on that?

**Comment by michaelgoin** [comment]
We haven't resolved this yet but hoping to soon.

**Comment by michaelgoin** [comment]
@daveisfera @yigaldviri 

The most recent version of the agent now logs these at "debug" level. You should see a decrease in "info" level logs now.

**Comment by daveisfera** [comment]
thanks
