### ISSUE TITLE
Compatibility with yarn 2

### ISSUE THREAD

**Issue by daveisfera** [newrelic/node-newrelic#326]
Currently, the `newrelic.js` file has to be copied from `node_modules`, but with yarn 2, there is [no more `node_modules`](https://yarnpkg.com/features/pnp), so making it so things can be configured without the file and just with environment variables, would be good.

**Comment by michaelgoin** [comment]
Hi @daveisfera,

We do have the ability to use ENV only configuration. Not all config items are covered but most are.

The way to get away from needing a `newrelic.js` file is to set `NEW_RELIC_NO_CONFIG_FILE=true` in your ENV. While this item is on our configuration docs page, I see it is down in a special section and not up where it would be more visible/helpful so I'll make a note to try to surface that up better. Here's its description: https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#logging_config. The "avoid" language is also probably a bit strong at this point given it is normal for docker and such setups.

Where they exist, you should be able to find the ENV var equivalent next to the configuration items here: https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration. Hopefully, we haven't missed keeping anything up to date.

Hope that helps!

Michael

**Comment by michaelgoin** [comment]
May also be worth noting that the `newrelic.js` config template can always be copied directly from the root of this repository as well.

**Comment by daveisfera** [comment]
Good to hear that the file can be avoided, but copying the file one time could potentially be problematic if the file ever changed and that's why we had been copying it from `node_modules`

**Comment by michaelgoin** [comment]
Closing this out as we already supported the request but please let us know if you have any other yarn 2 issues.

Thanks!
