### ISSUE TITLE
Node 14 Support

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#329]
This issue will serve as a place to add any discovered issues/incompatibilities with Node14 (once released) prior to official support for Node 14. Please keep in mind we do not officially support odd-numbered releases. 

It should help inform if there are any risks too large to take on in your own project and will also help inform our official support as we tackle that.

For our official support policy, please see: https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent#version

**Comment by paul-pro** [comment]
Hello! Any activity in this direction? Maybe support date announcements?

**Comment by michaelgoin** [comment]
Hi @paul-pro,

No immediate activity here. Based on current priorities (always subject to change) I'm guessing we'll add official support closer to the end of our promised window in the link above (closer to LTS start date).

If you are feeling more adventurous, we don't have the 14 engine restricted so you can test out if you wish. So far we've had one 14 specific issue reported and PR'd on the native metrics side but no comments here or PR's on the main agent side, yet.

**Comment by harrykimpel** [comment]
Hi team, any updates on this?

**Comment by rr0214** [comment]
Hi @harrykimpel. We are committed to supporting Node 14 and are targeting completion by end of October.  I would love to know if there are specific parts of Node 14 that you are particularly looking forward to having supported.

**Comment by harrykimpel** [comment]
Hi @rr0214, just generic support for v14. Most of the applications in scope run v14 already. Thanks!

**Comment by nijotz** [comment]
Starting work to support v14 now: https://github.com/newrelic/node-newrelic/projects/5

**Comment by nijotz** [comment]
Closing in favor of #483
