### ISSUE TITLE
Event handlers not cleaned up for child process

### ISSUE THREAD

**Issue by DullReferenceException** [newrelic/node-newrelic#333]
Child process event listeners are not being cleaned up when using `newrelic`.

Scenario: I have a pool of `child_process` workers. When an inbound request is processed, I claim a worker and attach a listener thusly:

```js
child.once('message', messageHandler);
```

When `newrelic` is disabled, and I add logging of `child._events.message` inside of `messageHandler`, it shows that the message handler was properly cleaned up. However, if `newrelic` is enabled, the message listener is not removed. The next time the `child.once` command is run, there is now an array of two handlers. Eventually the process retains so much memory that it has to be killed.

Additional info:

* It doesn't make a difference if using `child.on('message', messageHandler)` is used and the handler is manually removed with `child.removeListener('message', messageHandler);` that line fails to manually remove the handler.
* `child.removeAllListeners('message');` does function as a workaround.

Versions:
- `node`: 12.16.1
- `newrelic`: 6.4.2

**Comment by michaelgoin** [comment]
Thank you for letting us know. I'll try to generate a repro of this soon and then get back to you if I have more questions.

**Comment by michaelgoin** [comment]
I've been able to repro. Will keep you posted on timing.

Thanks!

**Comment by michaelgoin** [comment]
This issue should be resolved with the next release.
