### ISSUE TITLE
Issue with Websockets - Cannot redefine property: __NR_segment 

### ISSUE THREAD

**Issue by EntropyAu** [newrelic/node-newrelic#335]
Hi - I'm unable to connect to a puppeteer service on Node (version 12.16.1) while the node-newrelic agent (version 6.5.0) is active - the request fails with the following stacktrace: 

`
TypeError: Cannot redefine property: __NR_segment
    at Function.defineProperty (<anonymous>)
    at instrumentRequest (/Volumes/Development/xxxx/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:129:12)
    at wrapped (/Volumes/Development/xxxx/node_modules/newrelic/lib/transaction/tracer/index.js:188:22)
    at Tracer.addSegment (/Volumes/Development/xxxx/node_modules/newrelic/lib/transaction/tracer/index.js:83:48)
    at instrumentOutbound (/Volumes/Development/xxxx/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:75:23)
    at wrappedRequest (/Volumes/Development/xxxx/node_modules/newrelic/lib/instrumentation/core/http.js:476:12)
    at initAsClient (/Volumes/Development/xxxx/node_modules/puppeteer/node_modules/ws/lib/websocket.js:555:31)
    at new WebSocket (/Volumes/Development/xxxx/node_modules/puppeteer/node_modules/ws/lib/websocket.js:70:7)
 `

Appreciate any ideas or guidance!

**Comment by astormnewrelic** [comment]
Nice to meet you @EntropyAu.  Apologies for the delay, this isn't (at the moment) a support channel we monitor 24/7 and the world's been -- _gesticulates wildly_ -- bananas lately.  If you need the sort of timely support that's tied to things like an SLA, your best bet is to [route that request through our support channels](https://support.newrelic.com/). Its the best way to get an issue in front of the right people as fast as possible. 

That said -- `__NR_segment` is a property the agent will set on objects as part of its instrumentation.  The error you're describing makes it sounds like something in your system (maybe typescript, maybe ES6 modules, maybe something else) is making an object immutable, and that's blocking the property from being added. 

Is this the sort of things where you could come up with an easy to reproduce error case for us?  We don't have anyone around right now with puppeteer experience, so while we know _I'm unable to connect to a puppeteer service _ describes the problem well to you/your-team, we'd need a little more to go on if we wanted to reproduce the problem and advise your further.

**Comment by gnavalesi-navent** [comment]
Same thing happening here. I'm trying to add the newrelic node agent to a modified version of Prerender, and the agent is failing when the PreRender server does a DNS lookup to find the Chrome host.

A horrible fix but that is working is the following:
```
if(process.env.NEW_RELIC_ENABLED || false) {
	const or = Object.defineProperty
	Object.defineProperty = (o, p, attributes) => {
		if(o.hasOwnProperty(p) && !Object.getOwnPropertyDescriptor(o, p).configurable) {
			console.log("dude.. that is already defined and cant write on that")
		} else {
			or(o, p, attributes)
		}

		return o
	}

	require('newrelic');
}
```

**Comment by astormnewrelic** [comment]
@gnavalesi-navent Thanks for the heads up!  If it's a top of your head/mind sort of thing, do you have a minimal code/invocation example that reproduces the behavior you're seeing? With that in hand we'll be able to get to the bottom of why this is happening and see what we can do about a less horrible fix (or maybe just hiding the horriblness a layer or two deep, where it belongs)

**Comment by astormnewrelic** [comment]
Thank you @gnavalesi-navent -- I've stolen a bit of time to work on this this week -- your reproduction output the following messages

> @google-cloud/trace-agent ERROR TraceWriter#initialize: Unable to acquire the project number automatically from the GCP metadata service. Please provide a valid project ID as environmental variable GCLOUD_PROJECT, or as config.projectId passed to start. Original error: Error: Unable to detect a Project Id in the current environment. 

> @google-cloud/trace-agent ERROR StackdriverTracer#start: Disabling the Trace Agent for the following reason: Unable to detect a Project Id in the current environment. 

It sounds like it wants/needs to GCP project to run against. I'll be looking into wrangling that (I'm more a Linode person), but if you know a way to invoke the Google trace agent without one it'd help speed things up.

**Comment by gnavalesi-navent** [comment]
@astormnewrelic Sorry for the delay. If you try with GOOGLE_CLOUD_TRACE_ENABLED=false it should start the tracer but don't send any trace to Google Cloud. Could you try that?

**Comment by rr0214** [comment]
If this is still an issue, we recommend reaching out to New Relic support.
