### ISSUE TITLE
Support for Fastify

### ISSUE THREAD

**Issue by simoneb** [newrelic/node-newrelic#336]
It doesn't look like fastify is supported. Can you please add support for it?

https://www.fastify.io/

**Comment by astormnewrelic** [comment]
Nice to meet you @simoneb.  Appologies for the delay, but this isn't (at the moment) an _official_ support channel -- if you need the sort of timely support that's tied to things like an SLA your best bet is to [route that request through our support channels](https://support.newrelic.com/). Its the best way to get an issue in front of the right people as fast as possible. 

Fastify is on our radar (how could it not be? ;)), but it's not on our immediate roadmap.  The best way to change this is to submit a feature request via [New Relic's explorer hub](https://discuss.newrelic.com/c/feature-ideas) or [to open a support ticket](https://support.newrelic.com/). People _do_ read these and customer need is heavily weighed when we're making roadmap decisions -- so if you want fastify support, submit an FR.  If you have _clients_ who want it, have them submit an FR as well. 

Also -- if you (or others at at NearForm) were interested in adding that support yourself we're open to PRs along those lines.  Our docs for this aren't  (at the moment) great -- but my contact info [is on my GitHub profile](https://github.com/astormnewrelic) -- if you're interested say hello.

**Comment by simoneb** [comment]
thank you @astormnewrelic  /cc @mcollina

**Comment by astormnewrelic** [comment]
@simoneb We've got a draft PR with some _basic_ fastify support built in.  Would you be interested in giving it a spin? https://github.com/newrelic/node-newrelic/pull/354

**Comment by simoneb** [comment]
Thanks @astormnewrelic. I put together a quick codesandbox to try it out using your branch for the newrelic package. You can see the license key in there and the logs, so I guess you should be able to access the app dashboard somehow.

https://codesandbox.io/s/newrelic-fastify-y5kh9

It looks good to me, I can see the two routes of the app being hit and reported in the dashboard.

**Comment by astormnewrelic** [comment]
@simoneb Nice!  So, slightly larger ask -- we know people choose fastify because it's -- well --  _fast_ 🐇. Sometimes an APM agent (including ours) can introduce a lot of extra overhead in the work it's doing.   Give you're close to the fastify core engineers, do you see anything obvious we might be able to do to reduce that overhead for this fastify instrumentation?

**Comment by mcollina** [comment]
@astormnewrelic not on the Fastify side / this PR as far as I can see. As part of our Node core work we have been working hard to reduce the overhead cost of async_hooks. All of that is included in https://nodejs.org/api/async_hooks.html#async_hooks_async_hooks_executionasyncresource and https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage. With the current code in Node v14, keeping the context adds _only_ 8% overhead (what you are doing is somehow in the 20-25% range).

**Comment by astormnewrelic** [comment]
Coming back to this: @mcollina -- my apologies, it's not 100% clear to me what you mean when you say _I would recommend to open a separate issue_ -- are you suggesting an issue [in the NodeJS project itself](https://github.com/nodejs/node/issues) to report a perf. problem?  Or are you suggesting an opening in issue in a different repository (here? fastify's repo? somewhere else?)

**Comment by mcollina** [comment]
I mean opening a separate issue in this repo. using `AsyncLocalStorage` is _not_ fastify-specific in any form.

**Comment by astormnewrelic** [comment]
We've got fastify route naming behind a feature flag, [details in the PR where it landed](https://github.com/newrelic/node-newrelic/pull/354).  Going to close this issue out for now -- new issues for features would be welcome.
