### ISSUE TITLE
Instrument whole nodejs script as background transaction

### ISSUE THREAD

**Issue by maxgalbu** [newrelic/node-newrelic#338]
Hi,
I have a whole nodejs script that does not expose routes and it's all run in the background (think of it as a cronjob). 

Is there a way to consider it a background transaction, other than wrapping all the code with `newrelic.startBackgroundTransaction(name, function() { $code });` (which is a biiiit ugly)?

**Comment by michaelgoin** [comment]
Hi @maxgalbu!

Unfortunately, passing a function to `newrelic.startBackgroundTransaction()` is the only option we currently have available.

To avoid a layer of nesting, you could define your function and then pass it in by name: 

```js
newrelic.startBackgroundTransaction('myName', myfunction)

function myFunction() {
  // Actually do the work
}
```

But it isn't much of a change.

"a biiiit ugly" is perhaps a bit subjective haha but maybe we can get a feature request in for what you were hoping for.

Would you prefer to have an API available that is a bit more procedural? Such as:

```js
const transaction = newrelic.startBackgroundTransaction('myName')

// Actually do the work

transaction.end()
```

Or is there another approach you are thinking would be nice for your use case?

**Comment by michaelgoin** [comment]
Closing out due to age.

**Comment by saroshaga** [comment]
> Would you prefer to have an API available that is a bit more procedural? Such as:

@michaelgoin : this would actually be nice
