### ISSUE TITLE
Outdated version of @grpc/grpc-js 

### ISSUE THREAD

**Issue by AlexShemeshWix** [newrelic/node-newrelic#340]
Hi
Im using newrelic@6.6.0
When i check my yarn.lock i can see that this package installs outdated version of @grpc/grpc-js 0.6.18.
Current version of  @grpc/grpc-js is 0.8.1.
That creates double dependencies in my project.
Please upgrade @grpc/grpc-js to 0.8.1.
Thanks

**Comment by michaelgoin** [comment]
Hi @AlexShemeshWix,

We are actually planning to ship with a newer version with the next release. It will be newer than `0.8.1`, however. `grpc-js` now has official 1.0+ releases.

**Comment by michaelgoin** [comment]
We've shipped with a newer version of `grpc-js`, so I'm closing this issue.

I'm guessing drift will continue to be an issue as far as your dependency size. We can consider making these dependencies optional as they are used for a subset of features, so let us know if that would be desirable and we can note that.

Thanks,

Michael
