### ISSUE TITLE
Additional dependencies with  New relic

### ISSUE THREAD

**Issue by reachmehere89** [newrelic/node-newrelic#341]
While reviewing modules used by New relic as dependencies, found that koa,superagent, aws-sdk etc modules are listed in dependencies. 
If my understanding is correct and forgive me if i'm wrong, these modules are specifically created for instrumentation of koa, superagent,aws-sdk. If my application doesn't use any of these, it doesn't make sense to have it downloaded into my application. Can we consider using these as pluggable modules so that application which needs them can include it within itself and it should not be shipped as part of New relic agent itself

**Comment by carlonewrelic** [comment]
Hi @reachmehere89 , thank you for your comment.  I like your suggestion to make these pluggable modules and only loaded as needed.  If you wish to make this feature request, you can do so via [New Relic's explorer hub](https://discuss.newrelic.com/c/feature-ideas) or to [open a support ticket](https://support.newrelic.com/).  That way it the request can get properly prioritized along side our main work.

**Comment by michaelgoin** [comment]
We should definitely consider but one thing for general conversation/consideration is we also have to balance the needs of customers who want it to "just work" out of the box and not necessarily have to install multiple newrelic packages to get up and running. For example, we felt some pressure to get the `aws-sdk` instrumentation included by default into the main agent. 

That being said, that preference might just be more vocal. I certainly like keeping things lightweight for install. Perhaps there is a middle-ground at some point of "install X to get all the external packages" or install each individually.

**Comment by jthurman42** [comment]
@michaelgoin Making things just work is great, but following the [install instructions](https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent/) for apps that do no use `aws-sdk` causes compilation failures:

```
./node_modules/@newrelic/native-metrics/lib/pre-build.js
Module not found: Can't resolve 'aws-sdk' in '<REDACTED>/node_modules/@newrelic/native-metrics/lib'
```

Logic to conditionally import / enable that feature would be great, or even more interactive experience for detection on install (do you want to install X/Y/Z too? type of thing vs the current installation instructions)

**Comment by michaelgoin** [comment]
@jthurman42 hmm that's really weird. Many customers do not use the aws-sdk (and in our own app testing) and do not have any issues.

And I honestly have no idea why on earth anything related the native metrics module... something natively compiled or download woudl have anything to do with aws-sdk at all.

So either there is something off with the instructions you linked, or something unique to your environment we need to expose and resolve. Similarly, you don't necessarily use koa or necessarily use superagent. You aren't seeing warnings for those but they are included in the identical way.
