### ISSUE TITLE
How to use newrelic with esm "import" syntax?

### ISSUE THREAD

**Issue by AdityaAnand1** [newrelic/node-newrelic#344]
https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_enabling

When enabling esm mode, either import is recognized or require is recognized. Both are not recognized together, so is there a way to the import syntax instead of require? (I'm unwilling to convert my entire app back to the require format just for this)

I'd like to use this:
```
import 'newrelic.js';
```

I tried this:

```
import 'newrelic.cjs';
```

(explicitly making it cjs = use common module for one file)

Which currently gives an error:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Projects\backend\src\bin\www.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
```

**Comment by carlonewrelic** [comment]
Hi @AdityaAnand1 

You should be able to import newrelic this way

`import newrelic from 'newrelic'`

The newrelic.js config file will not load properly in esm mode.  You will need to setup the agent configuration with environment variables.  That being said, we currently do not support auto-instrumenting modules loaded via esm mode.  We do plan to add support in the future.  If you would like to help prioritize this work you can submit a feature request through [New Relic's explorer hub](https://discuss.newrelic.com/c/feature-ideas) or by [submitting a support ticket](https://support.newrelic.com/).

**Comment by AdityaAnand1** [comment]
Thank you, can you provide the exact instructions for setting up this way? Or maybe a link to the docs?

1. Which environment variables are required for minimal setup? (The docs give the whole list but will it work with just app_name + license key environment variables?)
2. Is there a way to enable to debug logging for newrelic? Right now, I get no visibility whether or not it is working or not? (Something I can set to `.isDebugMode(true)` on my local environment so that I know that it'll work when I push it to prod

**Comment by AdityaAnand1** [comment]
Instead of 

```
import newrelic from 'newrelic'
```

the following

```
import 'newrelic'
```

should work too, right? (unless the newrelic import needs to be used in some way)

**Comment by AdityaAnand1** [comment]
I tried the environment variable route, however it doesn't seem to be detecting them (In the following image I print the env variable right after newrelic says it doesn't exist)

![image](https://user-images.githubusercontent.com/13274079/81881797-b878e400-95ae-11ea-95a3-4467d04be78d.png)

Any ideas?

**Comment by carlonewrelic** [comment]
@AdityaAnand1 To answer your first question, you should use `import newrelic from 'newrelic'`.  `import 'newrelic'`  will not work due to the way the newrelic module is exported.  

To use the environment variables you will need to remove the newrelic.js configuration file from your application and provide all that information via environment variables.  You can see the list of environment variables here:
https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#environment

Let me know if you need more help.

**Comment by iwaduarte** [comment]
What is the problem to try to load either .js or .cjs.
While using this flag --es-module-specifier-resolution=node  I would expect to load the file even if the host is using esm.
How hard would be to be implemented?

**Comment by drmrbrewer** [comment]
@carlo-808 is it likely that loading a configuration file will be supported with ESM import?  It clutters up the environment variable space to have an environment variable for each and every (non-default) new relic setting, and for some there doesn't even seem to be an environment variable at all: [`allow_all_headers`](https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#allow_all_headers).

**Comment by carlo-808** [comment]
@drmrbrewer If we get to supporting ESM in the agent, we will ensure that the config will load via ESM import. That being said, we have several roadmap items ahead of that work.

**Comment by HishamMubarak** [comment]
Ran into this same issue after adding `"type": "module"` in my package.json file.

The only solution I found was to change stuff inside newrelic package using [patch-package](https://www.npmjs.com/package/patch-package)

Changed content inside `/node_modules/newrelic/lib/config/index.js` at line 35:
`const DEFAULT_FILENAME = 'newrelic.js'`
to
`const DEFAULT_FILENAME = 'newrelic.cjs'`

And then in the root of my project, renamed `newrelic.js` to `newrelic.cjs` 
Then imported newrelic at `import * as newrelic from 'newrelic'` in root index.js

I know this is not a recommended way, but it was the only was I could make it work at the moment.

**Comment by HishamMubarak** [comment]
> That being said, we currently do not support auto-instrumenting modules loaded via esm mode.

Hi again, does this mean that newrelic wont work the same way if I switched to esm? I moved my codebase to esm and since then all my newrelic transactions got bundled into a single transaction called *, so now the transaction page is effectively worthless. 

Is there anyway to make the auto transaction tracking work with esm?
Or the only possible option is to implement babel to covert everything to es5, to make newrelic work?

**Comment by carlo-808** [comment]
Hi @HishamMubarak , unfortunately, you are correct. The Agent is unable to instrument esm modules at this time. Auto-instrumentation will not work directly with esm. It may be possible to get it working if everything is converted to es5, but we have not tried that to verify it will work. If you were to go that route, I think you may need to load the agent using the `-r` flag, like `node -r newrelic app.js`, where app.js is the entry point of your es5 compiled code. That being said, the newly compiled modules may not be instrumented and you may have to use the agent API to instrument.

**Comment by HishamMubarak** [comment]
> If you were to go that route, I think you may need to load the agent using the `-r` flag, like `node -r newrelic app.js`, where app.js is the entry point of your es5 compiled code.

If I may ask, what is the -r flag for? Is it something related to newrelic cli or node cli?

> That being said, the newly compiled modules may not be instrumented and you may have to use the agent API to instrument.

I did not clearly understand. The whole point of converting to ES5 is for the ability to instrument everything right? Are you saying that even after I convert it to ES5, I will still need to manually instrument each API call... etc?

**Comment by HishamMubarak** [comment]
> Hi @HishamMubarak , unfortunately, you are correct. The Agent is unable to instrument esm modules at this time. Auto-instrumentation will not work directly with esm. It may be possible to get it working if everything is converted to es5, but we have not tried that to verify it will work. If you were to go that route, I think you may need to load the agent using the `-r` flag, like `node -r newrelic app.js`, where app.js is the entry point of your es5 compiled code. That being said, the newly compiled modules may not be instrumented and you may have to use the agent API to instrument.

Hi, just tried this. Used babel to transpile my node app to es5 and deployed. Now things are back to normal and I am able to inspect each API separately.
