### ISSUE TITLE
Getting a type error on newrelic agent version ^6.7.1 and aws-sdk ^2.681.0

### ISSUE THREAD

**Issue by nambok** [newrelic/node-newrelic#357]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

Getting a type error on newrelic agent version ^6.7.1 and aws-sdk ^2.681.0

## Description

[NOTE]: Getting the following error when running the latest agent

```
TypeError: Cannot read property 'lastIndexOf' of undefined
at grabLastUrlSegment (/usr/src/app/node_modules/@newrelic/aws-sdk/lib/sqs.js:44:30)
at features.constructor.recordMessageApi (/usr/src/app/node_modules/@newrelic/aws-sdk/lib/sqs.js:33:21)
at features.constructor.consumeRecorder (/usr/src/app/node_modules/newrelic/lib/shim/message-shim.js:428:24)
```

## Steps to Reproduce

when reading from sqs newrelic agent throws the error
```js
return Promise.resolve(sqs.receiveMessage({
    AttributeNames: [],
    MessageAttributeNames: [
      'All',
    ],
    MaxNumberOfMessages: max,
    VisibilityTimeout: config.queue.sqs.VisibilityTimeout,
    WaitTimeSeconds: config.queue.sqs.WaitTimeSeconds,
  })).then((data) => {
  ....
```

## Your Environment
Running a node docker container image `node:carbon`

## Additional context
Everything works as expected running agent version `^3.0.0`

**Comment by carlonewrelic** [comment]
Hi @nambok !  Nice catch!  I'll enter a bug ticket for this.

**Comment by carlonewrelic** [comment]
@nambok One question, what do you mean by 

> Everything works as expected running agent version ^3.0.0

**Comment by nambok** [comment]
@carlonewrelic the code doesnt throw the error 
```
TypeError: Cannot read property 'lastIndexOf' of undefined
```
when running the newrelic agent version `^3.0.0`

makes sense?

**Comment by carlonewrelic** [comment]
@nambok Thank you for clarifying 👍

**Comment by michaelgoin** [comment]
@nambok that is because we don't have aws-sdk instrumentation for 3.x versions of the agent.

To avoid the error, you may need to temporarily downgrade to a version prior to the aws-sdk being packaged by default, so < 6.1.0.

**Comment by nambok** [comment]
yip, just wanted to make sure you guys were aware. Thanks! 😄

**Comment by astormnewrelic** [comment]
PR landed to fix this in https://github.com/newrelic/node-newrelic-aws-sdk/pull/34 -- next steps are for us to do a `@newrelic/aws-sdk` release.  We'll update this issue when that's done, but if anyone (i.e. @nambok) wanted to install directly from https://github.com/newrelic/node-newrelic-aws-sdk this should fix the above problem.

**Comment by astormnewrelic** [comment]
@nambok v1.1.3 of the AWS SDK has landed, and has a fix for this bug.  We'll be closing this issue out -- if you're still seeing issues (or can share the specific use case for omitting a parameter the SDK lists as required) please don't hesitate to keep the conversation going.
