### ISSUE TITLE
Source map issue with New Relic Webpack Plugin

### ISSUE THREAD

**Issue by etienne-martin** [newrelic/node-newrelic#367]
## Description

We're using the [New Relic experimental plugin](https://www.npmjs.com/package/@newrelic/webpack-plugin) to allow New Relic's NodeJS Agent to work with webpack compiled server side javascript and it's causing issues with the source map that's generated by webpack.

I noticed that the plugin adds a new line with `require("newrelic");\n` at the top of the compiled files and this is what's causing issues. The line added by the newrelic plugin is not taken into account when the source map is generated by webpack.

We fixed the issue by removing the new line (`\n`) after the require statement that's injected by the webpack plugin.

I'm posting this here because I could not find the repository for `@newrelic/webpack-plugin`.

**Comment by nijotz** [comment]
Hi Etienne!

Thanks for your bug report. That makes sense that the `\n` would mess up the source map. This seems like it should be a quick fix that I can get to soon. I'll start looking into it when I can and keep you posted.

Thanks!
Nick

**Comment by etienne-martin** [comment]
Thank you @nijotz

**Comment by etienne-martin** [comment]
It seems like other people are having the same issue: https://discuss.newrelic.com/t/experimental-webpack-plugin-for-nodejs/88068/14

**Comment by astormnewrelic** [comment]
@etienne-martin (and all following) Thanks again for bringing this to our attention.  Until we get this plugin published to GitHub this is the best place for issues. This is still an experimental plugin -- if you'd like to see this more officially supported (including a GitHub repo) be sure to file a feature request [via our formal support channels](https://support.newrelic.com/). 

We've just published version 0.4.1 of the plugin, which removes this newline from the compiled output. 

https://www.npmjs.com/package/@newrelic/webpack-plugin

We'd be interested in hearing if this helps with your soucemap issue.  We can see how this newline would interfere with any line number offsets provided via a source map, but we're still a little concerned about character offsets.  Also, if you (or anyone following) knows whether it's possible for a plugin to tap into these source maps and provide a proper fix we'd appreciate the information.  Our current solution is um -- pragmatic? -- but there's a probably a better way to fix this. 

Closing for now, but don't hesitate to open a new issue or keep this conversation going.

**Comment by etienne-martin** [comment]
Thanks @astormnewrelic and the team for such a quick fix. 

I agree that this is a "good enough" solution for our current use case given that our build files are not minified. But yeah, I can see why this can still be an issue with compiled javascript that spans a single line.

Here's an attempt at dealing with the character offset by github user @kxlow: https://discuss.newrelic.com/t/experimental-webpack-plugin-for-nodejs/88068/16

And here's the gist: https://gist.github.com/kxlow/98bfb17e3429a48436219020610f0eb4

Thanks again
