### ISSUE TITLE
startSegment doesn't work for patching/wrapping functions

### ISSUE THREAD

**Issue by janpio** [newrelic/node-newrelic#391]
## Description

I am trying to wrap an exported method of a library so I can add some New Relic instrumentation to it. Unfortunately this segment is discarded with the following error message in the logs:

`{"v":0,"level":20,"name":"newrelic","hostname":"...","pid":29256,"time":"2020-06-21T21:18:56.369Z","msg":"startSegment(\"Query Engine (prisma.fetcher.request)\") called outside of a transaction, not recording.","component":"api"}`

There _is_ a transaction running when the method is called - shortly before and after segments are successfully created. Seems just the way I wrap the function makes it lose the transaction.

## Steps to Reproduce

https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-sql-typescript-postgres + 

```
var originalRequest = prisma.fetcher.request
var newRequest = async function(object) {
  var label = 'Query Engine (prisma.fetcher.request)'
  
  var result = await newrelic.startSegment(label, true, async () => {
    return await originalRequest.call(this, object)
  })
  
  return result
}
prisma.fetcher.request = newRequest
```

## Expected Behavior

The segment is successfully created and my code is instrumented.

## Your Environment

`"newrelic": "^6.9.0",`
node: v12.6.0
OS: Windows

**Comment by michaelgoin** [comment]
Hi @janpio,

Sorry you are running into some difficulties. Sometimes the transaction state tracking can be a pain.

`startSegment` by itself should not have issues finding a currently active transaction, but often there is an order of operation issue or sometime certain frameworks are written in a way that cause us to lose state in certain situations.

To resolve issues such as this one, we typically need a bit more hands-on approach by leveraging our great support team. I would recommend going through the official support channels via: https://support.newrelic.com/.

They'll likely start by asking for some trace-level logs, your configuration and frameworks being used. What will likely also be helpful is understanding what is creating the transaction (web framework? custom instrumentation?) and what code you are seeing segments created for around this particular failure. I would not be surprised at all to find prisma is doing some async pooling or such that causes us to lose state.

Thank you,

Michael

**Comment by rr0214** [comment]
Hi @janpio I hope you were able to receive help through support https://support.newrelic.com/.

I am going ahead and closing this out.
