### ISSUE TITLE
Switch to 'main' as default branch

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#396]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

We've settled on `main` as the new default branch name.

This will involve creating and migrating to the new branch before deleting the prior. We'll also want to ensure we change the base of any existing PR's etc.

Hanselman has some helpful instructions on the blog: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx. I'm sure there are other useful resources out there as well.

**Comment by nijotz** [comment]
* default branch in repo settings changed
* changed the base of all open PRs

**Comment by nijotz** [comment]
* default branch in repo settings changed
* changed the base of all open PRs
* copied master branch protection rules to main (and left master there)
* gave instructions to team for updating their local repo, copied here:
  ```
   $ git checkout master
   $ git branch -m master main
   $ git fetch
   $ git branch --unset-upstream
   $ git branch -u origin/main
   $ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
   ```
* Edited "Manual Node Agent Release Process" to reference `main` branch instead of `master`

**Comment by michaelgoin** [comment]
Setup snyk to use `main`. Submitting a PR will be a final test of that.

**Comment by michaelgoin** [comment]
Seems like we've likely got everything at this point.

Wondering if we should delete master now, with this issue, or open another card and delete after a few days of letting things settle.
