### ISSUE TITLE
Minimal code cleanup

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#398]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

We are already in decent shape but do a pass for general things outlined in the Engineering Plan.

**Comment by nijotz** [comment]
Some funky regex for getting all the comments from the codebase:
```
rg --pcre2 '(?<!SELECT)(// |^ *\*(?!/))(?! Copyright|.*Apache|.*eslint)'
```

**Comment by nijotz** [comment]
What about links to internal docs?
