### ISSUE TITLE
Readme Updates

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#399]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

* Clear instructions for development and "building".
* For Explorer's Hub, we'll want to point here: https://discuss.newrelic.com/c/support-products-agents/node-js-agent/
* Template will likely help but good time to scrub out-dated info, make info clearer, etc. (Can split into multiple issues)

**Should strongly consider going with the consistent template.**
  * See the repo template project.
  * Recommended to run readme by docs team when done.

**Comment by rr0214** [comment]
@michaelgoin here is the README template: https://github.com/newrelic/newrelic-repo-template/blob/master/README_agent.md
