### ISSUE TITLE
Update contributing guidelines

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#403]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

* We already have a “contributing guide”. We probably should review the content VS the current NR open source repo template and determine if we want to update. 

  Consistency will likely make cross-NR contributors and our lives easier.

* "Need to put something in your contributing guidelines that is like "We can only accept PRs for version X or greater" with X being the version you OSS."

**Comment by nijotz** [comment]
Link to the template: https://github.com/newrelic/newrelic-repo-template/blob/master/CONTRIBUTING.md
