### ISSUE TITLE
Node agent doesn't use proxy for infinite tracing

### ISSUE THREAD

**Issue by danifitz** [newrelic/node-newrelic#428]
## Description

Agent cannot connect to trace observer, we see it connects/disconnects regularly in the agent log file. All communication is required to go through a proxy. Agent should use proxy for connecting to trace observer when one is configured.

## Steps to Reproduce

Try and configure infinite tracing when outbound internet access is only allowed via a proxy.

## Expected Behavior

Agent connects to trace observer via HTTP proxy

## Relevant Logs / Console output

{"v":0,"level":30,"name":"newrelic","hostname":"xxxx","pid":204,"time":"2020-07-10T13:22:29.954Z","msg":"Span streamer connected","component":"span-streamer"}
{"v":0,"level":30,"name":"newrelic","hostname":"xxxx","pid":204,"time":"2020-07-10T13:22:29.985Z","msg":"Span streamer disconnected","component":"span-streamer"}
{"v":0,"level":30,"name":"newrelic","hostname":"xxxx","pid":204,"time":"2020-07-10T13:22:44.990Z","msg":"Span streamer connected","component":"span-streamer"}

## Your Environment

agent version 6.10.0, kubernetes, docker, istio/envoy as proxy.

**Comment by astormnewrelic** [comment]
Thank for the feature request @danifitz.  A few questions

1. Do you happen to have a reproducible test case here?  We know that _New Relic Edge with Infinite Tracing_ for Node.js doesn't officially support "proxy" servers, but proxy is a bit of an overloaded term.  Having a reproducible test case that we could run would help tremendously in getting to the bottom of this. 

2. Similarly -- you mentioned in the issue _Agent connects to trace observer via **HTTP proxy**_.  _New Relic Edge with Infinite Tracing_ uses a GRPC connection,  which is ultimately HTTP2, not HTTP. If/when we get official support for proxy servers into _New Relic Edge with Infinite Tracing_ users will still need to have their proxy server configured to handle GRPC traffic.  

3. While we don't have _formal_ configuration for a GRPC proxy server for _New Relic Edge with Infinite Tracing_ -- the underlying GRPC library we use does appear to support environmental variables that would let you set some proxy server information.  This might let you proceed while this feature request works it's way through the system.  You can [find the env variable names here](https://github.com/grpc/grpc-node/blob/%40grpc/grpc-js%401.0.5/packages/grpc-js/src/http_proxy.ts#L45).

**Comment by danifitz** [comment]
In this case the proxy being used is Istio/Envoy which should support HTTP/2. Thanks for the hint on the other env vars which could be used. 

I’m terms of being able to reproduce, a simple node app that uses a sidecar istio proxy (envoy) should replicate this behaviour

**Comment by danifitz** [comment]
Okay, update: the HTTP proxy is actually just a regular squid proxy cluster which supports HTTP/2. We tried setting GRPC_PROXY but we still see the connect/disconnect messages in the agent log.

**Comment by danifitz** [comment]
Update: Confirmed we are seeing traces after setting GRPC_PROXY, there is still the activity in the agent log related to connecting and disconnecting. The customer has stated the preference would be for the agent to use the existing `NEW_RELIC_PROXY_URL` to handle this rather than needing to set an additional env var such as `GRPC_PROXY`.

**Comment by michaelgoin** [comment]
Given there is a potential need, depending on setup, for those to be different... it is more likely we'd have a separate setting additionally introduced.

How frequent are the disconnect/reconnects? I do know the server will manually trigger reconnects on purpose on a regular interval. In these situations, we retain data and reconnect as soon as possible (unlike error cases where there is a delay on reconnect). The log above looked super frequent, but is that still the case or is it more spread out?

**Comment by rr0214** [comment]
There is a work around. We are going to document the work around solution.

**Comment by jordigh** [comment]
Fixed by https://github.com/newrelic/docs-website/pull/6585
