### ISSUE TITLE
GraphQL/Apollo Server 

### ISSUE THREAD

**Issue by rr0214** [newrelic/node-newrelic#438]
### Summary

There is a large customer demand for GraphQL Apollo Server support:

GraphQL, a query language for your API, is becoming increasing popular over REST APIs due to its efficiency and flexibility. It minimizes the amount of data to be transferred over the network by requesting exactly the data it needs. GraphQL can be used with any framework and protocol.

With the completion of this MMF, customers will be able to breakout their transactions based on payload as well as have visibility into their downstream GraphQL services and databases. Customers will be able to see what exact query came in, which backends were called and how long it took to process the request in totally.

### Background

GraphQL servers is typically a single endpoint that enables a user to "query" the data. Since it is only one endpoint, the Node.js agent doesn't show downstream servers and performance of the request call. This is inadequate for the end-user. They are interested in knowing how each resolver performs so that they can troubleshoot and tune their graphQL services.

### Proposed Solution 

Breakdown query so that each operation/variable combination becomes a transaction. Each transaction will be associated with their downstream services, resolvers, which will be represented as segments within NR. Each segment will show the response time.

### Acceptance Criteria

Part 1 (Transactions/Traces):

- Create a transaction for GraphQL Operation Name and Field combination
- Use the following naming convention for the transaction:

_ **GraphQL.Operation Type.OperationName.FieldName (see attached diagram for definitions)** _

- Expected instance details and environment data should be passed to NR i.e.

    - Host
    - Request Path
    - URL
    - Method

Part 2 (Segments/Spans):

- Create a segment for each top level resolver
- Resolver should have identifiable human readable name
- Should track resolver response time
- Time Consumption by Caller should be show GraphQL transactions
- Show response time and throughput on each segment
- Include Operation Type, Operation Name, Object Type(s)

What is will not include:

This MMF will not include GraphQL operation type called Subscription.

For all the above, also include

- Unit-tested
- New capability is documented in ’compatibility' section of [docs.newrelic.com](http://docs.newrelic.com), and documentation is available in docs.newrelic, Node. JS docs and Github in line with other integration packages that describes to customers what is required to make this instrumentation work
- Instrumentation Demo

### Supporting Materials

Apollo GraphQL Manager: [https://engine.apollographql.com/org/acephei-corp/graphs](https://engine.apollographql.com/org/acephei-corp/graphs).

What is GraphQL Description/Summary: [https://docs.google.com/document/d/1iZG4mRzmKeJ-u8okzJpV3x0r5w-ffRW9VhSiKU9JOuk/edit?usp=sharing](https://docs.google.com/document/d/1iZG4mRzmKeJ-u8okzJpV3x0r5w-ffRW9VhSiKU9JOuk/edit?usp=sharing)

**Comment by respectTheCode** [comment]
Please include support for Apollo Federation

https://www.apollographql.com/docs/apollo-server/federation/introduction/

**Comment by rr0214** [comment]
This work is complete. The Apollo Server GraphQL Plugin can be found here: https://github.com/newrelic/newrelic-node-apollo-server-plugin.
