### ISSUE TITLE
Truncated outbound requests are labeled as category generic rather than http

### ISSUE THREAD

**Issue by carlo-808** [newrelic/node-newrelic#439]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
When an outbound http request is made resulting in a truncated segment, the resulting span is labeled with the attribute category: generic.  It should have been labeled category: http.  This is happening because the the truncated segment name is prefixed with 'Truncate' before the segment is converted to a span.  The span category is set to http by looking for the 'External' prefix in the segment name attribute.

Relevant code:
https://github.com/newrelic/node-newrelic/blob/main/lib/transaction/index.js#L214-L224

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
Spans resulting from an outbound http request should be labeled category http regardless of whether the originating segment was truncated or not.

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
Node.js agent version 6.11.0

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by astormnewrelic** [comment]
Some good first steps here would be a test case that demonstrates the behavior.
