### ISSUE TITLE
Add more examples of api usage

### ISSUE THREAD

**Issue by carlo-808** [newrelic/node-newrelic#441]
## Feature Description
Add more examples of api usage to `/examples`.  Specifically examples for recording custom events and adding custom attributes would be helpful.  A nice example around creating and accepting distributed trace headers would be useful as well.

These are some of the api methods in question:
`newrelic.recordCustomEvent(eventType, attributes)`
`newrelic.addCustomAttribute(name, value)`
`newrelic.addCustomAttributes(attributes)`
`newrelic.addCustomSpanAttribute(name, value)`
`newrelic.addCustomSpanAttributes(attributes)`
`transactionHandle.acceptDistributedTraceHeaders`
`transactionHandle.insertDistributedTraceHeaders`
`transactionHandle.createDistributedTracePayload()`
`transactionHandle.acceptDistributedTracePayload`

## Additional context
Customers have requested these examples.

## Priority
Nice to have

**Comment by justqyx** [comment]
+1
