### ISSUE TITLE
newrelic.js config validator

### ISSUE THREAD

**Issue by davidnormo** [newrelic/node-newrelic#444]
## Is your feature request related to a problem? Please describe.
Yes. I added the `expected_status_codes` property to my project config but didn't realise it was wrapped in the `error_collector` object. Took a while to get to the bottom of the problem. Having a little script that can validate the config file and point out errors would be really handy.

## Feature Description
A script that the user can run to validate the newrelic.js config file. For example:

```
$ npx newrelic-validate-config
Found 3 issues:
1. Unexpected property `expected_status_codes`. Did you mean `error_collector.expected_status_codes`?

2. Invalid type given for `app_name` should be `array` found `string`

3. Invalid value given for `logging.level` found "errror" should be one of: "fatal", "error", "warn", "info", "debug" or "trace"
```

## Describe Alternatives
n/a

## Additional context
I'm happy to contribute to the solution, just wanted to get an idea if people would find this useful or not?

## Priority
Really Want

**Comment by astormnewrelic** [comment]
That would be a pretty sweet feature @davidnormo -- I know I would have liked something similar when I was starting with the Node Agent, and I can think of a bunch of support tickets where having such a thing would have helped. 

Do you think you'd use something formal like JSON Schema for this?  Or something a bit simpler with a set of type rules for each "path" into the JSON file?  Or some third thing?

**Comment by davidnormo** [comment]
Thanks for the feedback. Yeah JSON schema or typescript. I was thinking of using jsdoc to add types. Then if new properties are added, the author can just add types without having update the validation script

**Comment by astormnewrelic** [comment]
Hey there @davidnormo -- it's been a moment. Are you still interesting in trying something like this and just looking for the time, or is something blocking you?  Or did you find a better solution?  No preasure here -- just checking in while we have a moment.

**Comment by davidnormo** [comment]
I've spent a little time on it but haven't found a great jsdoc/typescript
parsing solution. I'll probably go for a more basic first version but I'm a
little strapped for time at the moment. This may be a slow burner...

**Comment by astormnewrelic** [comment]
Sounds good @davidnormo -- we'll keep the issue open and check-in periodically. Hopefully time will unstrap you soon.

**Comment by rr0214** [comment]
@davidnormo is this something you are still working on? If not, we will close this out.
