### ISSUE TITLE
Span error attributes not ignored

### ISSUE THREAD

**Issue by nijotz** [newrelic/node-newrelic#445]
Prior to v6.5.0, you could configure certain HTTP status codes to be ignored when reporting errors via the `ignore_status_codes` option. v6.5.0 introduced span error attributes which does not ignore HTTP status codes.

## Description

Errors are reported both as transaction error events and as span attributes. The [code path for span error attributes](https://github.com/newrelic/node-newrelic/blob/2121ffdc5001ea1bf9ab473138b9446c1f2a7eef/lib/transaction/index.js#L744) handles expected but not ignored.

[`shouldIgnoreError`](https://github.com/newrelic/node-newrelic/blob/2121ffdc5001ea1bf9ab473138b9446c1f2a7eef/lib/errors/helper.js#L103) is used by the [error collector](https://github.com/newrelic/node-newrelic/blob/2121ffdc5001ea1bf9ab473138b9446c1f2a7eef/lib/errors/error-collector.js#L207) for transaction error events.

## Expected Behavior

Ignoring functionality should be present in both code paths.

**Comment by linovaldivia** [comment]
NR Dashboard Services team would be able to help verify the fix once a build/pre-release candidate is available!

**Comment by michaelgoin** [comment]
Missed this issue. This should have been resolved with the latest 6.14.0 release.

Here's the relevant PR: https://github.com/newrelic/node-newrelic/pull/503
