### ISSUE TITLE
Winston + Node.js + New Relic-- No logging

### ISSUE THREAD

**Issue by awcchungster** [newrelic/node-newrelic#453]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The logging for my Node.JS app is not being sent to New Relic at all. Some telemetry data is available in the NR dashboard for my app, but no logs.

## Expected Behavior

I am trying to set up basic logging and metrics of my Node JS applications to New Relic.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

Diag:

> Check Results
> -------------------------------------------------
> 
> Info     Base/Env/CollectEnvVars [Gathered Environment variables of current shell.] 
> Success  Base/Config/Collect
> Success  Base/Config/Validate
> We've found a file that may contain secure information: /var/log/syslog
> Include this file in nrdiag-output.zip?
> Choose 'y' or 'n', then press enter: y
> adding file  /var/log/syslog
> Success  Base/Log/Copy
> Success  Base/Config/LicenseKey
> Success  Base/Config/ValidateLicenseKey
> Info     Base/Config/RegionDetect [1 unique New Relic region(s) detected from config.] 
> Info     Base/Env/HostInfo [Collected host information] 
> Success  Base/Log/ReportingTo
> Success  Node/Config/Agent
> Info     Node/Env/Version [v10.19.0 ] 
> Info     Node/Env/NpmVersion [6.14.4] 
> Info     Node/Env/Dependencies [We have successfully retrieved a list of dependenc...] 
> Success  Base/Config/AppName
> Success  Node/Env/NpmPackage
> Success  Node/Env/VersionCompatibility
> Info     Node/Agent/Version [5.13.1] 
> Success  Base/Agent/EOL
> Success  Base/Config/ValidateHSM
> Success  Node/Requirements/ProblematicModules
> Info     Base/Env/InitSystem [Systemd detected] 
> Success  Base/Collector/ConnectUS
> Success  Base/Env/DetectAWS
> 59 results not shown: 59 None

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

Set up Nodejs App, use Winston
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

All above in Diag

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by astormnewrelic** [comment]
Hi Alex, nice to meet you, and welcome to the platform :)

This isn't obvious (and we'd welcome any thoughts you have on improving the experience) -- but logging support isn't built in to language agents. Instead, languages have "Log Enricher" packages that you can _add_ to your agent instrumented project.  

You can find [the Node.js log enricher over here](https://github.com/newrelic/newrelic-winston-logenricher-node). If you install this (the README.md has instructions) you'll be good to go for logs in context. Also -- the logging product isn't limited to New Relic language agents -- [our logging docs can get you started on that](https://docs.newrelic.com/docs/logs/new-relic-logs/get-started/introduction-new-relic-logs).

Also -- for things like troubleshooting New Relic setup or how features are meant to work you'll be better off engaging through our [100% free community forums](https://discuss.newrelic.com/) or via the [support process](https://support.newrelic.com/). Those are dedicated channels for that sort of support -- GitHub issues are better for reporting known bugs or making PRs to fix bugs or add features. We're always happy to help out here but not every engineer will be able to triage every issue with the platform. The folks monitoring the forums and support channel are your dedicated resources for _anything_ to do with the platform. 

Good luck with your logging -- we're going to close this out but if you run into a bug or you're not getting what you need from the forum or support process don't hesitate to let us know.

**Comment by stevenaldinger** [comment]
have you considered adding this to the documentation? you acknowledged its not obvious but it would be extremely obvious if it just said shipping logs to newrelic isn't supported in the logging setup documentation.

**Comment by michaelgoin** [comment]
Hi @stevenaldinger ,

We can see if there's somewhere we can add verbiage to make things clear.

At the time we added logs support, none of the language agents supported sending logs directly. The intent has to been to go through a log forwarder per the standard setup instructions. This is because these tools are optimized for this purpose and resiliency in a way that is harder in an in-memory language agent. Since that point, I believe a couple of language agents (not the Node agent) have added the ability to directly send the logs from the agents. While available, that's not necessarily the recommended approach.

The section in the doc that was linked above called "bringing in your log data" has links to relevant sections for forwarding logs to New Relic from different locations: https://docs.newrelic.com/docs/logs/log-management/get-started/get-started-log-management/#integrate-logs

> Once log management is enabled, you can also connect your logs with your APM agent, Kubernetes clusters, or distributed tracing to get additional contextual logging data with our logs in context extensions.

At that point, the use of our log enricher writing to the log files that are forwarded will complete the setup.

https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/configure-logs-context/configure-logs-context-apm-agents/
