### ISSUE TITLE
Abnormally Long Distributed Traces and Duplicate Trace IDs

### ISSUE THREAD

**Issue by astormnewrelic** [newrelic/node-newrelic#457]
We've received sporadic reports of abnormally long distributed traces -- traces that should measure in the seconds being listed as lasting for minutes, or sometimes hours.

Our current theory is this is a bug caused by duplicate trace ids being generated in systems with a poorly seeded random number generator, or a system whose entropy level are low, or where the entropy is consumed. Docker containers are a common thread so far.

We're opening this issue to track occurrences of this behavior, share what we know about the issue, and determine possible solutions.

If you suspect you're seeing this same issue please let us know in the comments below, or via [one of](https://discuss.newrelic.com/) the usual [support channels](https://support.newrelic.com). 

## Background

An individual measurement in a single distributed trace is called a span.  When a distributed trace starts, agents generate a random trace id.  Every span generated in this trace will include a trace id attribute.  New Relic is then able to tie these spans together into a single trace using this trace id attribute.  If trace ids are not unique, then spans from different traces will be seen as part of the same trace.  These spans will have wildly out of sync start and end time, which will create the appearance of an abnormally long distributed trace.

Trace IDs are generated using randomness.  In the NodeJS Agent, this means using `Math.random()`.  Generally, `Math.random()` should produce numbers that are sufficiently random -- however, there's a number of factors about a user's underlying system that may impact this randomness.

How Node.js creates unique numbers will depend on

1. The version of Node you're running
2. Whether the system you're running Node.js on has a `/dev/urandom` resource
3. How your system generates entropy for its random number generator

### Version of Node.js

Node.js uses Google's V8 Javascript engine.  `Math.random()` numbers come from V8.  When V8 [initializes it's random number generator](https://github.com/nodejs/node/blob/v14.7.0/deps/v8/src/base/utils/random-number-generator.cc#L31) it will seed that generator. 

For the vast majority of linux systems, that seeding looks like this

```javascript
    FILE* fp = fopen("/dev/urandom", "rb");
    if (fp != nullptr) {
      int64_t seed;
      size_t n = fread(&seed, sizeof(seed), 1, fp);
      fclose(fp);
      if (n == 1) {
        SetSeed(seed);
        return;
      }
    }
```

V8 will use the `/dev/urandom` resource to seed the random number generator.  This is generally sufficient to generate the random numbers we require.

If `/dev/urandom` is not available, the random number generator will be seeded with the system time

    int64_t seed = Time::NowFromSystemTime().ToInternalValue() << 24;
    seed ^= TimeTicks::HighResolutionNow().ToInternalValue() << 16;
    seed ^= TimeTicks::Now().ToInternalValue() << 8;
    SetSeed(seed);
  
This is generally _not_ sufficient to generate the random numbers we require -- particularly if there are multiple docker containers starting at the same time.

While `random-number-generator.cc` is a relatively stable part of V8, it has seen some small changed over the year -- particularly if you're running on a non-linux platform.  These changes _may_ effect the seeding of your random number generator.

### Seeding of Random Numbers and `/dev/urandom`

In addition to the V8 engine's seeding of the random number generator, how your underlying operating system generates entropy for its random numbers will determine whether or not `/dev/urandom` returns a sufficiently random number or not. 

Entropy generation is a topic that's beyond our scope for today -- but on many linux systems you can check your system's entropy level by running 

    $ cat /proc/sys/kernel/random/entropy_avail
    [a number]
    
Low or consumed system entropy level is [a known issue when running in certain containerized environments](https://www.digitalocean.com/community/tutorials/how-to-setup-additional-entropy-for-cloud-servers-using-haveged).  This is a topic that's also beyond our scope for today, but you can learn a bit more by researching [entropy daemons like haveged](http://www.issihosts.com/haveged/index.html) or contacting your cloud provider.

**Comment by rr0214** [comment]
We haven't seen this problem for a while. We'll need more examples if this is still an issue that needs to be solved. There were some id improvements shipped with the W3C Trace Context work.
