### ISSUE TITLE
Agent Should Not use Redirect Host When Reconnecting to the Agent

### ISSUE THREAD

**Issue by astormnewrelic** [newrelic/node-newrelic#462]
When connecting to New Relic, the Node.js Agent uses the value in `agent.config.host` to post a request to the New Relic `preconnect` endpoint.  This endpoint returns a "redirect host", which (at the time of this writing) often looks like one of the following

    collector-00n.newrelic.com
    gov-collector-00n.newrelic.com
    
This URL becomes the URL that agents will send data to.

There is a bug in the Node Agent related to this functionality.  If the agent needs to _reconnect_ to the collector, it will **incorrectly** use this redirect host to call the `preconnect` endpoint, when instead it should use the original configured value in `agent.config.host`.  

It appears the root cause of this bug is the agent rewriting the `agent.config.host` value with the redirect host, and never resetting it when the agent resets.

We should probably _not_ rewrite this value. Instead we should 

1. Store the redirect host separately
2. Have the `RemoteMethod`s (save `preconnect`) use this stored redirect host value)

**Comment by astorm** [comment]
📆 📆 📆 📆 📆 📆 👍
