### ISSUE TITLE
NestJS Project can't Load newrelic.js 

### ISSUE THREAD

**Issue by astormnewrelic** [newrelic/node-newrelic#470]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The NestJS command line compiler incorrectly generates  a `../newrelic` path when transpiling `import * from newrelic` into CommonJS format.  This is an issue with the upstream provider. See 

https://github.com/nestjs/nest-cli/issues/838 for more details

## Additional context

We've had reports from @devfreddy that modifying `tsconfig.build.json` to include only the `src` directory is one workaround to this problem

    "include": ["src/**/*"],

**Comment by michaelgoin** [comment]
I ran into a related issue here and so importing (`import * as newrelic from newrelic`) ended up grabbing my `newrelic,.js` config.

I was able to work around by using the hybrid import syntax:

`import newrelic = require('newrelic')`

**Comment by igor-mardari-ft** [comment]
I placed `newrelic.js` in the root of my project.  
Then, in `AppModule` inside `configure()` function I just put `require('newrelic');` and that was all.
