### ISSUE TITLE
Debugging Agent

### ISSUE THREAD

**Issue by magicalbanana** [newrelic/node-newrelic#473]
Is there a way to debug the events being posted to the collector by the agent without having to connect to the collector? I just want to see what the payload is to the collector because I'm trying to determine how to handle certain errors types from an app.

I tried spinning up a basic web app and set the value of host to the app (e.g, localhost:3000) but it's not connecting. I'm guessing there's more to this than a simple endpoint.

**Comment by astormnewrelic** [comment]
Hello @magicalbanana -- nice to meet you.  Regarding your direct question

> Is there a way to debug the events being posted to the collector by the agent without having to connect to the collector? I just want to see what the payload is to the collector because I'm trying to determine how to handle certain errors types from an app.

The quick answer is -- no.  The long answer is -- it's complicated.  

The concept of a collector connection (for authentication and authorization) is pretty baked the agent right now. The `Agent` object's constructor function [will call the collector's connect method](https://newrelic.slack.com/archives/CQXTP3UAG/p1599074473023500).  This means if you're not configured correctly, you won't connect.

There are some possible things that _might_ let you do what you want, but nothing's that designed to let you do what you've asked.

First -- New Relic [now has a base account that's free](https://newrelic.com/signup).  If your concerns about connecting were posting data into your employer's dashboards you can always sign-up for a free account and debug til your heart's content.

Second -- the agent has something we call "Serverless Mode" that's used in for our Amazon Lambda support, where a traditional collector connection isn't used.  Switching you local dev agent to use serverless mode _may_ get you the results your after. 

Finally -- it doesn't sound like this was _quite_ what you were asking for, but if [you look at our tests](https://github.com/newrelic/node-newrelic/tree/main/test) we have an [agent_helper](https://github.com/newrelic/node-newrelic/blob/7b240660e9723eb23c0c81b4a877146fa0ab6163/test/integration/fastify/errors.tap.js#L4) that lets us test agent functionality without the need for a collector connection cycles.

Does any of that get you pointed in the right direction @magicalbanana?

**Comment by magicalbanana** [comment]
@astormnewrelic thank you! Extremely detailed response. I think the free account will do best and then if not, the serverless option.

**Comment by astormnewrelic** [comment]
Sounds great @magicalbanana -- we'll close this out for now, but if you have more questions you know where to find us :)

**Comment by magicalbanana** [comment]
@astormnewrelic would you be able to post an accessible link for this, https://newrelic.slack.com/archives/CQXTP3UAG/p1599074473023500? Thanks!

**Comment by astormnewrelic** [comment]
> @astormnewrelic would you be able to post an accessible link for this, https://newrelic.slack.com/archives/CQXTP3UAG/p1599074473023500? Thanks!

Whoops -- that's not the link :)  I updated my comment -- here where the agent connects to the collector https://github.com/newrelic/node-newrelic/blob/7208a8bbfaaa207883b26ed91fca6abe952d02f5/lib/agent.js#L231

**Comment by magicalbanana** [comment]
@astormnewrelic than you sir.
