### ISSUE TITLE
Requirement of NEW_RELIC_APP_NAME environment variable in serverless mode (Lambda)

### ISSUE THREAD

**Issue by superrafek** [newrelic/node-newrelic#477]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Node.js agent appears to still require `NEW_RELIC_APP_NAME` when running in Lambda as per [documentation](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-serverless-monitoring-aws-lambda#node). This value does not seem to be used anywhere in the UI or in any Event but without it the agent does not start. The other agents do not seem to share the same requirement.

## Expected Behavior

Remove the requirement of this environment variable for Lambda.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

Remove `NEW_RELIC_APP_NAME` in Node.js agent instrumented Lambda function to see it fail.

## Your Environment

AWS Lambda with Node.js agent using Manual Instrumentation.

**Comment by carlonewrelic** [comment]
Thanks for submitting the issue @superrafek , we'll get this work prioritized with our PM.

**Comment by nijotz** [comment]
The NEW_RELIC_APP_NAME environment variable is used to name the application. In APM, the applications are named based on this environment variable for Node apps. Some other agents provide a default like 'My Application' or 'PHP Application'.

https://docs.newrelic.com/docs/agents/manage-apm-agents/app-naming/name-your-application#app-name

Are you asking for a default name to be used if one is not provided?

**Comment by michaelgoin** [comment]
We definitely don't need the requirement for Lambda. We should also consider a default for standard cases to ease the process of getting up and running. For example, we could name based off of the package.json 'name' property and log a message saying that is what we are using. If nothing there either, we could default to a generic name.
