### ISSUE TITLE
@newrelic/publish-sourcemap using old version of yargs-parser

### ISSUE THREAD

**Issue by dave-nm** [newrelic/node-newrelic#478]
## Description
https://github.com/advisories/GHSA-p9pc-299p-vxgp

## Expected Behavior
Using more recent version of `yargs-parser`

## [Troubleshooting]
See link

## Steps to Reproduce
Install `@newrelic/publish-sourcemap` as [recommended by documentation](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/upload-source-maps-api#npm)

## Your Environment
Node version: 12.18.3
Operating System and version: macOS 10.15.6

**Comment by astormnewrelic** [comment]
Hey @dave-nm -- nice to meet you and thanks for the heads up.  

The [@newrelic/publish-sourcemap](https://www.npmjs.com/package/@newrelic/publish-sourcemap) package isn't actually published out of this repository -- but we'll see if we can track down its owners and ask about getting the `yargs-parser` version bumped. 

Our of curiosity -- is this something that causing issues for you? Or is just just a friendly abundance of security on your part?

**Comment by dave-nm** [comment]
Ya, I couldn't find anywhere else to report this, so I figured that this would at least get the conversation going.

It's not causing problems and is a pretty low security risk, but just working to make sure that all of our code and dependencies are as secure as possible

**Comment by astormnewrelic** [comment]
Makes sense @dave-nm -- a clean build is a righteous build :)

So this is tricky -- that code hasn't been open sourced yet so the team that owns it isn't on public GitHub.  We've got an internal issue opened to handle it (`DEMEXP-418`) and I've asked that folks report back in here when that's done.  If you need/wanted to track it more closely then the best route would be opening [a formal support ticket](https://support.newrelic.com/) or [saying hello in the forums](https://discuss.newrelic.com/). Both of those places are watched over by our mighty technical support engineers, and they'll be able to get you updates in a more timely manner than we can here.

**Comment by dave-nm** [comment]
Sounds good. Thanks for the update!

**Comment by astormnewrelic** [comment]
@dave-nm New version of https://www.npmjs.com/package/@newrelic/publish-sourcemap published.  I'm going to close this out but if you need more help here please do at us :).

**Comment by dave-nm** [comment]
There's something funky going on with the version numbers in that package and the released version is `4.4.2-0` and the `-0` makes `yarn` not want to resolve to that version so can it be published properly as `4.4.2`?

**Comment by michaelgoin** [comment]
Hi @dave-nm, 

I've passed on your message to the proper team.

Thanks,

Michael

**Comment by michaelgoin** [comment]
@dave-nm OK, looks like you should be able to give `4.4.2` a spin now. Hope that works out better!

**Comment by dave-nm** [comment]
That did the trick! Thanks again for the quick turn around on this

**Comment by michaelgoin** [comment]
Awesome. Glad to hear it.
