### ISSUE TITLE
Better Node 14, EOL Node 8

### ISSUE THREAD

**Issue by rr0214** [newrelic/node-newrelic#483]
### **Problem**

The maintenance cycle for Node.js 8 ended in [<ins>December 2019</ins>](https://blog.risingstack.com/update-nodejs-8-end-of-life-no-support/). This means since December 2019, Node.js 8 has not received updates, bug fixes or security patches, so it is in our customers’ best interest to upgrade their Node.js version to not be open to vulnerabilities. We there do not want to be responsible for fulfilling support for this version.

Also the newest version of Node.js, [<ins>Node.js 14</ins>](https://nodejs.org/en/about/releases/) was released in April 2020 and we want to ensure customers do not see _ **degradations** _ in their experience between Node 12 and Node 14

### **Solution**

Newer versions of the agent will no longer support Node 8 and we will fix any degradation between Node 12 and Node 14. Our documentation will be updated appropriately to reflect Node 14 support and the removal of Node 8 support

**Comment by jgeurts** [comment]
What is the timeline for full node 14 support?

**Comment by jgeurts** [comment]
Never mind.... I saw https://github.com/newrelic/node-newrelic/issues/329#issuecomment-692180970. I wish this project didn't feel so neglected/abandoned.

**Comment by nijotz** [comment]
Hey Jim, we're starting to work on Node v14 support now. You can track progress here: https://github.com/newrelic/node-newrelic/projects/5

**Comment by nijotz** [comment]
Closing in favor of #329

**Comment by nijotz** [comment]
Got that backwards.. reopening

**Comment by nijotz** [comment]
[v7.0.0](https://github.com/newrelic/node-newrelic/releases/tag/v7.0.0) was released which adds Node v14 support
