### ISSUE TITLE
Confusing documentation example - WebFramework

### ISSUE THREAD

**Issue by ronen-e** [newrelic/node-newrelic#485]
## Where
in the file
[examples/shim/Webframework-Simple.md](https://raw.githubusercontent.com/newrelic/node-newrelic/main/examples/shim/Webframework-Simple.md)

I am experiencing some confusion with the first code sample:
```js
var myWebFramework = require('my-web-framework')

// create server
var server = new myWebFramework.Server()

server.all(function authenticate(req, res, next) {
  if (authenticate()) {
    next()
  } else {
    res.statusCode = 403
    res.end()
  }
})

server.get('/api/users', function(req, res) {
  res.write(getUsers())
  res.end()
})

server.get('/home', function(req, res) {
  this.render('home', function(err, renderedView) {
    res.write(renderedView)
    res.end()
  })
})

server.start(8080)
```

### Specifically these lines:
```js
server.all(function authenticate(req, res, next) {
  if (authenticate())
```
## Reason
The function `authenticate()` is recursively calling itself causing an infinite loop.

The function is declared in this line:
```js
server.all(function authenticate(req, res, next) {
```

And later calls a reference of itself the following line, thus causing an infinite loop:
```js
  if (authenticate())
```
## Solution
Use non conflicting names like:

```js
var myWebFramework = require('my-web-framework')
var authenticate = require('./lib/authenticate')

// create server
var server = new myWebFramework.Server()

server.all(function authenticateMiddleware(req, res, next) {
  if (authenticate()) {
    next()
  } else {
    res.statusCode = 403
    res.end()
  }
})

server.get('/api/users', function(req, res) {
  res.write(getUsers())
  res.end()
})

server.get('/home', function(req, res) {
  this.render('home', function(err, renderedView) {
    res.write(renderedView)
    res.end()
  })
})

server.start(8080)
```

**Comment by nijotz** [comment]
Hi Ronen, thanks for catching that! Ya I don't think that function is supposed to be recursive. Do you want to put up a PR? If not, I can get to it sometime today.

**Comment by ronen-e** [comment]
@nijotz I would love to contribute but I won't be able to get to it today. 
If you can do it go ahead
