### ISSUE TITLE
Log out what metadata keys have been set for the environment

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#497]
Metadata keys can be set via ENV vars. These get sent to the server and then returned as request headers we attach to every request (or as metadata to gRPC requests).

This mostly transparent to the agent functionality enables linking of details such as kubernetes clusters to transactions.

Troubleshooting issues, though, can be a little bit rough as we just pass things around without keeping track of anything. This proposes a baby step towards improving troubleshooting by logging what keys have been set in the local environment.

We should log out what `NEW_RELIC_METADATA_` keys have been set as we iterate these to send them via our "facts."

**Comment by bizob2828** [comment]
@michaelgoin can you assign me and move to proper status?
