### ISSUE TITLE
Module not found: Error: Can't resolve './event-sources' in Angular Builder

### ISSUE THREAD

**Issue by ksooad** [newrelic/node-newrelic#502]
## Description

In angular builder webpack can't resolve  `require('event-sources')`  from https://github.com/newrelic/node-newrelic/blob/main/lib/serverless/aws-lambda.js#L25
Output error: Module not found: Error: Can't resolve './event-sources'

Angular builder don't use .json extension for resolve.

Add extension to `require('event-sources.json')` fix problem

**Comment by michaelgoin** [comment]
Hi @ksooad,

What version of Angular are you using? I believe newer angular/typescript can use `resolveJsonModule`.

We certainly can modify our JSON import but this is the sort of thing that we are likely to break again in the future as that JSON require is completely valid in standard Node.js.

**Comment by ksooad** [comment]
Hi
We using 10.1.4 and has config `resolveJsonModule: true` in tsconfig.json

For success build application we use `@angular-builders/custom-webpack:server` and extend basic webpack.config.js  with:
`
module.exports = {
  resolve: {
    extensions: ['.ts', 'tsx', '.mjs', '.js', '.json'],
  },
};
`
I found default webpack config in angular with extensions for resolve function https://github.com/angular/angular-cli/blob/e22c196c32278dee78f56088613de51bbf826131/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L466

And now i think, this is not bug of newrelic.

Thanks for hint to look at angular/typescript specs

**Comment by michaelgoin** [comment]
No problem! I'll go ahead and close this out for now... but don't hesitate to reopen if you continue to have issues.
