### ISSUE TITLE
Leverage infinite tracing span batch functionality

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#521]
The ability to send spans in batching for infinite tracing was added just before we shipped initial support via `RecordSpanBatch`.

This can be leveraged in multiple ways. This will be obviously beneficial in backpressure situations where we wait for drain and need to start emptying the queue. I'm not sure if we want to be in always send a batch mode or cross over in backpressure situations. We probably don't want to keep both connections open.

If we do an "always batch" approach that can get complicated. Unless we sometimes send individuals to the batch endpoint?

Anyways, some discovery needed here but initial testing when this was first released showed some benefit for us.

**Comment by rr0214** [comment]
Closing this out until we see this as an issue
