### ISSUE TITLE
Official way to get instrumentation API handle w/o being tied to module load

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#523]
Currently, you have to call `API.instrument*` to get a a handle on the instrumentation/shim API. This is tied to the loading of a module.

We have had multiple instances (and at least one customer instance) where we want to write new (or augment existing) instrumentation not tied to a module-load. For example... when we write instrumentation via public plugin APIs.

Currently, the workaround has been to grab the shim/instrumentation API off the agent API. While this works, that is not an "official" API property and lumps all of these types of instrumentation together for logging, etc. and also limits what is available to a single "shim" type.

Ideally, this API would auto-generate the external module support metrics instead of require each module to do so.

**Comment by rr0214** [comment]
We can work on this together with this issue: https://github.com/newrelic/newrelic-node-apollo-server-plugin/issues/14#issue-690503176

**Comment by bizob2828** [comment]
I'm not sure this is a priority any longer. I get the request but the investment to solve may not be worth it
