### ISSUE TITLE
Limit log file size

### ISSUE THREAD

**Issue by animir** [newrelic/node-newrelic#536]
## Is your feature request related to a problem? Please describe.
Agent logs may grow huge. It causes `no disk space` error.

## Feature Description
Implement configuration option to limit log file size (e.g. Java agent has `log_limit_in_kbytes` config option)

## Describe Alternatives
Alternatively, log rotation can be configured on Operation System level.

## Additional context
There is a way to set less noisy log `level`, but it is just postponed issue.

## Priority
Nice to Have

**Comment by michaelgoin** [comment]
Hi @animir,

Thank you for the feature request!  We will keep track of this as we prioritize future work. In the meantime, we also welcome pull requests if you (or anyone else) wants to make an attempt to solve prior to the work being prioritized.

**Comment by michaelgoin** [comment]
Looks like Java has a size limit per above.

The .NET agent has built-in log rotation.

What do other agents do?

**Comment by rr0214** [comment]
We recommend you use the alternative you identified. This is not a current priority given our strategic direction.

**Comment by animir** [comment]
@rr0214 Sorry, not sure about your strategic direction. As a user, when I install newrelic agent I want some automation ready, otherwise I would use some other software like Prometheus. How many of newrelic users know about logs rotation? How many are aware of the issue with logs size? What kind of strategic direction does threaten newrelic users and lead to issues?
