### ISSUE TITLE
Reporting of ELU

### ISSUE THREAD

**Issue by cah-caleb-boyd** [newrelic/node-newrelic#544]
## Feature Description
Node recently added `performance.eventLoopUtilization`

It would be great to have this metric included automatically by the agent under "Node VMs"

## Additional context

[Docs](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_eventlooputilization_utilization1_utilization2)

**Comment by michaelgoin** [comment]
Hi @cah-calebboyd,

Thank you for the feature-request! We will keep track of this as we prioritize future work.

PR for reference: https://github.com/nodejs/node/pull/34938

**Comment by bizob2828** [comment]
still valid
