### ISSUE TITLE
Vulnerability due to usage of lodash.camelcase:4.3.0

### ISSUE THREAD

**Issue by Mohammad-sabbagh** [newrelic/node-newrelic#546]
[NOTE]: # ( ^^ the above usage is providing the bellow issue https://ossindex.sonatype.org/vuln/12e63c9c-b3f9-42d3-8541-dca1b72cad69 ^^ )

## Description

lodash node module before 4.17.5 suffers from a Modification of Assumed-Immutable Data (MAID) vulnerability via defaultsDeep, merge, and mergeWith functions, which allows a malicious user to modify the prototype of "Object" via __proto__, causing the addition or modification of an existing property that will exist on all objects.

https://ossindex.sonatype.org/vuln/12e63c9c-b3f9-42d3-8541-dca1b72cad69

**Comment by carlo-808** [comment]
Closing this as we'll update all our dev dependencies in a future release.
