### ISSUE TITLE
Fastify v3 "register" shim middleware

### ISSUE THREAD

**Issue by josteph** [newrelic/node-newrelic#555]
## Is your feature request related to a problem? Please describe.
Technically related to #336, but it is due to deprecation in `.use()` method within fastify v3.

## Feature Description
The `.use()` method seems already deprecated in fastify v3, therefore (CMIIW) this shim might not be working as intended when the user is using the v3 instead of v2, due to this only wraps the `use` field only
https://github.com/newrelic/node-newrelic/blob/3afb93029da66eaa0d173feab2562b4684daeb57/lib/instrumentation/fastify.js#L40

## Additional context
Comparing the fastify version:
v2:
https://github.com/fastify/fastify/blob/e3850c9f0936730fb2b8eaa084c78d8c3ca2ee57/fastify.js#L368

v3:
https://github.com/fastify/fastify/blob/80414553e0457e4fbdc27bce70849622e69c52a6/fastify.js#L447

## Priority
**Must have** for fastify v3 users.

**Comment by michaelgoin** [comment]
@josteph thanks for the heads-up!

**Comment by GreenGuy09** [comment]
Any plans on prioritizing this issues? I believe fastify v2 is going to be deprecated in January 2021

**Comment by michaelgoin** [comment]
@GreenGuy09 We don't currently have this prioritized. I'll raise the concern but can't make any guarantees at this point we'll make it by v2 deprecation.

Can you share where you saw that v2 is being deprecated in January?

Our instrumentation for fastify is very limited, so if someone wants to take a stab at adding instrumentation for the new supported method of adding middleware, it may not be too involved. Easy for me to say without having researched yet, though. Similarly, if it is straightforward and we end up with spare cycles prior to normal prioritization maybe someone will get to it.

Will keep you posted.

**Comment by GreenGuy09** [comment]
> @GreenGuy09 We don't currently have this prioritized. I'll raise the concern but can't make any guarantees at this point we'll make it by v2 deprecation.
> 
> Can you share where you saw that v2 is being deprecated in January?
> 
> Our instrumentation for fastify is very limited, so if someone wants to take a stab at adding instrumentation for the new supported method of adding middleware, it may not be too involved. Easy for me to say without having researched yet, though. Similarly, if it is straightforward and we end up with spare cycles prior to normal prioritization maybe someone will get to it.
> 
> Will keep you posted.

Deprecated is probably the wrong term - Looks like it will reach[ End of Life](https://medium.com/@fastifyjs/fastify-v3-released-da4601d79a5) on January 2021.

**Comment by michaelgoin** [comment]
Thanks!

Found this link in there which takes a bit less reading to find the deets for others looking: https://www.fastify.io/docs/master/LTS/

**Comment by nijotz** [comment]
I was researching this and made an [example app](https://github.com/nijotz/nr-test-apps/blob/master/fastify/index.js) for testing. I added cors middleware using [these docs](https://www.fastify.io/docs/latest/Middleware/). The `.use()` does throw an error in v3, but I don't think that function is supposed to be invoked. It looks like, to use middlewares, you require a module that will [add that `.use()` method back](https://github.com/fastify/fastify-express/blob/0abb50c462698a35f55a37aa43690694b5ecaac8/index.js#L19). The middleware used is "express-style" and our instrumentation seems to [catch it correctly](https://puu.sh/H0jfC/0a9ec08252.png).

**Comment by nijotz** [comment]
Oh and it looks like [we test all fastify versions >2](https://github.com/newrelic/node-newrelic/blob/f365080c2dd805829a8b837c6a8cf5baaa4c8f06/test/versioned/fastify/package.json#L11) in our versioned tests.

But I'm just documenting what I've found so far using a simple app. Let me research this some more and see what I find.

**Comment by nijotz** [comment]
Ahhh, I didn't enable fastify instrumentation with the feature flag, I see the issue now

**Comment by nijotz** [comment]
So if I remove the wrapping of fastify's `use` in our instrumentation, the middleware [seems to be reporting properly](https://puu.sh/H0lmx/8dd4d922a9.png) in the UI for version 3. And when I tested version 2 of fastify (2.0 and 2.15), [the middleware is not reported at all](https://puu.sh/H0loS/5648eeeb7e.png), regardless of whether the `use` function is wrapped. It seems that the anonymous middleware in this screenshot is the [route handler](https://github.com/newrelic/node-newrelic/blob/3afb93029da66eaa0d173feab2562b4684daeb57/lib/instrumentation/fastify.js#L32). I think that the middleware wrapping can be removed, which will not break anything for v2, and which will fix v3 and middleware will report correctly.

**Comment by josteph** [comment]
>  It looks like, to use middlewares, you require a module that will add that .use() method back. The middleware used is "express-style" and our instrumentation seems to catch it correctly.

This means we need to require `fastify-express` which requires `express` module within same fastify server. The author of `fastify-express` made this statement in the readme:

![image](https://user-images.githubusercontent.com/13672022/103164322-5c608880-483c-11eb-9371-b61220f2c421.png)

So in conclusion it might work temporarily by using `fastify-express` as workaround. 
But as some of us are integrating in enterprise companies, I personally think it's not really a good solution to invest in.

Thanks for the insight though @nijotz, Merry Christmas 🎄

**Comment by nijotz** [comment]
Ahhh, I see. Re-reading the documentation:

>From Fastify v3, middleware support does not come out of the box with the framework itself, but it's offered as an external plugin via fastify-express and middie.

So, middleware isn't even supported, and it recommends this plugin which does require the entire express module. That's probably why our instrumentation catches the middleware calls.

Regardless, it looks like if we remove the wrapping of `use` in our instrumentation, things will work properly for v2, it won't break v3, and if users follow the documented way of using middlewares with fastify v3, it will show up in the UI. I'll test `middie` here in a bit.

But I'm thinking just removing the `use` wrapping will support fastify v3 and be backwards-compatible with v2 since it wasn't doing anything there either.

**Comment by josteph** [comment]
Yes I also agree if it's about removing the `use` wrapping 👍

**Comment by nijotz** [comment]
PR up: https://github.com/newrelic/node-newrelic/pull/572

**Comment by nijotz** [comment]
Fixed in latest release (7.1.0)
