### ISSUE TITLE
Incorrect version in error message

### ISSUE THREAD

**Issue by pmacdougall** [newrelic/node-newrelic#557]
## Description

Error message [here](https://github.com/newrelic/node-newrelic/blob/main/index.js#L53) has version 8.0.0 hard coded in the message string but the conditional is checking for `'<10.0.0'`.

Seems minor, but much time was wasted trying to figure this out before I looked at the source code.

## Expected Behavior

Error message should accurately reflect the version that is being checked.

## Steps to Reproduce

Try running with node version < 10 but >= 8.0.0 and you will see the confusing message.

**Comment by carlo-808** [comment]
Thank you for pointing this out @pmacdougall ! Sorry it caused you some trouble. We'll get this fix in soon.

**Comment by nijotz** [comment]
PR up: https://github.com/newrelic/node-newrelic/pull/573
