### ISSUE TITLE
DOC ISSUE: Datastore Example Not Accurate

### ISSUE THREAD

**Issue by icpenguins** [newrelic/node-newrelic#564]
## Description
When following the documentation for the `Datastore` example using Cassandra, the reference to `_innerExecute` ([link](https://github.com/newrelic/node-newrelic/blame/main/examples/shim/Datastore-Simple.md#L20)) is not accurate. The documentation goes on later to provide a source link to the Cassandra line where `_innerExecute` should be found ([link](https://github.com/datastax/nodejs-driver/blob/master/lib/client.js#L355)). However, the code base has changed to the point that `_innerExecute` no longer exists making this documentation less effective at showing how best to instrument a datastore.

**Comment by carlo-808** [comment]
Good catch @icpenguins ! Thank you for bringing this up with us. We'll get this prioritized and work on it as soon as we can.
