### ISSUE TITLE
SQL Traces can be generated with invalid SQL ID

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#567]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

When the number of digits to generate a SQL ID was increased to reduce collisions, it intended to rely on `parseInt` to trim down to a valid Integer. At the time, we validated it resulted in a valid JavaScript number but it turns out `parseInt()` can return a value that is larger than `Number.MAX_SAFE_INTEGER` while mostly seeming fine.

When we send this value to the server, the trace gets dropped because the number is not a valid `long`.

Example query for reproduction: 

```
'select `createdAt`, `updatedAt`, `id`, `firstName`, `lastName` from `Employee` limit ?'.
```

Example of parseInt behavior:

```
> const intVal = parseInt('3785db4c90b40f8a', 16)
undefined
> intVal > Number.MAX_SAFE_INTEGER
true
```

We'll lose some precision but we can probably trim the hex string down to 13 digits to ensure the largest possible hex number is within the valid range of values.

**Comment by nijotz** [comment]
Fixed in latest release (7.1.0)
