### ISSUE TITLE
A MySQL EXPLAIN Should Wrapped with SQL Queries Similar to Other New Relic Agents

### ISSUE THREAD

**Issue by icpenguins** [newrelic/node-newrelic#568]
MySQL offers the ability to execute an `EXPLAIN ANALYZE` on a SQL query providing detailed results on how the query is impacting the database ([EXPLAIN ANALYZE](https://dev.mysql.com/doc/refman/8.0/en/explain.html)).

## Feature Description
In parity with other New Relic agents and documentation ([docs](https://docs.newrelic.com/docs/apm/apm-ui-pages/monitoring/view-slow-query-details)), MySQL queries should also have an `EXPLAIN ANALYZE` result published to New Relic for review in New Relic One ([blog](https://blog.newrelic.com/engineering/how-to-monitor-mysql/)). This functionality helps users manage and tune their MySQL database backends to meet SLAs for backend requests.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Blocker. Since this is the expected behavior of a New Relic Agent and there is visualization in place for it today, this is blocking customers which required this functionality to observe, troubleshoot, and improve their environments.

**Comment by rr0214** [comment]
Given our strategic direction, this is not a priority at this time.
