### ISSUE TITLE
startBackgroundTransaction does not destroy TraceSegments during handle execution

### ISSUE THREAD

**Issue by iskraL** [newrelic/node-newrelic#578]
## Description

We are using the NR node agent and we are having memory issues with `startBackgroundTransaction`. It creates `TraceSegments` and destroys them after the `handle` function is done. We have jobs that are long and include a lot of operations which leads to memory piling up all the way up until everything is done.

## Expected Behaviour

We would expect memory to be released regularly and not all at once in the end.

## Steps to Reproduce

The described behaviour can be observed in [this sample project ](https://github.com/iskraL/new-relic-demo). If you take a few heap dumps from different moments of the execution you will see that TraceSegments are constantly increasing.

<img width="1440" alt="Screenshot 2021-01-12 at 8 35 06" src="https://user-images.githubusercontent.com/24715312/104294906-78188f80-54c8-11eb-9a15-c5b0dc70fbb0.png">

## Your Environment

 Node version: 14.5
 NR version: 6.13.2

**Comment by michaelgoin** [comment]
Hi @iskraL,

Does the transaction run that whole time?

The segments are kept around for the potential to capture a transaction trace. Whether or not a trace is captured is unknown until a transaction has completed. Part of this is also key to the parenting of segments/spans and keeping transaction state. While this can definitely not be desired (if not intending to capture a transaction trace and no distributed tracing) it is pretty fundamental to how data is currently captured. That being said, if your situation is that the transaction is running the whole time but you do not care about transaction traces, we can capture that ask as a feature request.

If your transactions are ending prior to this point but the memory is sticking around, then that is potentially a different issue. Based on your description, it sounds like this is not the case and you actually just have very long-lived transactions that process a lot of commands.

Thanks,

Michael

**Comment by iskraL** [comment]
Hey @michaelgoin, 

We do have very long running transactions. I agree that as this is how segments are designed to work, the bug report is not valid. Thanks for your input!
