### ISSUE TITLE
Automate Third Party Notices check/updates

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#591]
Extra language may prove painful. We can potentially look to see if the extra language can be removed.

Would consider if this should be a per PR merge VS once a release action. If per PR, we could have it auto-submit a PR for updates so some human intervention can easily take place.

[after we remove cert bundle]

**Comment by bizob2828** [comment]
we manually paste in the optional dep of @newrelic/native-metrics, so we will need to make sure this gets included
