### ISSUE TITLE
Automate roll-back functionality

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#592]
This likely needs to be broken up into individual pieces.

**Comment by bizob2828** [comment]
rollback described here: https://source.datanerd.us/NodeJS-agent/nodejs_agent/wiki/Rollback. should be ported to public github

**Comment by michaelgoin** [comment]
See manual release documentation (internal) in the team release documents: https://docs.google.com/document/d/1nMw-TJau7E9qtaUq_u2ERo64e-aH4bDvxjSpKuwLhSk/.

While we typically can do a fix-forward release, in certain cases we will do a full rollback release removing changes from the prior (Option 2). This should be automated so it can be efficiently and safely completed when the need arises.
