### ISSUE TITLE
Automate JSDoc API docs updates

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#593]
We have an existing script used to do manually. May be able to just hook that up via GitHub actions.

See additional info in Node agent release documentation.

## Feature Request
 * On release, re-generate and publish jsdoc API docs
 * add eslint rules to proactively lint the jsdoc in PRs, [jsdoc eslint plugin](https://www.npmjs.com/package/eslint-plugin-jsdoc)

**Comment by bizob2828** [comment]
Docs get published as GH pages to here http://newrelic.github.io/node-newrelic/docs/Shim.html#record

**Comment by michaelgoin** [comment]
size: medium
