### ISSUE TITLE
Allow multiple identical keys in labels definition

### ISSUE THREAD

**Issue by Slashgear** [newrelic/node-newrelic#597]
## Is your feature request related to a problem? Please describe.

For my project, I wanted to add labels on my APM project in order to simplify my queries.
We decide to add a `Team` label for each project in order to be able to filter project by teams.
Some of our project are "multi-team" project, so we want to be able to add many `Team` label for the same ressource.

For example:

```yml
Team: A
Team: B
```

This is completely possible in the Web UI and in Php agent configuration but it is not possible for NodeJS agent.

I took a look at the code implementation of labels in this agent and I understood that it is not possible without a refacto.

As we manage many projects with many different deployments, we do not want to manually maintain this label list in the interface.

The data type currently used to represent labels in the current agent is the `Map` Js which does not allow key duplication.

## Feature Description
A clear and concise description of the feature you want or need.

Be able to define labels with arrays to let user define more than one value for the same label key.

```js
export default {
  labels: [
    { Team: 'A'},
    { Team: 'B'}
 ]
}
```

## Describe Alternatives

Maybe a more elegant way to deal with multiple values:

```js
export default {
  labels: {
    Team: ['A','B']
 }
}
```

or

As we can use a string to define labels (this does not work currently because string is parse to `Map`) 

```js
export default {
  labels: `Team:A;Team:B`
}
```

## Additional context

- Take a look at https://github.com/newrelic/node-newrelic/blob/main/lib/util/label-parser.js implementation

## Priority

Really Want

**Comment by carlo-808** [comment]
@Slashgear thank you for the feature request! We will take a closer look at this request and prioritize it with our Product Manager. If you're feeling ambitious, PRs are welcome to add this feature!

**Comment by bizob2828** [comment]
It's worth noting our specification for labels reads as such 

```
 If a given label type is specified multiple times, then only the value associated with its last occurrence **MUST** be used.
```
