### ISSUE TITLE
Add a 'no drain event fired' supportability metric for infinite tracing

### ISSUE THREAD

**Issue by carlo-808** [newrelic/node-newrelic#600]
The agent should have a new supportability metric for infinite tracing indicating when back-pressure is encountered but a drain event is never fired.
Possible metric name: `Supportability/InfiniteTracing/Drain/NotEmitted`

**Comment by michaelgoin** [comment]
It may not be worth the effort trying to detect if it didn't fire... (how long would you wait, managing timers, etc.) but perhaps a metric (or at least logging) that we are starting to wait for a drain which we can then use to compare against actually hitting drain via our drain duration metric would be enough.

**Comment by michaelgoin** [comment]
Given we've resolved our main issues and discovered good patterns for finding issues, I don't think we need this anymore. If a need comes up again, we can do then.
