### ISSUE TITLE
Add log message for no config file found

### ISSUE THREAD

**Issue by linbaker** [newrelic/node-newrelic#612]
## Is your feature request related to a problem? Please describe.

Currently `!config` results in a message 'Module not enabled in configuration; not starting.' 

```
if (!config || !config.agent_enabled) {
      logger.info('Module not enabled in configuration; not starting.')
```

https://github.com/newrelic/node-newrelic/blob/main/index.js#L79

This can be misleading and makes troubleshooting more difficult when it could be two very different issues.

## Feature Description

Add a log message similar to what the Ruby agent has:

```
 NewRelic::Agent.logger.warn(
            "No configuration file found. Working directory = #{Dir.pwd}",
            "Looked in these locations (based on #{based_on}): #{candidate_paths.join(", ")}"
```

* https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/configuration/yaml_source.rb#L82

It may be worthwhile to include next steps as the missing 'app_name' log message does:

* https://github.com/newrelic/node-newrelic/blob/main/index.js#L139

For example:

`New Relic requires a newrelic.js file in the root directory of your app or set environment variable NEW_RELIC_NO_CONFIG_FILE=true` 

But it may be difficult to include all possible cases, for example if using 'NEW_RELIC_HOME' rather than having 'newrelic.js' in the root directory. 

## Describe Alternatives

Current troubleshooting strategy when logs show 'Module not enabled in configuration; not starting.'  :

* Check newrelic.js for `agent_enabled: false`
* Confirm no New Relic environment variables are present that could be disabling the agent with the methods here: https://discuss.newrelic.com/t/node-js-troubleshooting-framework-configuration/119977#post_1:~:text=If%20you%20used%20New%20Relic%20environment,vars%20are%20correctly%20loading%20in%20time
* Test enabling the agent in your start up script which will override any other configuration, for example: `NEW_RELIC_ENABLED=true node server.js`
* Use the environment variable 'NEW_RELIC_NO_CONFIG_FILE' to skip looking for the agent configuration file and use environment variables to set configuration:
https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#no_file

* Set path to directory containing newrelic.js the environment variable 'NEW_RELIC_HOME':

https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#home

**Comment by michaelgoin** [comment]
This is what gets logged to console.error() when there is no config file at all:

```
Unable to find New Relic module configuration. A base configuration file
can be copied from /node-newrelic/newrelic.js
and put at /expressApp/newrelic.js or
/expressApp/bin/newrelic.js.
If you are not using file-based configuration, please set the environment
variable `NEW_RELIC_NO_CONFIG_FILE=true`.
```

In fact it gets logged twice, for some reason...

And then the log message referenced here is logged below that to stdout since the logger will not be configured to a file path in this case:

```
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"C02T62BKGTDY","pid":64410,"time":"2021-02-25T00:01:31.047Z","msg":"Using New Relic for Node.js. Agent version: 7.1.2; Node version: v14.15.5."}
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"C02T62BKGTDY","pid":64410,"time":"2021-02-25T00:01:31.051Z","msg":"Module not enabled in configuration; not starting."}
```

I'm guessing we/customers are grepping for the agent logs and skipping/missing the other warning. And then getting mislead by the vague language.

**Comment by michaelgoin** [comment]
Logs multiple times because the logger also loads the config.

**Comment by berndartmueller** [comment]
Is there a way to disable this log message (e.g. while running automated tests)?

**Comment by carlo-808** [comment]
hi @berndartmueller , I believe you can disable all logging when you run automated tests with this config:
```
logging: {
  enabled: false
}
```
Are you running automated tests without a configuration file and just using environment variables? If that is the case, the agent should not log this message in the latest version of the agent. If no, configuration file is found, it will try to load the agent from environment variables.

**Comment by berndartmueller** [comment]
@carlo-808 I already had logging disabled via the config file. 

Turned out I had to remove `process.env.NEW_RELIC_NO_CONFIG_FILE = 'true';` from my Jest setup file. Now no logs are shown anymore while running automated tests.
