### ISSUE TITLE
Disable options for instrumented modules in newrelic.yml

### ISSUE THREAD

**Issue by drobnikj** [newrelic/node-newrelic#614]
## Feature Description
Added option into `newrelic.yml` config, which would disable instrumentation of required module in the app. There is no easy way(except one describe bellow), how you can disable the instrumented module. It is possible for example in Ruby agent([see the option to disable mongo](https://docs.newrelic.com/docs/agents/ruby-agent/frameworks/mongo-instrumentation)).
The structure can be done the same as in Ruby or any other way.
```
{
 disable_mongo: true,
 disable_redis: true,
 ...
}
```

## Describe Alternatives
I found one workaround [here](https://discuss.newrelic.com/t/feature-idea-using-mongoose-cursors-memory-leaking-very-quickly/49270/17). But it didn't work if the required module in not in your code but in code of some dependency package.

## Priority
Really Want

**Comment by michaelgoin** [comment]
Thank you for the feature-request. We'll get this in front of the PM for consideration and prioritization.

We have an experimental branch where we have played with this concept but have not yet prioritized turning into official support. One thing worth noting as we consider this support... turning off any specific piece of instrumentation **may** currently cause transaction state loss. So the feature would need to come with some clear warnings / safety measures.

**Comment by bizob2828** [comment]
This is still valid and we have talked about doing this a lot more recently. We need to get this prioritized as most other language have this ability

**Comment by bizob2828** [comment]
We have added this [here](https://github.com/newrelic/node-newrelic/blob/main/lib/config/default.js#L1392).  This is a use at your own risk as context may not be propagated accordingly
