### ISSUE TITLE
Potential memory leak interaction with global-agent

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#615]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

A customer is seeing a potential memory leak when [global-agent](https://www.npmjs.com/package/global-agent) is used and configured with proxy URLs (HTTP_PROXY/HTTPS_PROXY env vars).

This goes away when `GLOBAL_AGENT_FORCE_GLOBAL_AGENT` is set to false.

When not false, global-agent will swap out the options.agent with the global agent. https://github.com/gajus/global-agent/blob/master/src/utilities/bindHttpMethod.js#L35-L37

It is also worth noting this is impacting our own connect cycle and harvest requests. You can easily see that by not setting the proxy vars but still tracking impact to the agent. This means our normal keep-alive agent will not be reused.

I'm not sure if this is an instrumentation interaction or something impacting our harvest code, for example.

Unfortunately, because it does impact our agent calls you have to get a proxy up and running correctly. I have not yet successfully reproduced this issue so am entering a GitHub issue for more in-depth focused exploration.

The good news is there is a workaround (setting force agent to false) and this is the first this particular interaction has come up.

This Jira has the repro attached as well as the associated support ticket: https://newrelic.atlassian.net/browse/GTSE-7340.

**Comment by bizob2828** [comment]
It's worth noting I whipped up a Dockerfile that wraps the newrelic proxy module, [docker proxy server](https://github.com/bizob2828/node-proxy-server).  You could use this to spin up a proxy server locally within a docker container

**Comment by bizob2828** [comment]
I could not repro issue, more comments on [GTSE ticket](https://newrelic.atlassian.net/browse/GTSE-7340?focusedCommentId=927583).  I'm goin to un-assign and put back in backlog until we can get more information

**Comment by bizob2828** [comment]
Closing this issue. If customer reports more info on how to reproduce we can reopen

**Comment by nomiddlename** [comment]
I can confirm that we saw this behaviour in our application running in a container on AWS ECS, using Node 16, newrelic@8.7.1, global-agent@3.0.0, and express@4.17.2. Setting the env var mentioned above got rid of the leak for us, with no side-effects so far. Just thought I'd leave a comment for any other google searchers like me that are trying to track down this problem. It might be worth adding this tip to the [troubleshooting memory in node](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/troubleshooting/troubleshooting-large-memory-usage-nodejs/) page.
<img width="641" alt="Screen Shot 2022-03-24 at 9 09 42 am" src="https://user-images.githubusercontent.com/83909/159808599-3897ea9e-1392-4c7a-a665-a2e826c08a87.png">

**Comment by rjoaopereira** [comment]
I filed the original bug report. I didn't find any other solution apart from that one. I can say, at least, that the workaround never gave any problems.
