### ISSUE TITLE
CPU % (VM / Instance Summary) showing > 100% when should not be possible

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#617]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Customer is noting seeing > 100% CPU. 

Looking at graphs, seems sometimes as high as 200%+. 

We appear to be attempting to handle multiple core's here: https://github.com/newrelic/node-newrelic/blob/main/lib/sampler.js#L72-L110 so reasonably confident its not that. Looking at timeslice metrics via NRQL, nothing seems like it would result in these large percentages.

```
FROM Metric Select metricTimesliceName, newrelic.timeslice.value where (metricTimesliceName like '%CPU/System/util%') or (metricTimesliceName like '%CPU/User/util%') and entity.guid = '[insert here]' LIMIT MAX 
```

We do have some potential time resolution issues using Date.now() (instead of hr time) which I'm wondering if may be accounting for some of the odd min values (9.480000153416768E-5). Perhaps those are causing calculation issues for the queries? Will need to dig deeper into what the UI on teh summary (instances) and VM pages are using to track down further.

Here's the internal support Jira: https://newrelic.atlassian.net/browse/GTSE-7535.

**Comment by carlo-808** [comment]
Closing issue as the CPU utilization chart/table in the NROne Entity Summary page is reporting CPU Usage as expected and the Agent is reporting CPU usage up to New Relic specifications. The CPU utilization chart/table is based on the metric, `apm.service.cpu.usertime.utilization`, which is generated off the Node Agent supportability metric `CPU\User time`. `CPU\User time` does not take cpu cores into account and is calculated using the Nodejs method, [process.cpuUsage()](https://nodejs.org/api/process.html#process_process_cpuusage_previousvalue). If the node application/entity in question is running on a multi-core system, the CPU utilization chart may show values > 100%.
