### ISSUE TITLE
Generating release notes can generate for the next day (timezone)

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#632]
Turns out the date format used to get the nice setup is far enough ahead that when releasing in the afternoon you can end up with the next day.

It would be nice to resolve this, ideally without a heavyweight framework like moment.

**Comment by bizob2828** [comment]
We talked and it's prob good to just default to PST for generating date

**Comment by bizob2828** [comment]
This occurs in `bin/prepare-release.js` in `updateReleaseNotesFile`
