### ISSUE TITLE
(node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by arnav1991** [newrelic/node-newrelic#652]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
EventEmitter memorey leak warning coming in logs and memory leak is happening. 

[NOTE]: # ( Describe the problem you're encountering. )

As searched by our team we were able to find new relic node js module was causing mem leak. after removing it memorey graph became flat.
We were receiving warning in logs

`(node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit`

After checking new-relic files we found that new-relic is listening to 'close' event.

[NOTE]: # ( Tell us what you expected to happen. )

Memory does not increase over time.

[NOTE]: # ( Provide any other relevant log data. )

```
2021-02-28 19:17:41.238 | Old models hash is same as new hash so not running sync. hash: 

2021-02-28 19:17:41.238 | Express server listening on port 

2021-02-28 19:18:33.126 | (node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
```

## Steps to Reproduce

[Import](url) new-relic
![Screenshot from 2021-03-02 00-24-18](https://user-images.githubusercontent.com/26572100/110084955-8a22fa00-7db6-11eb-8021-b45f8a7e84f4.png)
![Screenshot from 2021-03-02 00-17-22](https://user-images.githubusercontent.com/26572100/110084961-8b542700-7db6-11eb-8bf7-853c261fef5d.png)

after removing new relic graph is like this now
![Screenshot from 2021-03-02 23-28-09](https://user-images.githubusercontent.com/26572100/110086232-21d51800-7db8-11eb-909c-334542a318d2.png)

## Your Environment
Production

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Node version: v8.12.0
* ex: Operating System and version: Linux docker
[](url)

**Comment by carlo-808** [comment]
Hi @arnav1991 , thank you for filing this issue. Can you please provide more details around the issue? What version of the agent are you running? I noticed that you are using Node v8.12.0. The Node Agent currently does not support a node version <= 10. Could you try upgrading your node version to at least 10 to see if that clears up the issue? Memory leak issues can be tricky to track down and it might be better if you engage with [New Relic Support](https://github.com/newrelic/node-newrelic#support) and provide them with more detailed information about the application you are running.

**Comment by arnav1991** [comment]
Hi @carlo-808 Thank you for quick response. We are using newrelic version **6.11.0**. 
Sure will update the node version and test it.
There are multiple 'close' events newrelic is listening to in node-modules. This warning is coming as newrelic is listening to 'close' event multiple times and maximum MaxListeners for an event can only be 10 according to event-emitter docs

**Comment by bizob2828** [comment]
Closing this issue and if @arnav1991 still has issue can follow the New Relic support route

**Comment by k2xl** [comment]
Any updates? still seeing this today in 2023

**Comment by mrickard** [comment]
@k2xl If you're still seeing this, can you open a ticket with New Relic Support? They'd be able to collect the right version, runtime, and configuration information and get it surfaced internally.

**Comment by wenkangjing** [comment]
this needs to be fixed. I am seeing it in Nov 2023. Can someone from New Relic provide an update?

**Comment by mrickard** [comment]
@wenkangjing Are you able to open a ticket with New Relic Support? They'll be able to collect the contextual information that would help us reproduce this.
