### ISSUE TITLE
Remove host from identifier field in collector handshake

### ISSUE THREAD

**Issue by carlo-808** [newrelic/node-newrelic#654]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
We are noticing slowness for MTQW queries from node agent data with a `connectPayload.identifier` value populated. Node agent is generating an identifier based on `nodejs` + `host` + `appName`.
https://github.com/newrelic/node-newrelic/blob/6f631ba9de995a9d3fb2dce4fed3282431c94599/lib/collector/facts.js#L70
The `identifier` field is not required and the backend will generate a usable identifier for the collector from other data sent in handshake.

Alternatively we can remove `host` from the identifier as well.

From TDP: 
>what happens in this particular instance is that we're detecting that the connection is originating from a host with a "dynamic hostname" (that looks like a UUID pattern) and instead of creating a separate agent instance for each connection, we treat them as one - this will mean that the customer loses the ability to see per-host breakdowns, but it's intentional - we do this to protect ourselves from inundating the system with rapidly churning hostnames 
by putting the hostname in the identifier field, you're circumventing that protection

**Comment by michaelgoin** [comment]
It looks like to avoid the customer situation that prompted this change, we'll still need to keep the 'identifier' field. But we do need to remove the host name so the New Relic server won't do bad things and slow down things for customers.

Customer background on problem: https://github.com/newrelic/node-newrelic/commit/c0901e6807a50ac3969d79ab48c31c8e0232a6b5#r18254962

> So, it sounds like the previous behavior was to assume that if there were multiple comma-separated app names, then the first app name given would be unique per-host.
>In our case we were using multiple agents per host and our first app name happened to be the /same/ for all the agents.
>This change creates a new identifier that uses all the app names as part of the unique identifier, not just the first one.

And from our internal server comments...

```
// Note that by using the first app name, and not all of the app names,
// agents cannot connect "a;b" and "a;c" at the same time.
//
// Agents that wish to avoid this limitation should provide an
// 'identifierOverride' that contains all of the app names.
//
```

Chatting internally, it sounds like the host will still be used as a part of the key that is used to determine if two agent connections are the same real agent or a separate one. As such, we should be safe to remove the host but we'll want to keep the full app names / send the identifier to keep from breaking at least the one customer.

See internal slack thread here: https://newrelic.slack.com/archives/C0511B24H/p1614618798048500
