### ISSUE TITLE
Fully remove cert bundle feature-flag

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#666]
* Fully remove feature flag introduced with: https://github.com/newrelic/node-newrelic/issues/664 by default.
* Fully remove cert bundle.
* Remove now unnecessary license text from third party notices.

Major version bump as removes flag fully so allows no configuration. Prob do with the Node 16 support effort?

## Background

We intend to remove bundling of the cert bundle. We have no way to truly know if any customers are currently dependent on the bundle so we are going to handle gradually. We can tell when we include the bundle, though, via support metric recently added.

1. Introduce feature flag where customers can experiment turning off w/ some messaging
2. Turn feature-flag off by default (major release)
3. **Remove feature-flag altogether (major release)**

**Comment by michaelgoin** [comment]
https://issues.newrelic.com/browse/NR-33407

**Comment by bizob2828** [comment]
closing as we are tracking in jira
