### ISSUE TITLE
Better Node 16/ EOL Node 10

### ISSUE THREAD

**Issue by rr0214** [newrelic/node-newrelic#687]

**Comment by michaelgoin** [comment]
We know the versioned test running has issues, due to npm 7. This is resolved with the latest test-utilities version by using the `--all` flag.

Unsure yet of any issues specific to functionality/instrumentation for parity.

**Comment by bizob2828** [comment]
We'll want to address this https://github.com/newrelic/node-newrelic/issues/756

**Comment by bizob2828** [comment]
Check to see if core Node.js bug has been fixed for LTS https://github.com/newrelic/newrelic-node-apollo-server-plugin/issues/81

**Comment by bizob2828** [comment]
We should consider these tidy up issues:
 * https://github.com/newrelic/node-newrelic/issues/763
 * https://github.com/newrelic/node-newrelic/issues/764
