### ISSUE TITLE
Research multiple invocations of wrappedResEnd/Response.prototype.end

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#715]
It appears that at least some early versions of Hapi (or at least our early Hapi version versioned tests) can result in multiple invocations of our wrappedResEnd function from our http instrumentation.

As a part of a different PR, I put in a safety check there to avoid extra work (and avoid interacting with error fields that will be cleared after transaction end). https://github.com/newrelic/node-newrelic/pull/712

We should verify if:
  1. This is normal expected behavior (and or not normal but should be fine in the wild) and we just didn't protect against it prior. OR
  2. If this is specific to Hapi and certain versions OR
  3. If we've accidentally introduced an issue anywhere that would result in an extra invocation.

Each time I saw this it was invoked exactly twice. This was with the hapi-pre-17 render tests.

**Comment by jsumners-nr** [comment]
Should we really invest time in this issue? It is describing an issue with "early versions of Hapi", i.e. versions less than 17. Hapi is currently at version 21 and their LTS policy (https://hapi.dev/policies/support/ https://web.archive.org/web/20230924164418/https://hapi.dev/policies/support/) clearly indicates that v17 is long out of support.

attn: @bizob2828

**Comment by jsumners-nr** [comment]
Closing this as the issue relates to long outdated versions of Hapi. Please open a new issue if this is encountered in a recent release.
