### ISSUE TITLE
Add function transationHandler.ignoreApdex()

### ISSUE THREAD

**Issue by drobnikj** [newrelic/node-newrelic#724]
## Feature Description
The simple function `ignoreApdex()` would be welcome for node js agent. [It is available for .NET agent](https://docs.newrelic.com/docs/agents/net-agent/net-agent-api/ignore-apdex/).
ATM, there is no easy way to dynamically(in the code) ignore some transaction from apdex. It can be useful in cases, where a longer response time is expected.

## Priority
Nice to Have

**Comment by michaelgoin** [comment]
Hi @drobnikj,

Thank you for the feature-request and for linking to relevant .NET docs. That is very helpful.

**Comment by Prashansa-K** [comment]
@michaelgoin Do we have any ETA on this? This is a pretty useful feature and much needed.

**Comment by rrjohnson85** [comment]
Is there any update on this feature request?

**Comment by bizob2828** [comment]
This was added in [11.16.0](https://github.com/newrelic/node-newrelic/blob/main/NEWS.md#v11160-2024-04-29)
