### ISSUE TITLE
Copyright not declared in license file

### ISSUE THREAD

**Issue by wes-novack** [newrelic/node-newrelic#744]
The Copyright information in the license file is currently blank. Please update to include the Copyright holder information.

This is needed for open source licensing compliance and auditing.

**Comment by michaelgoin** [comment]
Hi @wes-novack,

We can get that updated. Thanks for the heads-up.

**Comment by michaelgoin** [comment]
Going to confirm with legal (I'm not an expert here), as we may not actually want to update this.

You can see Google's open source guidance here: https://opensource.google/docs/releasing/preparing/#license-file which explicitly recommends *NOT* touching the template.

> Why shouldn't I edit the template in the Apache License? The "LICENSE" file is supposed to be our inclusion of an exact copy of https://www.apache.org/licenses/LICENSE-2.0.txt as required by section 4(a) of the Apache 2 license, so we shouldn't modify it in any way, such as by adding our copyright notice. Also, the Appendix (lines 179-202) represents a notice to third-parties informing them of how *they* should apply the Apache 2 license to their own works, so inserting our copyright notice in place of the template text renders those instructions incorrect. Many projects insert copyright notices into their LICENSE file at line 190 because this is a common and understandable misinterpretation of the license's instructions. We should attempt to fix this wherever we find it, particularly for first-party projects.

**Comment by wes-novack** [comment]
Ahh interesting! I hadn't seen this before. Thanks for sharing.

**Comment by michaelgoin** [comment]
@wes-novack Got guidance that we should be using the license file as-is without modifying. As such, we won't be moving forward with this. But very much appreciate the heads-up as I did not know either-way.

Thanks!
