### ISSUE TITLE
Use symbols instead of non-enumerable property definitions

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#746]
## Is your feature request related to a problem? Please describe.

We currently have a few mechanisms by which we store data on objects external to the New Relic agent for context tracking and similar (hopefully we can get rid of some of these at some point).

To prevent getting serialized into customer's logs (or in some cases removed), we use non-enumerable property definitions. That can add overhead (or at least did at one point) but also adds some complexity and there's still some chance for being serialized or even deleted/overwritten by libraries when `hide_internals` is false.

Example: https://github.com/newrelic/node-newrelic/blob/main/lib/shim/shim.js#L1752-L1774

By converting these to use symbols (`Symbol('my item')`), we should still be able to avoid being serialized for most cases, avoid forking code or needing the `hide_internals` configuration, and will avoid customers/frameworks accidentally overriding our values.

Looking for usages of 'hide_internals' should find most usages but I'd also do a general scan for property definitions to see if there are others that need to be manually updated (or even other assignments not using the property descriptor but writing to objects New Relic does not maintain control over such as wrapped functions).

**Comment by michaelgoin** [comment]
```
_slowSetInternalProperty x 2,503,661 ops/sec ±0.70% (87 runs sampled)
Standard x 118,715,710 ops/sec ±0.53% (88 runs sampled)
SYMBOL x 118,695,494 ops/sec ±0.63% (91 runs sampled)
Fastest is Standard,SYMBOL
```

**Comment by michaelgoin** [comment]
We are also separately using defineProperty in several places. While the gets/sets are fine after initial call, defineProperty itself is slow on invocation. We should see if we can avoid these for places invoked frequently and maybe even see if we truly need any of them.

We should also consider if we can clean up special properties we write (via whatever means) once we are done using them.

**Comment by michaelgoin** [comment]
We've decided to defer this work until we've looked at other async state tracking improvements.

**Comment by bizob2828** [comment]
Add this to the AsyncLocalStorage feature in jira

**Comment by bizob2828** [comment]
well the syncing did not work. manually created this jira https://issues.newrelic.com/browse/NEWRELIC-4422
