### ISSUE TITLE
Impossible to disable early logging

### ISSUE THREAD

**Issue by nikolaik** [newrelic/node-newrelic#755]
## Description

Since #636 it is no longer possible to mute newrelic log messages about possible configuration errors when you have `NEW_RELIC_NO_CONFIG_FILE=true` or simply don't use config file, since the logger is only initialized with defaults before the log statement is hit. Or am I missing something? If not, being flooded with irrelevant log messages when running your app tests is good. Not having to wrap all newrelic code in some conditionals is also good.

## Expected Behavior

Allow disabling the log message `NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables` here: https://github.com/newrelic/node-newrelic/blob/6e37c0058f67708d901b268726e12389de873702/lib/config/index.js#L1639

Could it be optionally logged if `!isTruthular(NEW_RELIC_LOG_ENABLED)` is true?

## Steps to Reproduce

Set the following env vars and require newrelic in your project

```
NEW_RELIC_ENABLED=false
NEW_RELIC_NO_CONFIG_FILE=true
NEW_RELIC_LOG_ENABLED=false
NEW_RELIC_LOG_LEVEL=fatal
```

Observe the log message appear

**Comment by rr0214** [comment]
Given our priorities, we likely will not have a chance to tackle this anytime soon.
