### ISSUE TITLE
Node 16 no GC/Eventloop data per instance 

### ISSUE THREAD

**Issue by artur-ma** [newrelic/node-newrelic#761]
## Description

After upgrading NodeJs in our container 14 => 16, we see no EventLoop/GC data reported

## Your Environment

Alpine image with node 16.2.0 inside k8s cluster
node-newrelic: 7.3.1

## Additional context

![image](https://user-images.githubusercontent.com/57314588/118969702-0bca0300-b976-11eb-8f5a-6b0a967155ea.png)
![image](https://user-images.githubusercontent.com/57314588/118969745-18e6f200-b976-11eb-90df-5a10c9434adc.png)

**Comment by artur-ma** [comment]
Unfortunately we can not provide more info, we rolled back to node 14 since we can run on prod without these metrics

**Comment by MichielDeMey** [comment]
We ran into the same issue, no pre-built binaries are available for Node 16 yet.
We added a new build step to our Docker build to compile the native dependency on Alpine and now we're receiving those metrics on Node 16.

**Comment by michaelgoin** [comment]
Closing out as seems to be a local build situation and pre-built Node 16 binaries now exist.

**Comment by jordigh** [comment]
We don't support node 18 yet, but it's good to know that trouble can arise. Just to confirm, have you been able to install [@newrelic/native-metrics](https://www.npmjs.com/package/@newrelic/native-metrics) on Node 18?

**Comment by jtarchie** [comment]
We did. Installing the equivalent of `build-essentials` on the `alpine` image got rid of the warning `native-metrics` gave. It just does not appear to be working. ☹️

**Comment by jordigh** [comment]
@jtarchie We have just started some work on supporting Node 18. Could I trouble you with opening a new issue with whatever relevant output you can show that demonstrates the native metrics package is built and installed for Node 18?
