### ISSUE TITLE
Replace url.parse with url.URL

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#763]
## Feature Description
`url.parse` is in legacy stability and is not recommended.  All instances of `url.parse` should be replaced with `new url.URL` and use the appropriate properties

## Describe Alternatives
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?

## Additional context
We will be doing a semver major to drop v10, it would be good to up our references during this project.  There aren't many uses of this and it's just a tidy up task

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have]

**Comment by bizob2828** [comment]
This change may be a little too risky due to the uncertainty of the data getting passed to `url.parse`.  The API behavior between `url.parse` and `new URL` differ in 2 big ways:

 * If input is a relative bath then a base url is required to properly parse the URL.  This is where it's very risky as we may not have the fully qualified URL as this time.
 *  the 2nd arg to `url.parse` would [parse the querystring](https://github.com/nodejs/node/blob/master/lib/url.js#L273), so we'd have to re-implement this behavior ourselves.

Also, as of Node.js v14.17.0, `url.parse` was upgraded from stability 0 - deprecated to stability 3 - legacy so the risk of this getting removed in the future is probably is much lower.  I will move this ticket to the backlog in case we want to address in the future as there are still some risks using url.parse from a security perspective, most notable this [host spoofing](https://hackerone.com/reports/678487) bug.

**Comment by rr0214** [comment]
Node 14 will keep url.parse as legacy. This is no longer an urgent issue.
