### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by SamiraHuber** [newrelic/node-newrelic#774]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I currently get the error when starting newrelic:

Critical dependency: the request of a dependency is an expression
07:17:08 app.1      |  wait  - compiling...
07:17:08 app.1      |  warn  - ./node_modules/newrelic/lib/config/index.js
08:55:24 app.1      |  ./node_modules/newrelic/lib/shimmer.js
08:55:24 app.1      |  Critical dependency: the request of a dependency is an expression
08:55:24 app.1      |  ./node_modules/newrelic/lib/shimmer.js
08:55:24 app.1      |  Critical dependency: the request of a dependency is an expression
08:55:24 app.1      |  ./node_modules/newrelic/lib/shimmer.js
08:55:24 app.1      |  Critical dependency: the request of a dependency is an expression
08:55:24 app.1      |  ./node_modules/newrelic/lib/config/index.js
08:55:24 app.1      |  Critical dependency: the request of a dependency is an expression
08:55:24 app.1      |  ./node_modules/newrelic/lib/shim/shim.js
08:55:24 app.1      |  Critical dependency: the request of a dependency is an expression
08:55:24 app.1      |  ./node_modules/newrelic/lib/proxy/grpc.js
08:55:24 app.1      |  Critical dependency: the request of a dependency is an expression

## Your Environment

- newrelic version: 7.2.1
- node: v10.15.0
- react
- macOS

**Comment by carlo-808** [comment]
Hi @SamiraHuber , thank you for the issue submission. Could you give us a little more detail on the setup in this case? It looks like you are using react. Are you compiling the application with babel before running? Is this error coming from the server-side of your react application?

**Comment by SamiraHuber** [comment]
- it comes on the react application when starting the client with npm.
- we include newrelic with `import * as newrelic from 'newrelic';` in the root .jsx file as first import.
- we use the next.js-framework
- it happens for both applications we have with this configuration
- the error occurs every time the application compiles (also on hot reload)

If you need any further information just ask!

**Comment by carlo-808** [comment]
Thank you for that context, @SamiraHuber. It looks like you are importing newrelic into a jsx file which eventually gets rendered into html for the user. Am I understanding that correctly? I think you want the server side portion of next.js to be instrumented by the agent. The agent does not support front end instrumentation and the node agent technically does not support Next.js at this time. In our discussion forums, some folks have posted some ways to instrument next.js. Here's a post that may be helpful to you: https://discuss.newrelic.com/t/feature-idea-is-there-a-guide-to-instrumenting-a-nextjs-application/96169/11
It looks like they run the agent with this command when starting their next.js app:
`node -r newrelic node_modules/.bin/next start`

**Comment by SamiraHuber** [comment]
Yes exactly. 
It actually works although the error is thrown. It's just a bit annoying to see the error and based on https://github.com/webpack/webpack/issues/196 the error should not be ignored. 

Also this trick: https://github.com/webpack/webpack/issues/196#issuecomment-172775900
worked for me, but that's not a great solution.

**Comment by carlo-808** [comment]
Have you tried removing the newrelic import statement from the root .jsx file and starting your app with `node -r newrelic node_modules/.bin/next start`? Do you still get the error?

**Comment by rr0214** [comment]
Hi @SamiraHuber. Support for Next.js out of the box in the agent is on our roadmap. https://github.com/newrelic/node-newrelic/issues/904
