### ISSUE TITLE
Node Garbage collection failures possibly because of newrelic.

### ISSUE THREAD

**Issue by vasu-winzo** [newrelic/node-newrelic#777]
## Description
We started this issue since last three days. Memory utilization and response times of one of the containers starts to increase and it eventually fails with the following stack trace: 
```
<--- Last few GCs --->
[25:0x5610dee65ee0]  1505078 ms: Scavenge 2033.5 (2050.6) -> 2033.0 (2050.6) MB, 14.9 / 0.0 ms  (average mu = 0.225, current mu = 0.162) allocation failure
[25:0x5610dee65ee0]  1505091 ms: Scavenge 2033.7 (2050.6) -> 2033.3 (2051.1) MB, 8.4 / 0.0 ms  (average mu = 0.225, current mu = 0.162) allocation failure
[25:0x5610dee65ee0]  1507633 ms: Mark-sweep 2034.0 (2051.1) -> 2033.3 (2051.1) MB, 2535.4 / 4.1 ms  (average mu = 0.228, current mu = 0.230) allocation failure scavenge might not succeed
<--- JS stacktrace --->
==== JS stack trace =========================================
    0: ExitFrame [pc: 0x5610dd5820d9]
    1: StubFrame [pc: 0x5610dd503631]
    2: ConstructFrame [pc: 0x5610dd5030cf]
Security context: 0x125359e808d1 <JSObject>
    3: wrapTransactionInvocation [0x7c2f76098a9] [/node_modules/newrelic/lib/transaction/tracer/index.js:~101] [pc=0x1983031ddb1f](this=0x24ac79615e01 <Server map = 0x3803218948e9>)
    4: arguments adaptor frame: 3->0
    5: wrappedEmit [0x7c2f76041f1] [/node_modules/newrelic/l...
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

We first thought it was a high throughput and memory usage related issue so we increased the memory available to node using `--max-old-space-size=6000` flag. After this, the container would stay alive for longer, the response times would increase further and it would eventually fail with the same error. 

Can this be a newrelic-node version incompatibility like issue?

## Environment
Newrelic version: 6.14.0
Node: node:12-alpine (docker)
Deployment: ECS, tasks with 6GB RAM.

**Comment by bizob2828** [comment]
Hi @vasu-winzo it's hard to tell with the current context.  However I do notice you're running v6.14.0 of the agent.  We fixed a few memory leaks in the agent so it's best to upgrade to the latest which is v7.5.0.  You may be getting bit by some Promise memory leak issue.  You could try setting 

```
feature_flag: {
  new_promise_tracking: true
}
``` 

in your newrelic.js config. It is worth noting that historically we've seen that the agent tends to make slow memory leaks in user code exponentially worse based on the level of instrumentation that is occurring.  But after trying the suggested options above and you still continue to have an issue you'll probably want to go through [New Relic support](https://support.newrelic.com/).  They will give you the standard first-touch information the support team captures such as trace-level logs, npm ls, etc. so we can dig into this further.

**Comment by vasu-winzo** [comment]
@bizob2828 there has been a drop in memory usage of about 20 - 30 % since we upgraded to 7.5.0 and no issues yes. I think this has solved the issue. I will post on this thread again if the containers fail with a similar stack trace.

**Comment by bizob2828** [comment]
Great, glad the upgrade fixed your memory leak @vasu-winzo!
