### ISSUE TITLE
Providing a stable stub api for unit testing or for injecting newrelic into libraries?

### ISSUE THREAD

**Issue by TysonAndre** [newrelic/node-newrelic#783]
## Is your feature request related to a problem? Please describe.

It is useful to be able to inject a stub for newrelic in libraries, when the application needs to perform initialization (e.g. modify newrelic.enabled or the service name based on the results of a configuration service)
(e.g. it may cause problems if the libraries load newrelic before the application using those libraries has initialized config settings to be returned by newrelic.js before calling `require('newrelic')`)

Additionally, having a stub which can be initialized quickly and definitely has no external dependencies can be useful when unit testing

Additionally, stubs external to newrelic may get out of sync with the actual implementation without maintainers realizing it, causing bugs if newrelic gets disabled/enabled

https://github.com/newrelic/node-newrelic/blob/main/stub_api.js exists, but it is currently undocumented as far as I've seen, and there's no guarantee that `Stub = require('newrelic/stub_api'); newrelic = new Stub();` would work, and there is no guarantee the stub may be refactored or moved.

## Feature Description
Provide a documented way to create a stub (e.g. `require('newrelic/some_stable_stub_api')`, `newrelicStub = require('@newrelic/some-stub')` that would not prematurely load `require('newrelic')`.

## Describe Alternatives
Alternately, document that stub_api is stable in the file itself and in official documentation (e.g. api won't change outside of major versions)

Or recommend alternatives that already exist

## Priority

Nice to Have

**Comment by TysonAndre** [comment]
Something along the following lines can be used as a standalone substitute as a workaround/prototype. This isn't complete and some methods were provided in stub_api dynamically through eval() to avoid the need to manually update stub_api.js - this is missing those.
Most of this is copied directly from the referenced files without the logging statements

```js
/*
 * This is a modified version of newrelic/stub_api.js and newrelic/lib/transaction/handle.js
 * which were provided under the below license.
 *
 * Copyright 2020 New Relic Corporation. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Modifications:
 * 1. Remove logger.debug statements
 * 2. Simplify to use global functions instead of a class, satisfy a different style guide
 */

/* eslint-disable class-methods-use-this */
class TransactionHandleStub {
  end(callback) {
    if (callback instanceof Function) {
      setImmediate(callback);
    }
  }

  ignore() {
  }

  isSampled() {
  }

  acceptDistributedTraceHeaders() {
  }

  insertDistributedTraceHeaders() {
  }
}

// This code gets injected into HTML templates
// and we don't want it to return undefined/null.
exports.getBrowserTimingHeader = () => '';

exports.getTransaction = () => new TransactionHandleStub();

exports.setLambdaHandler = (callback) => callback;

exports.startSegment = (name, record, handler, callback) => {
  if (typeof handler === 'function') {
    return handler(callback);
  }
  return null;
};

exports.getLinkingMetadata = () => ({});

exports.getTraceMetadata = () => ({
  traceId: '',
  spanId: '',
});

exports.startWebTransaction = (url, callback) => {
  if (typeof callback === 'function') {
    return callback();
  }

  return null;
};

exports.startBackgroundTransaction = (name, group, callback) => {
  if (typeof callback === 'function') {
    return callback();
  }

  if (typeof group === 'function') {
    return group();
  }

  return null;
};

// Normally the following call executes callback asynchronously
exports.shutdown = (options, cb) => {
  let callback = cb;
  if (!callback) {
    if (typeof options === 'function') {
      callback = options;
    } else {
      callback = function NewrelicStubShutdownCallback() {};
    }
  }

  setImmediate(callback);
};
```

**Comment by rr0214** [comment]
The stub API is automatically returned when the agent can't bootstrap such as lacking the appropriate configuration. You are welcome to use it. Given our current priorities we are unlikely to work on an official stub API outside of that use case.
