### ISSUE TITLE
node-postgres instrumentation query times incorrect for Promise based calls

### ISSUE THREAD

**Issue by carlo-808** [newrelic/node-newrelic#786]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Instrumentation for asynchronous node-postgres (`pg`) `Client.query` calls are measuring incorrect, extremely short, query times. 

## Expected Behavior

When executing a postgres query with `pg_sleep(1)`, expected query execution time should be ~ 1 second. Example query:
`Select pg_sleep(1)`

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
Reproduction can be found here:
https://github.com/carlo-808/nr-pg-timings

Timings look correct for the synchronous/callback `Client.query` calls like this:
```
client.query(`SELECT pg_sleep(1)`, (err, result) => {})
```

Asynchronous calls for the same query are returning timings in the sub-millisecond range:
```
await client.query(`SELECT pg_sleep(1)`)
```
Look at postgres timings on NROne.

**Comment by rr0214** [comment]
This issue should be looked at prior to https://github.com/orgs/newrelic/projects/41#card-54579148

Already tried setting promise is true on the shim did not seem to fix the problem
