### ISSUE TITLE
Transaction auto-monitoring on MongoDB not working with promises

### ISSUE THREAD

**Issue by richardgarnier** [newrelic/node-newrelic#788]
## Description

When using callbacks, transaction times are correctly reported on MongoDB operations, but these are not shown when using the promise implementation.

Either of these is working:
```js
function withMongoose() {
    return mongoose.model(x).find(query).lean();
}

function withCallbacks() {
    return new Promise((resolve, result) => {
        mongo.db.collection('x').find(query).toArray((err, res) => {
            if (err) {
                reject(err);
                return;
            }
            resolve(res);
        });
    });
}
```

However this is not working:
```js
function withPromises() {
    return mongo.db.collection('x').find(query).toArray();
}
```

Here's what it looks like when we switched from mongoose (withMongoose) to native driver promises (withPromises):
![image](https://user-images.githubusercontent.com/8066261/123647911-ca582d80-d828-11eb-944f-a00232ce3310.png)

## Expected Behavior

I expect the same result with the three methods above.

## Steps to Reproduce

See code snippets.

## Your Environment

NewRelic: 7.5.1
MongoDB (driver): 3.6.4
Mongoose: 5.11.17
Node: 14.16.0

**Comment by bizob2828** [comment]
@richardgarnier I attempted to reproduce but do not see the same behaviors you're describing.  I see the calls to mongo using callback style vs promises are very close.  [Example Code](https://gist.github.com/bizob2828/4dbae20646eeae1f0be3fcd18d4bc666)

**mongodb promised based**:

<img width="971" alt="screenshot 2021-06-28 at 3 07 18 PM" src="https://user-images.githubusercontent.com/1874937/123690925-fa9ccd80-d822-11eb-88b2-70ceb5599b80.png">

**mongodb callback based**:

<img width="1013" alt="screenshot 2021-06-28 at 3 07 43 PM" src="https://user-images.githubusercontent.com/1874937/123690935-fec8eb00-d822-11eb-8868-80d5d308fa16.png">


Just so I can understand a bit better, in that graph you posted, when did you switch from using mongoose(withMongoose) to mongo with native Promises?(withCallbacks)  I assume when the responses for the `MongoDB visits toArray` fell off is when you switched from mongoose to using mongo promised based implementation(withPromises), correct?

Also, do you have distributed tracing enabled by chance? If so, can you post the traces?

**Comment by richardgarnier** [comment]
Thank you for the example code, I will investigate to check whether we're seeing similar behavior, and whether I can modify it to reproduce my issue.

> Just so I can understand a bit better, in that graph you posted, when did you switch from using mongoose(withMongoose) to mongo with native Promises?(withCallbacks) 

I switch when MongoDB visits toArray fell off between the 24th and the 25th. 
I believe it is a typo, but just to clarify, I switched to withPromises not to withCallbacks

> I assume when the responses for the MongoDB visits toArray fell off is when you switched from mongoose to using mongo promised based implementation(withPromises), correct?

Yes, perfectly correct.
Investigating on why the data was not reporting correctly lead me to write withCallbacks which shows accurate data.

> Also, do you have distributed tracing enabled by chance? If so, can you post the traces?

I will check and report together when posting my findings on the sample.

**Comment by richardgarnier** [comment]
Ok I did some more digging, I believe what is missing in your sample, is that the amount of data returned is not enough to showcase the issue.

Here is a small sample that allowed me to reproduce the issue.
I add more and more documents to show that using callbacks scales with the number of documents, whereas using promises does not.
[new-relic-repro.tar.gz](https://github.com/newrelic/node-newrelic/files/6731622/new-relic-repro.tar.gz)

Here are the results:
![image](https://user-images.githubusercontent.com/8066261/123759951-b06a2980-d8c0-11eb-8004-d3200f205b3b.png)

![image](https://user-images.githubusercontent.com/8066261/123760005-bcee8200-d8c0-11eb-9d39-568bdd0f894d.png)

> Also, do you have distributed tracing enabled by chance? If so, can you post the traces?

I am sorry we don't have distributed tracing enabled.

**Comment by bizob2828** [comment]
Thanks for the code snippet @richardgarnier! I can reproduce.  I'm still new on the Node.js agent team but I think the issue is that the mongodb instrumentation isn't built to support `toArray` being a promise vs callback.  I will start working on a fix later today and open a PR against this.  Thanks for submitting the issue and bringing it to our attention!  If you can keep the code snippet where you wrap the call in a native Promise that would be a good workaround for the moment.

**Comment by bizob2828** [comment]
Ok I think I have a fix. This looks better

<img width="769" alt="screenshot 2021-06-29 at 12 22 35 PM" src="https://user-images.githubusercontent.com/1874937/123833798-bcf87d00-d8d4-11eb-81ac-a9c890f46a24.png">

<img width="767" alt="screenshot 2021-06-29 at 12 22 26 PM" src="https://user-images.githubusercontent.com/1874937/123833800-bcf87d00-d8d4-11eb-9a20-d21f3b507acf.png">
 
I will open a PR and get it reviewed by the team
