### ISSUE TITLE
Replace helper.temporarilyOverrideTapUncaughtBehavior

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#799]
Might be able to replace this function in tap tests: helper.temporarilyOverrideTapUncaughtBehavior(tap, t)
Here’s the helper function we may not need anymore:
https://github.com/newrelic/node-newrelic/blob/main/test/lib/agent_helper.js#L387-L394

Used here:
https://github.com/newrelic/node-newrelic/blob/main/test/integration/instrumentation/http.tap.js#L193-L196
https://github.com/newrelic/node-newrelic/blob/main/test/integration/instrumentation/q.tap.js#L78-L82
https://github.com/newrelic/node-newrelic/blob/main/test/integration/instrumentation/when.tap.js#L150-L154
https://github.com/newrelic/node-newrelic/blob/main/test/integration/transaction/tracer.tap.js#L115-L119
https://github.com/newrelic/node-newrelic/blob/main/test/unit/errors/error-collector.test.js#L1785-L1788
https://github.com/newrelic/node-newrelic/blob/main/test/unit/instrumentation/core/domain.test.js#L22-L25
https://github.com/newrelic/node-newrelic/blob/main/test/unit/instrumentation/core/globals.test.js#L18-L29
https://github.com/newrelic/node-newrelic/blob/main/test/unit/instrumentation/http/http.test.js#L1027-L1031
https://github.com/newrelic/node-newrelic/blob/main/test/unit/instrumentation/http/http.test.js#L1071-L1075
https://github.com/newrelic/node-newrelic/blob/main/test/unit/serverless/aws-lambda.test.js#L1464-L1469
(check for more usages)

**Comment by michaelgoin** [comment]
This doesn't really seem to work for at least one of our use cases. We are going to keep the manual override for now.
