### ISSUE TITLE
Possibility of disabling logging or use custom logger

### ISSUE THREAD

**Issue by hungryblank** [newrelic/node-newrelic#82]
In our environment we don't want node applications to write to stdout or write to a file, we'd like to completely disable logging or specify our own function used for logging.

**Comment by adamhathcock** [comment]
Is this still on the table to do?

**Comment by michaelgoin** [comment]
@adamhathcock logging can be turned off via the file-based config or via ENV variable.

```
logging: {
  enabled: false
}
```

OR

`NEW_RELIC_LOG_ENABLED = false`

Using a custom logger is not currently supported but can always be added as a feature request.
