### ISSUE TITLE
DT by Default: Reservoir Performance Testing 

### ISSUE THREAD

**Issue by rr0214** [newrelic/node-newrelic#840]
**What and Why**

This is the first step to the DT by Default work. We'll Run performance tests to confirm the appropriate default span reservoir size recommendation for the agent along with a minimum and maximum possible span size. We want to have a good recommendation on max reservoir size that will not hinder overhead.

**Acceptance Criteria**
Set up a Node test application 
Put cards into Rich's project on steps for performance testing
Work with Rich to run some OATs performance tests 
Produce a DT Span Reservoir Size Benchmark sheet determining overhead for each reservoir size starting at 1,000 until 10,000 along with associated number of spans
Make a decision on our recommendation for default and minimum and maximum possible settings and document results in the launch plan

**Resources**
Instructions
Rich's project Board

**Comment by RichVanderwal** [comment]
That DT by Default OATS Testing project board is [right here](https://source.datanerd.us/agents/oats/projects/2).
