### ISSUE TITLE
Remove instrumentation for oracle 

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#841]
## Is your feature request related to a problem? Please describe.
We have instrumentation for an obsolete library [oracle](https://github.com/joeferner/node-oracle).  It has integration tests but never run because we don't have an easy way to test agent with oracle db.

## Feature Description
Remove instrumentation and tests for oracle.

## Additional context
There is an actively maintained library for oracle support in Node.js [oracledb](https://github.com/oracle/node-oracledb), but this will be prioritized as a separate effort, if ever.  This is technically a breaking change so we have to schedule it during a semver major project bump.

**Comment by michaelgoin** [comment]
https://issues.newrelic.com/browse/NR-33408

**Comment by bizob2828** [comment]
closing as we are tracking in jira
