### ISSUE TITLE
Add `noticeError()` example

### ISSUE THREAD

**Issue by linbaker** [newrelic/node-newrelic#850]
## Feature Description

Add an example for `noticeError()`

There is an example buried in the background transaction examples:
https://github.com/newrelic/node-newrelic/blob/main/examples/api/background-transactions/example4-promises.js#L30

But this example is hard to find and does not show how to add custom attributes. 

The API docs better describe the parameters, but could also use an example:

* https://newrelic.github.io/node-newrelic/docs/API.html#noticeError 

May also need to edit the docs site as there may be some confusion from the `\` and the use of `customParameters` rather than `customAttributes`:

* https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/nodejs-agent-api/#noticeError

## Additional context

Issue started as a Docs site issue: https://github.com/newrelic/docs-website/issues/3560

## Priority

Nice to Have

**Comment by carlo-808** [comment]
Thanks @linbaker !
