### ISSUE TITLE
GCP pubsub + app instrumentation

### ISSUE THREAD

**Issue by estfe** [newrelic/node-newrelic#858]
Hello,

My node app subscribes from a GCP pub/sub, do whatever it needs to be done and publish the result to another pub/sub.

I can't see any data in NR... just the app name block in "service map".   I would like to see everything, but at least the methods being executed after the the app receives the content from the pub/sub, in distributed tracing.

What steps should I follow? Should I create a background transaction for this? 
Is there any adicional configuration in newrelic.js that I must add?
Does every function/method from the transaction chain must be configured as a background transaction? After doing this, will I be able to see them at "service map" view?

I couldn't understand what needs to be done by reading the docs.

ps: NR is properly installed and configured. I can see data from other apps. I'm just not sure how to act in this case.

Regards.

**Comment by michaelgoin** [comment]
Hi @estfe,

This sort of troubleshooting is typically best done via our support over at https://support.newrelic.com, given we sometimes need to dig into sensitive details and do a lot of back and forth.  You've got some great targeted questions, so I'll see what I can do for you here but we may end up moving out of GitHub issues.

For pub/sub libraries we don't instrument, such as GCP, you'll need to manually create a background transaction on the consumer-side. Typically, your publish-side will already have a transaction unless you are publishing via background-processes / scripts in which case you'll also need to create a transaction there.

Taking a super shallow look at https://www.npmjs.com/package/@google-cloud/pubsub (assuming this is what you are using?), creating a transaction on the receiving end will likely look similar to the following...


```js
subscription.on('message', message => {
  newrelic.startBackgroundTransaction('Message Consumer', () => {
    // Required to keep transaction open if doing any async work.
    const transaction = newrelic.getTransaction()

    // Pass in true if you want metrics generated
    // doTheWork === what you want to measure before ending the transaction.
    newrelic.startSegment('doTheWork', false, doTheWork, function callback() {
      // End the transaction when the work has completed.
      // In this case, `doTheWork` is passed `callback` and invokes it after 
      // various async activities.
      transaction.end()
    })
  })
});
```

http://newrelic.github.io/node-newrelic/docs/API.html#startBackgroundTransaction
http://newrelic.github.io/node-newrelic/docs/API.html#startSegment

You'll want to ensure Distributed Tracing (DT) is enabled in your config, as it is currently disabled by default.

Similar to `doTheWork` above, you'll need to custom-instrument using `startSegment()` any of your functions you want to show up in DT associated with the transaction. Things we auto-instrument should automatically show up. Keep in mind spans are subject to sampling so distributed traces may not always display all instrumented methods depending on the quantity captured. These custom items will also show up in transaction traces when captured.

You may also want to custom instrument the publish side, although you may already see that captured as an external depending on how the client behaves. This would not require a transaction (assuming you already have one) but may require a custom segment if you want obviously represented as the publish. This is likely lower priority.

Finally, we'll have to manually wire-up processing the distributed tracing headers. Typically for pub/sub, we need to add the headers outgoing to whatever mechanism is available for the library and then manually consume them.

In the pub side, `insertDistributedTraceHeaders` can be used to write the appropriate headers to an object. This object can then be sent with the message.http://newrelic.github.io/node-newrelic/docs/TransactionHandle.html#insertDistributedTraceHeaders

On the sub side, `acceptDistributedTraceHeaders` can be used to take the DT headers sent along with the message and process them to associate the two traces together into the same distributed trace. http://newrelic.github.io/node-newrelic/docs/TransactionHandle.html#acceptDistributedTraceHeaders

Again, taking a quick stab looking at that assumed library and I'm guessing it will look something like the following...

```js
function publish() {
  const customAttributes = {
    origin: 'nodejs-sample',
    username: 'gcp',
  };

  const transaction = newrelic.getTransaction()
  // Adds New Relic DT headers
  transaction.insertDistributedTraceHeaders(customAttributes)

  const messageId = await pubSubClient
    .topic(topicName)
    .publish(dataBuffer, customAttributes);
}
```

```js
function consume(message) {
  const attributes = message.attributes

  const transaction = newrelic.getTransaction()
  // Tell New Relic to process DT headers added to the passed-in object
  transaction.acceptDistributedTraceHeaders(attributes)
}
```

OR to give the example in the context of the earlier code snippet...

```js
subscription.on('message', message => {
  newrelic.startBackgroundTransaction('Message Consumer', () => {
    // Required to keep transaction open if doing any async work.
    const transaction = newrelic.getTransaction()
    transaction.acceptDistributedTraceHeaders(message.attributes)

    // Pass in true if you want metrics generated
    // doTheWork === what you want to measure before ending the transaction.
    newrelic.startSegment('doTheWork', false, doTheWork, function callback() {
      // End the transaction when the work has completed.
      // In this case, `doTheWork` is passed `callback` and invokes it after 
      // various async activities.
      transaction.end()
    })
  })
});
```

These may or may not be particularly how you *should* use that library or perhaps you are using a different one, but hopefully will be a good starting point.

**Comment by michaelgoin** [comment]
Closing this out as an answered question but we'll continue to respond if the conversation continues.
