### ISSUE TITLE
DT Enabled - add supportability metric to track final set span event limit

### ISSUE THREAD

**Issue by carlo-808** [newrelic/node-newrelic#862]
Add the supportability metric `Supportability/SpanEvent/Limit` to track the set span event limit after the receiving the server enforced limit.
Set the `Supportability/SpanEvent/Limit` value to the Span Event Limit used by the agent.

The spec for the supportability metric is still in PR as of this writing:
https://source.datanerd.us/agents/agent-specs/pull/561/files#diff-84129716d24d72f7b47506e2af179810R361

Most likely need to report the metric [here](https://github.com/newrelic/node-newrelic/blob/5c06db7a51d09320897068b1b12c8393b238fb7d/lib/spans/span-event-aggregator.js#L132) after the final span limit has been set *OR* the metric can be reported [here](https://github.com/newrelic/node-newrelic/blob/main/lib/spans/span-event-aggregator.js#L95), closer to where it will be used.

**Comment by bizob2828** [comment]
To query NR run the following NRQL
```
SELECT uniqueCount(account_id) as Accounts FROM Supportability WHERE name LIKE 'Supportability/SpanEvent/Limit' FACET name SINCE 7 days AGO
```
