### ISSUE TITLE
fastify: the interface of the fastify shim seems incorrect

### ISSUE THREAD

**Issue by meeech** [newrelic/node-newrelic#865]
The interface of the fastify shim seems incorrect.

Without the new relic shim:

```javascript
const fastify_1 = require('fastify');
console.log('index 2 >', fastify_1);
console.log('index 3 >', fastify_1.fastify);
```

Output:

```javascript
index 2 > <ref *1> [Function: fastify] {
  fastify: [Circular *1],
  default: [Circular *1]
}

index 3 > <ref *1> [Function: fastify] {
  fastify: [Circular *1],
  default: [Circular *1]
}
```

With the newrelic fastify shim `NEW_RELIC_FEATURE_FLAG_FASTIFY_INSTRUMENTATION=1`

```javascript
require('newrelic');
const fastify_1 = require('fastify');
console.log('index 3 >', fastify_1);
console.log('index 4 >', fastify_1.fastify);
```

Output:

```javascript
index 3 > [Function: wrappedFastifyModule] { __NR_instrumented: true }
index 4 > undefined
```

This then leads to breaking anything else that may be expecting the `.fastify` on the module returned from require.

[package_json_and_index_js.zip](https://github.com/newrelic/node-newrelic/files/7094609/package_json_and_index_js.zip)

**Comment by michaelgoin** [comment]
Hi @meeech,

Thank you for the bug submission. It looks like we are failing to propagate some details after wrapping. We'll take a look and let you know what we find.

**Comment by meeech** [comment]
that is a super fast response. :D. thanks @michaelgoin

**Comment by michaelgoin** [comment]
Looks like in v2 of fastify (current major when instrumentation was written), it exported a 'build' function that did not have these additional properties.

With v3, it now exports a 'fastify' function that has the 'default' and 'fastify' properties which also seem to be 'fastify' functions. Given these seem to be similar functions, I'm guessing we'll need these instrumented not just copied over. Perhaps there's a singular location that can be instrumented. This may result in loading instrumenting slightly different for v2 VS v3.

The existing instrumentation is pretty simple but done in the traditional wrapping style which is more prone to these sorts of issues with major releases. As we look at fastify going forward we should consider if a hooks-based approach would be more appropriate. While awkward with some of our existing APIs, we've gotten this sort of appropriate to work with Apollo Server, for example.

**Comment by michaelgoin** [comment]
@meeech would you be willing to share any concrete use cases for how `.fastify` or `.default` are used? Any relevant docs you think would be good for reference would be nice to have too. We can poke around but we'll want to make sure we've gotten some key bases covered.

Thanks!

**Comment by meeech** [comment]
@michaelgoin sure!

So a few more details. 

1) When I manually resolve the issue in the dependency, then I was getting the full transactions in NR with no changes to the new relic module - so the instrumentation was working (well, the transactions - i can't speak for all the instrumentation).

2) Here is the specific use case for me

we are using NestJS, which has a fastify-adapter (https://www.npmjs.com/package/@nestjs/platform-fastify). 
This is in typescript, which get converted to

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FastifyAdapter = void 0;
const common_1 = require("@nestjs/common");
const load_package_util_1 = require("@nestjs/common/utils/load-package.util");
const http_adapter_1 = require("@nestjs/core/adapters/http-adapter");
const fastify_1 = require("fastify");
const Reply = require("fastify/lib/reply");
class FastifyAdapter extends http_adapter_1.AbstractHttpAdapter {
    constructor(instanceOrOptions = fastify_1.fastify()) { // <--- If i wasn't passing in some options, probably would have broke here too. 
        const instance = instanceOrOptions && instanceOrOptions.server
            ? instanceOrOptions
            : fastify_1.fastify(instanceOrOptions); // <--- So here we break, since fastify_1.fastify doesn't exist.
        super(instance);
    }
.....
```
So looking into why it wasn't working, led to this ticket. I know I can work around it be setting up the instance myself and passing it in (which I may just do for now) but ideally we could just fix the NR shim. 

So I guess this would be a problem for any other deps one might add to a fastify project that rely on  require('fastify') .

lmk if there's anything else.

**Comment by michaelgoin** [comment]
Hi @meeech ,

Thanks for the additional info!

It looks like we are going to do an effort soon to solidify some fastify concepts and get it out of behind a feature flag. It may end up as auto-applied instrumentation like it currently is or may become a separate plugin module.

Either way, we'll be sure to make sure the effort solves for this use case.

I don't want to dig too deep into a perfect solution right now, as the general approach may change very soon. That being said, I could probably do a quick fix of simply propagating the properties over to the wrapped item which sounds like it would solve your issue.

If you don't need this right away / are comfortable with the manual work-around on your end, then we will just tackle with this next effort. If this is blocking you and you'd prefer something right away, then I can do the short-term quick fix.

Let me know what you think.

**Comment by meeech** [comment]
@michaelgoin For me, would be nice to have the quick fix in NR for now, so I can move forward with our instrumentation. would be prefered, since a manual workaround would be tricky. (i was able to do it just to verify the issue)

**Comment by michaelgoin** [comment]
@meeech what should be a fix for at least the initial interface problem shipped with the latest release.

**Comment by meeech** [comment]
@michaelgoin thanks! yeah, i kept reloading the npm info page to see when it was published. Its installed, working ok so far.  Just have the ui bug (#757), but can live with that since its just cosmetic. I appreciate the quick turnaround. 

thanks 👍🏼
