### ISSUE TITLE
Automatically add new issues to the Engineering board.

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#866]
Currently, we rely on the engineer doing initial triage of an issue to ensure issues get added to the engineering board.

This sometimes gets missed, resulting in issues that are in limbo and sometimes missed. Ideally, we can automate this.

I believe I've heard of other teams doing this via a GitHub action workflow triggered via Issue create, since there's doesn't seem to be built-in auto-assign but some time researching potential approaches is warranted.

Ideally, this would also capture re-opened issues that may not yet be associated with the project.

**Comment by bizob2828** [comment]
Looks like we could just wire this action up in every repo https://github.com/marketplace/actions/assign-to-one-project
