### ISSUE TITLE
Document feature flags

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#870]
Add a page (or section) to documentation to document the feature flags.

Considerations:
* We'll want to ensure a good way of keeping this up to date. Not necessarily with rev 1 but worth putting some thought into up front. 
* We'll either want to omit from documentation or clearly note when we do not want customers to self-select into a feature-flag. An example may be a partially implemented set of functionality that is behind a flag to allow for safely shipping at all times or a riskier feature-flag that can break certain situations.
* Other?

At least to start, I'm thinking this documentation should live in the repository itself. Either directly on the readme or a separate doc file linked from the readme.

**Comment by bizob2828** [comment]
let's do this in the async local storage feature
