### ISSUE TITLE
Remove Feature Flag for Fastify Support and Formalize

### ISSUE THREAD

**Issue by rr0214** [newrelic/node-newrelic#880]
**Background**

According to the [State of JS users survey](url), Fastify is one of the top 3 frameworks that users are most interested in and satisfied with. We have some primary support of Fastify behind a feature flag and it is time to make that support official.

**What we will do**

The goal of this effort is to remove the feature flag and formalize that support

**Acceptance criteria**

- Remove feature flag
- Add appropriate tests
- Add documentation about official support for Fastify

**Comment by michaelgoin** [comment]
We will need to make sure the final solution takes into account this issue: https://github.com/newrelic/node-newrelic/issues/865.

Particularly, if we stick with traditional instrumentation we'll need to see if there are situations where we need the .default / .fastify property functions to be instrumented and what that looks like. I'm assuming if we go the plugin route we won't need to worry about these.

I plan to attempt a quick fix to merely propagate the properties via the current solution but will not dig further given this work is coming up.

**Comment by michaelgoin** [comment]
https://www.fastify.io/docs/latest/Plugins-Guide/
