### ISSUE TITLE
Test Running Node Agent on Arm64 Processor Environment

### ISSUE THREAD

**Issue by rr0214** [newrelic/node-newrelic#898]
## Is your feature request related to a problem? Please describe.
We would like to an AWS Graviton Partner. To do that, our agent needs to run on an ARm64 processor.

## Feature Description
This effort is to determine the feasibility of running the Node agent on an Arm64 processor.  

The desired outcome is to check that a sample app running the agent is reporting data. 

## Additional context
[Initiative Document](https://docs.google.com/document/d/1Y41Angdd96mNdrOnVyEXsQc_3W6hf2sUYwNmcjzlvhA/edit#)
[ARM64 Partership](https://aws.amazon.com/ec2/graviton/partners/)

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have, Really Want, Must Have, Blocker]

**Comment by bizob2828** [comment]
I verified the agent works just fine on arm64 architectures

## Specs
* Amazon Linux 2 arm64
* t4g.micro

## Set up of ec2 instance
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
source ~/.bashrc
nvm install 16
nvm install 14
nvm install 12
sudo yum install git /usr/bin/g++ -y
git clone git@github.com:Contrast-Security-OSS/NodeTestBenches.git
cd NodeTestBenches/fastify
nvm use 14
npm install
npm install newrelic
# copy new relic config 
node -r newrelic server.js
# Make requests, 🎉
cd perf
# generate load for test results
CONNECTION_COUNT=1 node run.js
```

Link to running app: https://staging.onenr.io/0PLREN9klja

<img width="2232" alt="screenshot 2021-09-14 at 4 10 44 PM" src="https://user-images.githubusercontent.com/1874937/133326912-dd16faf6-6cff-49eb-b831-c40304d3af14.png">

<img width="1887" alt="screenshot 2021-09-14 at 4 11 31 PM" src="https://user-images.githubusercontent.com/1874937/133327006-ff7a8b15-8f49-440e-a234-9486125f65fa.png">
