### ISSUE TITLE
Avoid private implementation details in examples

### ISSUE THREAD

**Issue by garbados** [newrelic/node-newrelic#912]
## Is your feature request related to a problem? Please describe.

Some of the examples in `examples/` refer to implementation details that are not intended for public consumption, such as private or protected methods (see: https://github.com/newrelic/node-newrelic/issues/564). Our examples should be more flexible wherever possible and not rely on such implementation details. 

## Feature Description

Examples should avoid implementation details where possible, opting for general counsel about introspecting systems for instrumentation instead. For example, sharing *how* to find pertinent implementation details, rather than *where* they were found, as that *where* may change even as the *how* remains useful.

## Describe Alternatives

🤷‍♀️ 

## Priority

Nice to Have

cc @michaelgoin

**Comment by coreyarnold** [comment]
Incorporated into team working agreements and the moving toward concrete working examples in the newrelic-node-examples repo.
