### ISSUE TITLE
Allow undici to understand a header to disable DT

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#935]
## Is your feature request related to a problem? Please describe.
Our aws-sdk instrumentation sets a symbol as a header which is then parsed by the http-outbound instrumentation to decide if DT should be disabled.  This will not work in undici because at every hook point we have the headers have been parsed from an Object to a string.  If the aws-sdk ever supports undici as the http client, this will become a problem.  This is all hypothetical but called out in #921.  

## Feature Description
Provide an ability to disable DT from aws-sdk instrumentation that is properly parsed by undici instrumentation.

## Additional context
We could probably just pass along an x header as and undici instrumentation look for it to decide if we want to disable DT for undici.  Then we could even remove the header from the string before it actually made the http request

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice To Have]

**Comment by artur-ma** [comment]
I dont think the will support undici in 2.x (since it will be deprecated at some point), but they do support custom http client in 3.x , but u do not support 3.x yet, to support it u will  change you instrumentation anyway https://github.com/newrelic/node-newrelic-aws-sdk/issues/86

**Comment by bizob2828** [comment]
We're closing as this is not an issue.  If it ever becomes an issue we can log a ticket to capture the steps to reproduce
