### ISSUE TITLE
Remove default HTTPS port from external segments via http module

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#945]
Creating GitHub issue for TODO in code: https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentation/core/http-outbound.js#L52-L58

Currently default HTTP port is excluded from external naming but not the default HTTPS port.

We've now implemented Undici with the intended behavior in the comment of excluding both default ports from the external naming.

I'm not sure what defines not including the default port. May want to cross reference specs to verify if this is a requirement or a preference at the time. That being said, consistency would be good between our external library captures.

This would require a major version bump. It *does* change behavior on customers so I def would double-check this is a documented requirement. If not, consider the tradeoff with regards to changing things on customers.

**Comment by michaelgoin** [comment]
https://issues.newrelic.com/browse/NR-35652

**Comment by bizob2828** [comment]
Closing as this is being tracked in the jira issue
