### ISSUE TITLE
Undefined agent when calling recordMetric after typescript upgrade

### ISSUE THREAD

**Issue by andrejleitner** [newrelic/node-newrelic#956]
## Description

After upgrading `typescript` from `4.3.5` to `4.4.4`, the newrelic agent started crashing with the following error:

```
TypeError: Cannot read property 'agent' of undefined
    at recordMetric (~/myProject/node_modules/newrelic/api.js:987:30)
```
coming from:

```
setInterval(() => recordMetric('myMetric', myMetricVariable), 60 * 1000);
```

## Expected Behavior

The agent will be defined.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Newrelic version: 8.5.0
* Node version: 14.15.0

**Comment by michaelgoin** [comment]
@andrejleitner Looks to be an issue with the code TypeScript 4.4.4 generates for that style of import. It *seems* like a TypeScript bug to me but I'm not sure what sorts of constraints they currently encourage around importing of CommonJS modules.

The default branch generates the following JS:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const newrelic_1 = require("newrelic");
setInterval(() => newrelic_1.recordMetric('SampleTestMetric', 123), 8 * 1000);
```

You can see here it imports `newrelic` and then executes directly on that API instance and as such the `this` operator is just fine.

On the `typescript-issue` branch / with TypeScript 4.4.4, it generates some odd code...

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const newrelic_1 = require("newrelic");
console.log(newrelic_1.recordMetric);
setInterval(() => (0, newrelic_1.recordMetric)('SampleTestMetric', 123), 8 * 1000);
```

Here, the `(0, newrelic_1.recordMetric)` will in fact return the `recordMetric` function but now we'll be executing it outside of the context of the API instance and so `this` is `undefined`. It is some odd / unnecessary seeming code gen. 

Directly importing the API will avoid this and generate appropriate code.

Either of these will work:

```js
import * as newrelic from 'newrelic'
// OR
import newrelic = require('newrelic')
```

And then you can invoke the function as such:

```js
newrelic.recordMetric('SampleTestMetric', 123)
```

I've tested these imports out and they worked just fine and generated the code you'd expect.

**Comment by andrejleitner** [comment]
Yep, I see. The question is if direct import `import {recordMetric} from "newrelic";` should also work.

**Comment by mscharley** [comment]
I ran into the same error while trying to use `import { noticeError } from 'newrelic'`. 

Using `import * as newrelic from 'newrelic'` got me `newrelic.noticeError is not a function`. What worked was `import newrelic from 'newrelic'`. This may vary depending on the `esModuleInterop` option in typescript.

**Comment by andrejleitner** [comment]
Heya, @michaelgoin, it still does not work with the latest versions (`newrelic`: 9.8.1, `typescript`: 4.9.5). Do you really wanna keep it like this (direct function imports without the API instance context)😞?

**Comment by wu-json** [comment]
+1 to what @andrejleitner said. Improper imports should give us TypeScript errors... This could easily cause an incident if someone upgrades TypeScript and does not know about this issue.
