### ISSUE TITLE
Support for Sequelize

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#957]
Split off from: https://github.com/newrelic/node-newrelic/issues/526

## Feature Description

Out of the box support for Sequelize ORM module.

## Describe Alternatives

- Custom instrumentation of Sequelize calls (app controllers - 1000+ hence not pragmatic without using a middleware library)
- Removing Sequelize library is not a pragmatic move either 

## Additional context

Sequelize NPM: https://www.npmjs.com/package/sequelize (1,131,990 downloads weekly)

**Comment by bizob2828** [comment]
This [example app](https://github.com/newrelic/newrelic-node-examples/tree/main/sequelize-app) shows sequelize working with pg as it just uses the underlying pg instrumentation
