### ISSUE TITLE
Process crash if unable to read /proc/cpuinfo and /proc/meminfo

### ISSUE THREAD

**Issue by jstaro** [newrelic/node-newrelic#967]
`parseProcCPUInfo(data)` and `parseProcMemInfo(data)` cannot handle when `data` is `null`, which happens if the library was unable to read `/proc/cpuinfo` and `/proc/meminfo`

## Description

I am working on a node app capable of running both on multiple hardware devices and now in the cloud, so they now have restricted things to target a subset of functionality.

It turns out you now get an `ENOENT` when trying to cat `/proc/cpuinfo` and `/proc/meminfo`.

There is error handling in `readProc`, returning `null` if an error occurs, but the parsing functions cannot deal with that parameter being `null`. These parsing functions otherwise gracefully handle not being able to parse the string data, so my suggestion would be adding null-checking guard statements before trying to parse.

## Expected Behavior

The library should gracefully handle not being able to read `/proc/cpuinfo` and `/proc/meminfo`.

## Steps to Reproduce

N/A

## Your Environment

node-newrelic version: 8.5.0
Node version: 12.16.1
Operating System and version: unknown, custom Linux distro

**Comment by michaelgoin** [comment]
Hi @jstaro,

Thank you for the issue. That is definitely not a use case we account for but looks like it is straightforward enough to handle.

**Comment by michaelgoin** [comment]
@jstaro Got a quick fix out today with v8.5.1. Hopefully that resolves your issue.
