### ISSUE TITLE
Fastify transaction naming

### ISSUE THREAD

**Issue by ISulimanov** [newrelic/node-newrelic#974]
## Description

According to https://github.com/newrelic/node-newrelic/pull/354 , if I understand correct we should have proper transactions name.

## Expected Behavior

All transactions have proper name on Transactions page

## Actual Begavior

All transactions have * instead of name

![image](https://user-images.githubusercontent.com/7904096/141315529-ea6ed92c-336f-4a6d-bedc-d63ca97040ac.png)

## Steps to Reproduce

- Clone official demo Nest with Fastify from https://github.com/nestjs/nest/tree/master/sample/10-fastify
- Add newrelic according to official doc
- Run app and make few requests

## Your Environment

Node.js version | v16.13.0
OS version | Windows 10.0.18362
NodeJs Agent | 8.5.2

**Comment by bizob2828** [comment]
@ISulimanov I cannot reproduce.  I see transactions just fine.

<img width="1150" alt="screenshot 2021-11-11 at 10 23 51 AM" src="https://user-images.githubusercontent.com/1874937/141323729-dc793c5d-bdf4-45b1-96a1-85da862bb8c6.png">

The steps I took:
 * Clone [Fastify Nest Sample App](https://github.com/nestjs/nest/tree/master/sample/10-fastify)
 * `npm install && npm install newrelic`
 * `npm run build`
 * `node -r newrelic dist/main.js`

If you're still having trouble it might be best to go through our support team so they can ask for logs and help troubleshoot deeper.

**Comment by jungRoit** [comment]
I'm facing the same error @ISulimanov @bizob2828. What steps did you take to get it to work as intended?

**Comment by rwojsznis** [comment]
Samies, I'm using [this approach](https://github.com/fastify/fastify/blob/main/docs/Guides/Testing.md#separating-concerns-makes-testing-easy) regarding separating concerns - any chance it's related? 🤔

fastify 3.28.0, node v16.14.2, newrelic 8.14.1

edit: before even submitting comment I'm going to answer my own question - it's seems like that's the case. @jungRoit - given example linked above, if have something like:

```js
const server = require('./app')({
  logger: {
    level: 'info',
    transport: {
      target: 'pino-pretty'
    }
  }
})
```

can you try wrapping `server` in newrelic as follows:

```js
newrelic.instrumentLoadedModule(
  'fastify',
  server
);
```

and let me know if it helped?
