### ISSUE TITLE
recordConsume doesn't time promises correctly

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#977]
Noticed this while double-checking my aws-sdk v3 experiment was capturing appropriate timing.

`recordConsume` is setup a bit differently than `recordProduce` which does time things correctly. Produce goes through a more standard `shim.record()` flow. In this flow, `_doRecord` bind the promise which does a 'touch' on the segment to update timing and clears the opaque flag. Consume is much more manual and does not do anything on promise resolve.

I'm not sure why the Consume version is so manual.

A quick fix can likely be accomplished by adding this copy/pasta from `_doRecord` in the short term:

```
if (msgDesc.promise && shim.isPromise(ret)) {
  shim.logger.trace('Binding return value as Promise.')
  ret = shim.bindPromise(ret, segment)
 }
```

A hacked local test seemed to resolve the issue but I did not look or test in-depth.

**Comment by garbados** [comment]
> I'm not sure why the Consume version is so manual.

Aside from a quick fix, should we adapt recordConsume to better match the approach of recordProduce? What will that look like?

**Comment by michaelgoin** [comment]
@garbados I don't know the answer as I'm not sure why it has diverged in the first place. I'd have to guess there's something about the record approach that doesn't work for this use case and/or this one needed extra. Would likely need to dig through git/Jira history to see what (if anything) artifacts exist to get a feel and look at the code closely to see how diverges and if can be solved more consistently.

Certainly, I think that is a worthy goal. Whether up front or as a fast-follow. If not possible to align, we could at least document why and maybe capture how to resolve if more involved to make tweaks to improve.

**Comment by garbados** [comment]
Fair enough. Once we have a bead on the cause of the divergence, we could at least spruce up the function's comments to explain the reason.
