### ISSUE TITLE
Add support for Pino log enricher

### ISSUE THREAD

**Issue by omusil24** [newrelic/node-newrelic#988]
## Is your feature request related to a problem? Please describe.
Currently only Winston is supported for enriching logs via the @newrelic/winston-enricher module, but we are using Pino for logging. This makes it inconvenient or impossible to use the Node Logs In Context feature with Pino and/or other logging libraries.

## Feature Description
Add support for Pino and possibly other common Node.js logging frameworks/libraries like Bunyan, so that Logs In Context feature can be used with them.

## Priority
Really want

**Comment by bizob2828** [comment]
Linking a previous feature request in the winston log enricher repo https://github.com/newrelic/newrelic-winston-logenricher-node/issues/47

**Comment by bizob2828** [comment]
@omusil24 we lost track of duplicate tickets. but we added support for this last month(January 2022)

We released a beta version of this log enricher: `@newrelic/pino-enricher`

  * [GitHub repo](https://github.com/newrelic/newrelic-node-log-extensions/tree/main/packages/pino-log-enricher)
  * [Npm package](https://www.npmjs.com/package/@newrelic/pino-enricher)

Please try it out and give us feedback.  Also, PRs are welcome

**Comment by omusil24** [comment]
@bizob2828 thank you. Unfortunately I am working somewhere else and I am not going to use it right now. But as soon as I will be working on Node+Pino stuff again, I will try it.
