### ISSUE TITLE
Fully release/remove await_support feature flag.

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#990]
The `await_support` has been enabled by default since v2.3.0 of the agent. This gates using async_hooks to track native promises in a way that works with async-await.

Removing this feature-flag will allow us to remove usage of the old, manual style of promise instrumentation for native promises. It will still be used for bluebird and when I believe. This will allow us to do do some cleanup and is a step towards preparing for using AsyncLocalStorage in the future. Disabling `await_support` is not something we will be able to support with that new functionality.

Likely not fully representative (given current limitations) but I'm seeing 3 uses disabling this feature in the wild. There may be more but it looks to be extremely small and likely for very old versions of the agent.

**Comment by michaelgoin** [comment]
https://issues.newrelic.com/browse/NR-35651

**Comment by bizob2828** [comment]
closing as we are tracking in jira
