### ISSUE TITLE
Support for Prisma as a datastore

### ISSUE THREAD

**Issue by wpoynter** [newrelic/node-newrelic#991]
## Is your feature request related to a problem? Please describe.
Prisma has made the decision not to use the standard `pg` and `mysql` packages and instead use its own engines, therefore the interaction with Postgres and/or MySQL are not instrumented. Although you can (and I have) use custom attribution, it lacks the richness of the datastore collection.

## Feature Description
Support as much observability for Prisma Engine usage as pg and MySQL, within reason. 

## Describe Alternatives
The two alternatives I can think of are to rely on existing methods to instrument the database separately and use the custom attribution available (e.g. `startSegment`). Or to extend the existing custom methods to be able datastore interactions in greater depth.

## Additional context
I/Tinto (the company I work for) are willing to do the work needed if New Relic agrees this feature is a good idea, but we would need guidance on the correct way to do the work that is inline with NR styling. I have had a read of the Postgres code and the shim code and it is not immediately clear how to develop an "instrumentation" from scratch.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Really Want

**Comment by michaelgoin** [comment]
Hi @wpoynter,

Thank you for the feature request. 

To double check, you are referring to: https://www.npmjs.com/package/@prisma/client?

**Comment by keithbro** [comment]
Hello! This is also of interest to us.

> To double check, you are referring to: https://www.npmjs.com/package/@prisma/client?

Yes I believe he is.

Prisma can [emit query events](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#event-types) which look like:

```
{
  timestamp: 1641438503151,
  query: 'SELECT "public"."Trip"."id", "public"."Trip"."createdAt", "public"."Trip"."updatedAt", "public"."Trip"."name" FROM "public"."Trip" WHERE 1=1 LIMIT $1 OFFSET $2',
  params: '[1,0]',
  duration: '5',
  target: 'quaint::connector::metrics'
}
```

So it feels like it should be possible to hook this up to the datastore instrumentation logic. The issue I'm seeing is that the datastore hooks [as described here](https://newrelic.github.io/node-newrelic/docs/tutorial-Datastore-Simple.html) are more geared towards wrapping function calls than handling events. Perhaps there's an easy way to do this that I'm missing.

Any assistance would be very much appreciated.

**Comment by sankarpa** [comment]
Do we have an ETA when this be ready for use?

Its really hard to monitor the databases when using prisma. :)

**Comment by Geczy** [comment]
any update?

**Comment by niels-van-den-broeck** [comment]
Also looking for this. Is there any update if this will be added at any time?

**Comment by bizob2828** [comment]
We are currently working on a solution to this.  However it's taking a new hybrid approach of gluing New Relic based traces and spans with opentelemetry spans.  We plan on making this work open source shortly.

**Comment by Geczy** [comment]
ETA?

**Comment by bizob2828** [comment]
@Geczy Within this quarter is a reasonable ETA we can provide. we will make sure to communicate on this thread and others as soon as possible.  Are you using opentelemetry at all at the moment along with the New Relic Node.js agent?

**Comment by Geczy** [comment]
> @Geczy Within this quarter is a reasonable ETA we can provide. we will make sure to communicate on this thread and others as soon as possible. Are you using opentelemetry at all at the moment along with the New Relic Node.js agent?

yes im using both

**Comment by whusted** [comment]
> @Geczy Within this quarter is a reasonable ETA we can provide. we will make sure to communicate on this thread and others as soon as possible. Are you using opentelemetry at all at the moment along with the New Relic Node.js agent?

This quarter is almost up, can you provide an update?

**Comment by kibertoad** [comment]
@whusted Wasn't prisma support released already?

**Comment by bizob2828** [comment]
@whusted it was released in [9.11.0](https://github.com/newrelic/node-newrelic/releases/tag/v9.11.0)

**Comment by whusted** [comment]
Amazing, thank you

**Comment by Geczy** [comment]
i had to uninstall newrelic because it was causing memory leaks, but great work on the release boys

**Comment by gustavolzangelo** [comment]
@bizob2828 do I have to set up something to show up on NewRelic? I currently have a NestJS setup with Prisma, but I can't see any log related to Prisma there
